export const c1Assessments = [
  { lesson: 1, prompt: '¿Cuál es el punto de partida correcto para delimitar una operación controlada?', options: ['Elegir el método con mejor resultado', 'Identificar hechos, términos, FAR y circunstancias relevantes', 'Buscar comparables externos', 'Calcular un rango intercuartil'], correctIndex: 1, feedback: 'La delimitación comienza por comprender qué ocurrió realmente y bajo qué condiciones económicas.' },
  { lesson: 2, prompt: 'Un contrato describe servicios mensuales, pero la entidad prestadora no tiene personal, terceros ni evidencia de ejecución. ¿Qué procede?', options: ['Aceptar el contrato como prueba suficiente', 'Aplicar Cost Plus', 'Analizar si el servicio ocurrió realmente', 'Clasificar automáticamente como regalía'], correctIndex: 2, feedback: 'El contrato es evidencia relevante, pero debe contrastarse con la conducta y la capacidad real de prestar el servicio.' },
  { lesson: 3, prompt: '¿Cuál de los siguientes NO es una característica económicamente relevante?', options: ['Términos contractuales', 'Funciones, activos y riesgos', 'Circunstancias económicas', 'Color corporativo del logotipo'], correctIndex: 3, feedback: 'La delimitación se concentra en condiciones capaces de afectar económicamente la operación.' },
  { lesson: 4, prompt: '¿Qué evidencia es especialmente importante para determinar quién controla un riesgo?', options: ['Quién aparece nombrado en el contrato', 'Quién toma decisiones sobre aceptar, evitar o mitigar el riesgo', 'Quién tiene más empleados', 'Quién emite la factura'], correctIndex: 1, feedback: 'El control del riesgo se vincula con decisiones sustantivas y capacidad real, no sólo con una asignación contractual.' },
  { lesson: 5, prompt: '¿Cuál es la descripción más útil para fines de delimitación?', options: ['Compra-venta con parte relacionada', 'Pago intercompañía', 'Adquisición recurrente de producto terminado para distribución local por una entidad que realiza funciones rutinarias de venta', 'Contrato comercial'], correctIndex: 2, feedback: 'Una descripción fuerte identifica la naturaleza económica y los elementos funcionales relevantes.' },
  { lesson: 6, prompt: 'Un distribuidor comienza a definir estrategia comercial, invertir significativamente en marketing y asumir riesgo de mercado. ¿Qué consecuencia puede tener?', options: ['Ninguna, porque sigue siendo distribuidor', 'Puede cambiar su caracterización económica', 'Obliga a aplicar CUP', 'Elimina la necesidad de FAR'], correctIndex: 1, feedback: 'La etiqueta puede permanecer, pero los hechos pueden modificar sustancialmente el perfil económico de la entidad.' },
  { lesson: 7, prompt: '¿Qué debe incluir una delimitación precisa bien redactada?', options: ['Sólo el nombre jurídico del contrato', 'Partes, naturaleza, FAR, términos relevantes y conclusión sobre la operación realizada', 'Únicamente el método seleccionado', 'Sólo información financiera'], correctIndex: 1, feedback: 'La delimitación debe conectar partes, hechos y condiciones relevantes en una conclusión breve y verificable.' },
  { lesson: 8, prompt: '¿Cuál es la secuencia analítica correcta?', options: ['Método → hechos → FAR', 'Comparables → contrato → método', 'Hechos → delimitación → caracterización → método', 'Resultado → método → operación'], correctIndex: 2, feedback: 'La metodología debe aplicarse a una operación previamente comprendida y delimitada.' },
];
