export const c2Assessments = [
  { lesson:1, prompt:'Si dos métodos pueden calcularse con los datos disponibles, ¿cuál debe elegirse?', options:['El más sencillo','El usado el año anterior','El que ofrezca mayor confiabilidad para los hechos','El que produzca el mejor resultado'], correctIndex:2, feedback:'Aplicable no significa necesariamente más apropiado; la selección exige comparar confiabilidad relativa.' },
  { lesson:2, prompt:'Una venta del mismo producto a relacionada e independiente bajo condiciones muy similares sugiere investigar primero:', options:['TNMM','CUP interno','Profit Split','RPM siempre'], correctIndex:1, feedback:'Un comparable interno potencialmente fuerte merece atención prioritaria, sujeto a verificar comparabilidad.' },
  { lesson:3, prompt:'Un método conceptualmente atractivo tiene datos de margen bruto inconsistentes, mientras otra alternativa cuenta con datos operativos confiables. ¿Qué procede?', options:['Mantener el primero por teoría','Comparar confiabilidad de ambas alternativas','Elegir siempre CUP','Ignorar calidad de datos'], correctIndex:1, feedback:'La calidad de la información forma parte de la confiabilidad de aplicación del método.' },
  { lesson:4, prompt:'¿Qué método suele ser especialmente sensible a diferencias materiales en las características de la operación?', options:['CUP','TNMM nunca','Todos son idénticamente sensibles','Ninguno'], correctIndex:0, feedback:'CUP requiere un alto grado de comparabilidad o ajustes suficientemente fiables.' },
  { lesson:5, prompt:'En un método unilateral, la parte analizada suele ser:', options:['La más grande','La matriz','La parte a la que el método puede aplicarse con mayor confiabilidad, frecuentemente la menos compleja','Siempre el vendedor'], correctIndex:2, feedback:'La selección de tested party es una conclusión funcional, no de tamaño o jerarquía corporativa.' },
  { lesson:6, prompt:'Si CUP y TNMM pueden aplicarse con igual grado de confiabilidad:', options:['TNMM debe prevalecer por ser común','La comparación directa de CUP puede ofrecer ventaja analítica','Debe usarse siempre Profit Split','Ambos deben descartarse'], correctIndex:1, feedback:'Cuando la confiabilidad es equivalente, una comparación más directa de la condición examinada puede ser analíticamente preferible.' },
  { lesson:7, prompt:'¿Cuál es una justificación insuficiente para seleccionar TNMM?', options:['Explicar FAR y datos','Comparar alternativas','Decir que es el método más usado','Explicar por qué los datos netos son más confiables'], correctIndex:2, feedback:'La frecuencia de uso no sustituye la justificación técnica basada en hechos y confiabilidad.' },
  { lesson:8, prompt:'Dos partes aportan intangibles únicos, personal especializado y controlan riesgos interdependientes sin comparables confiables separados. ¿Qué método merece consideración seria?', options:['RPM','Profit Split','CUP automáticamente','Cost Plus siempre'], correctIndex:1, feedback:'Contribuciones únicas y valiosas e integración relevante pueden hacer especialmente pertinente Profit Split.' },
];
