export const c3Course={id:'course-c3',curriculumVersion:'v1',level:'Consultant',code:'C3',title:'TNMM / MTUO en la práctica',description:'Convierte la lógica del TNMM/MTUO en una aplicación concreta: tested party, PLI, clasificación financiera, segmentación, cálculo e interpretación.',prerequisites:['Junior Foundations','C1','C2'],estimatedMinutes:175,lessonCount:8,passingScore:80,learningOutcomes:['Explicar qué mide TNMM y seleccionar una tested party razonable.','Distinguir y calcular Operating Margin, Mark-up on Costs, Berry Ratio y ROA.','Separar partidas operativas y no operativas y reconocer cuándo segmentar.','Interpretar un resultado frente a un rango sin sobreafirmar conclusiones.']};
export const c3Lessons=[
{id:'c3-lesson-1',sequence:1,title:'¿Qué mide TNMM?',estimatedMinutes:18,learningOutcomes:['Explicar la lógica económica de TNMM.','Distinguir margen neto de comparación directa de precios.']},
{id:'c3-lesson-2',sequence:2,title:'Tested Party',estimatedMinutes:18,learningOutcomes:['Seleccionar una parte analizada con base funcional.','Evitar seleccionar por tamaño, país o resultado.']},
{id:'c3-lesson-3',sequence:3,title:'Profit Level Indicators',estimatedMinutes:24,learningOutcomes:['Distinguir OM, mark-up, Berry Ratio y ROA.','Relacionar el denominador con el perfil funcional.']},
{id:'c3-lesson-4',sequence:4,title:'Operativo vs. no operativo',estimatedMinutes:20,learningOutcomes:['Clasificar partidas para calcular utilidad operativa.','Reconocer la importancia de consistencia contable.']},
{id:'c3-lesson-5',sequence:5,title:'Segmentación financiera',estimatedMinutes:22,learningOutcomes:['Identificar cuándo los estados totales distorsionan el análisis.','Explicar criterios razonables y documentables de segmentación.']},
{id:'c3-lesson-6',sequence:6,title:'Cálculos básicos',estimatedMinutes:28,learningOutcomes:['Calcular los cuatro PLI con datos simplificados.','Identificar errores de base o numerador.']},
{id:'c3-lesson-7',sequence:7,title:'Interpretación del resultado',estimatedMinutes:20,learningOutcomes:['Comparar el PLI con una referencia arm’s length.','Redactar una conclusión limitada al alcance del análisis.']},
{id:'c3-lesson-8',sequence:8,title:'Laboratorio C3',estimatedMinutes:25,learningOutcomes:['Aplicar PLI al dataset didáctico.','Resolver la Fase 8 de Manufacturas del Bajío.']}
].map(l=>({...l,courseId:'course-c3',curriculumVersion:'v1'}));