export const c3Assessments=[
{lesson:1,prompt:'¿Qué compara principalmente TNMM?',options:['Precio unitario','Margen neto relativo a una base apropiada','Tasa legal','Impuesto pagado'],correctIndex:1,feedback:'TNMM compara rentabilidad neta respecto de ventas, costos, activos u otra base apropiada.'},
{lesson:2,prompt:'¿Cuál es un criterio adecuado para elegir tested party?',options:['Menor utilidad','Mayor tamaño','Parte a la que el método puede aplicarse con mayor confiabilidad, frecuentemente la menos compleja','País de residencia'],correctIndex:2,feedback:'La selección es funcional y depende de confiabilidad y comparables, no de conveniencia.'},
{lesson:3,prompt:'¿Qué fórmula corresponde a Berry Ratio?',options:['Utilidad operativa/Ventas','Utilidad operativa/Costos','Utilidad bruta/Gastos operativos','Utilidad operativa/Activos'],correctIndex:2,feedback:'Berry Ratio relaciona utilidad bruta con gastos operativos y sólo es apropiado en circunstancias limitadas.'},
{lesson:4,prompt:'Bajo los supuestos didácticos de C3, ¿qué partidas se consideran no operativas?',options:['Ventas y costo de ventas','Intereses e impuestos','Gastos operativos','Utilidad bruta'],correctIndex:1,feedback:'En estos ejercicios intereses e impuestos se excluyen de utilidad operativa.'},
{lesson:5,prompt:'¿Cuándo puede ser necesaria una segmentación?',options:['Siempre','Cuando la entidad realiza actividades funcionalmente distintas y sólo una corresponde a la operación analizada','Sólo si hay pérdidas','Nunca en TNMM'],correctIndex:1,feedback:'Los estados totales pueden mezclar perfiles distintos y distorsionar el PLI.'},
{lesson:6,prompt:'Ventas 1,000 y utilidad operativa 50. ¿Operating Margin?',options:['2.5%','5.0%','10.0%','20.0%'],correctIndex:1,feedback:'50 / 1,000 = 5.0%.'},
{lesson:7,prompt:'Si el resultado cae dentro del rango comparable, ¿qué puede concluirse correctamente?',options:['Toda la entidad cumple arm’s length','La operación analizada, bajo los supuestos del análisis, se encuentra dentro de la referencia obtenida','No se necesita comparabilidad','El método es perfecto'],correctIndex:1,feedback:'La conclusión debe limitarse a operación, tested party, PLI, periodo y comparables analizados.'},
{lesson:8,prompt:'Manufacturas del Bajío: utilidad operativa 90 y costos operativos totales 1,110. ¿Mark-up on Costs?',options:['7.5%','8.11%','15.0%','12.0%'],correctIndex:1,feedback:'90 / 1,110 = 8.11%.'}
];