export const c4Course={id:'course-c4',curriculumVersion:'v1',level:'Consultant',code:'C4',title:'Análisis de Comparabilidad y Búsqueda de Comparables',description:'Estructura una búsqueda lógica, reproducible y documentable: proceso de nueve pasos, comparables internos y externos, criterios, filtros y decisiones Accept/Reject.',prerequisites:['Junior Foundations','C1','C2','C3'],estimatedMinutes:175,lessonCount:8,passingScore:80,learningOutcomes:['Describir y aplicar el proceso de nueve pasos de comparabilidad.','Diferenciar comparables internos y externos y diseñar criterios coherentes con FAR.','Distinguir filtros cuantitativos y cualitativos y evaluar descripciones de negocio.','Justificar Accept/Reject/Review y documentar una búsqueda reproducible.']};
export const c4Lessons=[
{id:'c4-lesson-1',sequence:1,title:'¿Qué es un análisis de comparabilidad?',estimatedMinutes:18,learningOutcomes:['Explicar por qué comparabilidad no significa identidad.','Conectar la búsqueda con la operación correctamente delimitada.']},
{id:'c4-lesson-2',sequence:2,title:'El proceso de nueve pasos',estimatedMinutes:24,learningOutcomes:['Ordenar el proceso de comparabilidad.','Reconocer que la secuencia puede ser iterativa.']},
{id:'c4-lesson-3',sequence:3,title:'Comparables internos y externos',estimatedMinutes:18,learningOutcomes:['Distinguir ambos tipos de comparable.','Explicar por qué un comparable interno sigue requiriendo análisis.']},
{id:'c4-lesson-4',sequence:4,title:'Diseño de criterios de búsqueda',estimatedMinutes:22,learningOutcomes:['Derivar criterios desde la operación y FAR.','Evitar criterios orientados al resultado deseado.']},
{id:'c4-lesson-5',sequence:5,title:'Filtros cuantitativos y cualitativos',estimatedMinutes:22,learningOutcomes:['Distinguir datos estructurados de revisión funcional.','Explicar por qué los códigos de industria no sustituyen el análisis.']},
{id:'c4-lesson-6',sequence:6,title:'Accept / Reject / Review',estimatedMinutes:24,learningOutcomes:['Justificar decisiones con evidencia concreta.','Reconocer cuándo la información es insuficiente.']},
{id:'c4-lesson-7',sequence:7,title:'Documentación de la búsqueda',estimatedMinutes:20,learningOutcomes:['Documentar un proceso reproducible.','Registrar filtros, resultados, razones y limitaciones.']},
{id:'c4-lesson-8',sequence:8,title:'Laboratorio Accept / Reject',estimatedMinutes:27,learningOutcomes:['Evaluar candidatos contra un perfil funcional.','Resolver la Fase 8 de Manufacturas del Bajío sin sesgo ex post.']}
].map(l=>({...l,courseId:'course-c4',curriculumVersion:'v1'}));