export const c4Assessments=[
{lesson:1,prompt:'¿Una empresa del mismo sector es automáticamente comparable?',options:['Sí, si comparte código de industria','No; deben evaluarse funciones, activos, riesgos y demás condiciones relevantes','Sí, si tiene un margen parecido','Sólo si está en el mismo país'],correctIndex:1,feedback:'La industria orienta la búsqueda, pero no sustituye el análisis de comparabilidad.'},
{lesson:2,prompt:'¿Qué debe revisarse antes de buscar comparables externos?',options:['El margen deseado','Comparables internos existentes','Sólo el código de industria','El cuartil esperado'],correctIndex:1,feedback:'El proceso de nueve pasos incluye revisar comparables internos antes de determinar fuentes externas.'},
{lesson:3,prompt:'¿Qué caracteriza a un comparable interno?',options:['Siempre pertenece al mismo grupo','Una parte de la operación controlada realiza una operación potencialmente comparable con un tercero independiente','Es una empresa de la misma industria','Sólo existe para CUP'],correctIndex:1,feedback:'Un comparable interno surge de una operación con un tercero independiente realizada por una de las partes.'},
{lesson:4,prompt:'¿Qué debe orientar los criterios de búsqueda?',options:['El resultado deseado','FAR y operación delimitada','El número mínimo de empresas','La costumbre de la firma'],correctIndex:1,feedback:'Los criterios deben derivarse de la economía de la operación, no del rango que se desea obtener.'},
{lesson:5,prompt:'Leer la descripción del negocio de un candidato corresponde principalmente a:',options:['Filtro cuantitativo','Revisión cualitativa','Ajuste de capital','Cálculo del PLI'],correctIndex:1,feedback:'La revisión cualitativa exige entender funciones, productos, segmentos, intangibles e integración.'},
{lesson:6,prompt:'Si la información disponible no permite distinguir distribución de manufactura propia, ¿qué decisión es defendible?',options:['Accept automático','Reject por margen','Review / información insuficiente','Accept si está en la misma industria'],correctIndex:2,feedback:'No debe forzarse Accept o Reject cuando la evidencia todavía no alcanza.'},
{lesson:7,prompt:'¿Qué debe documentarse para una búsqueda reproducible?',options:['Sólo comparables finales','Criterios, filtros, resultados por etapas, razones Accept/Reject y limitaciones','Sólo el rango','Sólo la fecha'],correctIndex:1,feedback:'La documentación debe permitir reconstruir razonablemente el proceso y sus decisiones.'},
{lesson:8,prompt:'¿Es válido rechazar un comparable únicamente porque su margen es muy alto?',options:['Sí','No','Sólo si mejora el rango','Sólo en TNMM'],correctIndex:1,feedback:'El resultado financiero no debe utilizarse como filtro ex post para manipular el rango.'}
];