export const c5Course={id:'course-c5',curriculumVersion:'v1',level:'Consultant',code:'C5',title:'Ajustes de Comparabilidad',description:'Comprende cuándo una diferencia amerita ajuste, qué objetivo económico persigue y cuándo ajustar puede reducir en lugar de aumentar la confiabilidad.',prerequisites:['Junior Foundations','C1','C2','C3','C4'],estimatedMinutes:180,lessonCount:8,passingScore:80,learningOutcomes:['Identificar diferencias potencialmente materiales y distinguir cuáles ameritan ajuste.','Explicar la lógica económica de capital de trabajo y activos operativos sin asumir una fórmula universal.','Reconocer ajustes vinculados a términos contractuales, geografía, volumen y funciones.','Evaluar si un ajuste es razonablemente fiable y justificar cuándo es preferible no ajustar.']};
export const c5Lessons=[
{id:'c5-lesson-1',sequence:1,title:'¿Para qué sirve un ajuste de comparabilidad?',estimatedMinutes:18,learningOutcomes:['Explicar el propósito económico de un ajuste.','Distinguir mejorar comparabilidad de manipular un resultado.']},
{id:'c5-lesson-2',sequence:2,title:'Materialidad de las diferencias',estimatedMinutes:20,learningOutcomes:['Aplicar las preguntas de existencia, materialidad y cuantificación.','Justificar cuándo una diferencia no requiere ajuste.']},
{id:'c5-lesson-3',sequence:3,title:'Capital de trabajo: lógica económica',estimatedMinutes:28,learningOutcomes:['Explicar CxC, CxP e inventarios desde su lógica financiera.','Reconocer variables metodológicas sin memorizar una fórmula universal.']},
{id:'c5-lesson-4',sequence:4,title:'Propiedad, planta y equipo (PP&E)',estimatedMinutes:22,learningOutcomes:['Relacionar intensidad de activos con rentabilidad esperada.','Evaluar límites y confiabilidad de un posible ajuste a PP&E.']},
{id:'c5-lesson-5',sequence:5,title:'Términos contractuales, volumen y mercado',estimatedMinutes:22,learningOutcomes:['Identificar diferencias contractuales, de volumen y geografía potencialmente ajustables.','Exigir evidencia del efecto económico antes de ajustar.']},
{id:'c5-lesson-6',sequence:6,title:'Diferencias funcionales',estimatedMinutes:20,learningOutcomes:['Reconocer diferencias que un ajuste no puede rescatar.','Priorizar mejores comparables frente a múltiples ajustes sobre malos comparables.']},
{id:'c5-lesson-7',sequence:7,title:'¿Cuándo no ajustar?',estimatedMinutes:20,learningOutcomes:['Identificar razones metodológicas para no ajustar.','Documentar una decisión de no ajuste.']},
{id:'c5-lesson-8',sequence:8,title:'Laboratorio de decisiones de ajuste',estimatedMinutes:30,learningOutcomes:['Resolver casos de CxC, PP&E, volumen y comparables inadecuados.','Completar la Fase 9 de Manufacturas del Bajío.']}
].map(l=>({...l,courseId:'course-c5',curriculumVersion:'v1'}));