export const c5Assessments=[
{lesson:1,prompt:'¿Cuál es el objetivo correcto de un ajuste de comparabilidad?',options:['Mover el resultado hacia la mediana','Reducir el efecto de una diferencia material cuando mejora la comparabilidad','Reducir impuestos','Aumentar el número de comparables'],correctIndex:1,feedback:'El ajuste es un instrumento para mejorar la confiabilidad de la comparación, no para dirigir el resultado.'},
{lesson:2,prompt:'Antes de ajustar, ¿qué debe evaluarse?',options:['Sólo si existe una diferencia','Existencia, materialidad y posibilidad de cuantificar razonablemente el efecto','Sólo el margen final','Si la firma siempre hace el ajuste'],correctIndex:1,feedback:'Una diferencia observable no basta: debe ser material y tratable de forma razonablemente fiable.'},
{lesson:3,prompt:'Una empresa con mayores cuentas por cobrar puede:',options:['Tener recursos inmovilizados por más tiempo','Eliminar su necesidad de financiamiento','No tener ventas','Tener automáticamente menor inventario'],correctIndex:0,feedback:'Conceder mayor crédito a clientes puede aumentar la necesidad de financiamiento.'},
{lesson:4,prompt:'¿Debe ajustarse PP&E siempre que existan diferencias?',options:['Sí','No; primero debe evaluarse relevancia funcional, datos y confiabilidad metodológica','Sólo en fabricantes','Sólo si aumenta el margen'],correctIndex:1,feedback:'La intensidad de activos puede ser relevante, pero un ajuste a PP&E no es mecánico.'},
{lesson:5,prompt:'Un ajuste por volumen es más defendible cuando:',options:['El volumen es distinto sin más evidencia','Existe evidencia confiable del efecto económico de la diferencia','El comparable tiene margen alto','La operación es relacionada'],correctIndex:1,feedback:'La diferencia debe ser económicamente relevante y su efecto suficientemente cuantificable.'},
{lesson:6,prompt:'Distribuidor rutinario vs. fabricante-distribuidor con I+D y marca propia. ¿Qué debe hacerse primero?',options:['Aplicar múltiples ajustes financieros','Revisar/rechazar la comparabilidad','Ajustar sólo inventarios','Ignorar las funciones'],correctIndex:1,feedback:'Los ajustes no deben utilizarse para rescatar comparables conceptualmente deficientes.'},
{lesson:7,prompt:'¿No ajustar puede ser una conclusión metodológicamente correcta?',options:['Sí','No'],correctIndex:0,feedback:'Puede ser correcto si la diferencia no es material, no es cuantificable, los datos son débiles o el ajuste no mejora confiabilidad.'},
{lesson:8,prompt:'Manufacturas del Bajío tiene inventarios y activos productivos superiores al set. ¿Qué procede?',options:['Aplicar una fórmula estándar automáticamente','Evaluar materialidad, datos, naturaleza de activos y metodología antes de decidir','Eliminar todos los comparables','Ajustar hasta alcanzar la mediana'],correctIndex:1,feedback:'La Fase 9 exige comprender la diferencia y la confiabilidad del ajuste antes de cuantificarlo.'}
];