export const c6Course={id:'course-c6',curriculumVersion:'v1',level:'Consultant',code:'C6',title:'El Rango de Plena Competencia',description:'Interpreta múltiples resultados comparables, rango completo, rango intercuartil, mediana y posición de la tested party sin confundir estadística con norma jurídica.',prerequisites:['Junior Foundations','C1','C2','C3','C4','C5'],estimatedMinutes:170,lessonCount:8,passingScore:80,learningOutcomes:['Explicar por qué pueden existir múltiples resultados independientes confiables.','Distinguir rango completo, Q1, Q3, rango intercuartil y mediana.','Interpretar la posición de la tested party frente a un rango dado.','Distinguir lógica estadística de consecuencia jurídica local y evitar cherry-picking.']};
export const c6Lessons=[
{id:'c6-lesson-1',sequence:1,title:'¿Por qué hablamos de un rango?',estimatedMinutes:18,learningOutcomes:['Explicar por qué no existe necesariamente un único resultado arm’s length.','Entender el rango como síntesis de observaciones previamente comparables.']},
{id:'c6-lesson-2',sequence:2,title:'Rango completo',estimatedMinutes:16,learningOutcomes:['Identificar mínimo y máximo.','Distinguir rango completo de una regla legal local.']},
{id:'c6-lesson-3',sequence:3,title:'Cuartiles y rango intercuartil',estimatedMinutes:24,learningOutcomes:['Definir Q1 y Q3.','Reconocer que las convenciones de cálculo pueden variar entre herramientas.']},
{id:'c6-lesson-4',sequence:4,title:'Mediana',estimatedMinutes:18,learningOutcomes:['Calcular mediana con número par e impar de observaciones.','Evitar tratar la mediana como precio correcto universal.']},
{id:'c6-lesson-5',sequence:5,title:'Resultado de la parte analizada',estimatedMinutes:20,learningOutcomes:['Determinar si el resultado cae dentro o fuera de un rango dado.','Separar conclusión económica de consecuencia jurídica.']},
{id:'c6-lesson-6',sequence:6,title:'Estadística vs. comparabilidad',estimatedMinutes:20,learningOutcomes:['Explicar por qué la estadística no repara comparables débiles.','Aplicar la secuencia correcta del análisis.']},
{id:'c6-lesson-7',sequence:7,title:'Outliers, extremos y disciplina analítica',estimatedMinutes:22,learningOutcomes:['Evitar eliminar observaciones sólo por su resultado.','Identificar cuándo existe fundamento independiente para exclusión.']},
{id:'c6-lesson-8',sequence:8,title:'De la estadística a la conclusión',estimatedMinutes:32,learningOutcomes:['Redactar una conclusión técnica de rango.','Resolver laboratorios y la Fase 10 de Manufacturas del Bajío.']}
].map(l=>({...l,courseId:'course-c6',curriculumVersion:'v1'}));