export const c7Course={id:'course-c7',curriculumVersion:'v1',level:'Consultant',code:'C7',title:'Documentación de Precios de Transferencia',description:'Comprende el propósito y la arquitectura conceptual de un Estudio de TP, Local File, Master File y CbC Report, sin confundirlos ni asumir plantillas universales.',prerequisites:['Junior Foundations','C1','C2','C3','C4','C5','C6'],estimatedMinutes:175,lessonCount:8,passingScore:80,learningOutcomes:['Explicar para qué sirve la documentación y qué debe dejar trazable.','Distinguir Estudio de TP, Local File, Master File y CbC Report por propósito, audiencia y nivel de detalle.','Reconocer que CbC Report es una herramienta de transparencia y risk assessment, no una prueba de plena competencia.','Detectar inconsistencias entre documentos y recordar que la normativa local gobierna la aplicación real.']};
export const c7Lessons=[
{id:'c7-lesson-1',sequence:1,title:'¿Para qué documentamos?',estimatedMinutes:18,learningOutcomes:['Explicar la función de trazabilidad documental.','Reconocer que una buena redacción no corrige un análisis débil.']},
{id:'c7-lesson-2',sequence:2,title:'Estudio de Precios de Transferencia',estimatedMinutes:22,learningOutcomes:['Describir su arquitectura conceptual general.','Evitar memorizar una plantilla como estándar universal.']},
{id:'c7-lesson-3',sequence:3,title:'Local File',estimatedMinutes:22,learningOutcomes:['Identificar su foco en la entidad local y operaciones materiales.','Distinguirlo de un EPT genérico.']},
{id:'c7-lesson-4',sequence:4,title:'Master File',estimatedMinutes:20,learningOutcomes:['Explicar su perspectiva global.','Reconocer su función de contexto sobre grupo, intangibles y financiamiento.']},
{id:'c7-lesson-5',sequence:5,title:'Country-by-Country Report / CbC Report',estimatedMinutes:22,learningOutcomes:['Explicar su naturaleza agregada por jurisdicción.','Distinguir risk assessment de análisis arm\'s length.']},
{id:'c7-lesson-6',sequence:6,title:'EPT vs. Local File',estimatedMinutes:20,learningOutcomes:['Explicar por qué no son sinónimos universales.','Formular la pregunta correcta sobre propósito y jurisdicción.']},
{id:'c7-lesson-7',sequence:7,title:'Master File vs. CbC Report',estimatedMinutes:20,learningOutcomes:['Diferenciar contexto global narrativo de métricas agregadas.','Explicar por qué uno no sustituye al otro.']},
{id:'c7-lesson-8',sequence:8,title:'Cómo se relacionan los cuatro documentos',estimatedMinutes:31,learningOutcomes:['Usar los cuatro niveles de zoom documental.','Resolver la Fase 11 de Manufacturas del Bajío e investigar inconsistencias.']}
].map(l=>({...l,courseId:'course-c7',curriculumVersion:'v1'}));