export const c7Assessments=[
{lesson:1,prompt:'¿Qué hace una buena documentación de Precios de Transferencia?',options:['Sustituye el análisis técnico','Deja trazabilidad del razonamiento y soporte','Evita revisar FAR','Define la legislación aplicable'],correctIndex:1,feedback:'La documentación conecta hechos, FAR, método, comparabilidad, resultados y conclusión; no sustituye un análisis débil.'},
{lesson:2,prompt:'¿Existe una plantilla universal de Estudio de TP?',options:['Sí','No'],correctIndex:1,feedback:'La Academy enseña arquitectura lógica; las estructuras y requisitos pueden variar entre firmas y jurisdicciones.'},
{lesson:3,prompt:'¿Cuál es el foco principal del Local File?',options:['El grupo global completo','La entidad local y sus operaciones materiales con relacionadas','Sólo las métricas por jurisdicción','Únicamente intangibles'],correctIndex:1,feedback:'El Local File conecta la entidad local con el análisis de sus operaciones materiales.'},
{lesson:4,prompt:'¿Qué documento ofrece una visión global del grupo multinacional?',options:['Local File','Master File','CbC Report exclusivamente','Factura'],correctIndex:1,feedback:'El Master File proporciona contexto narrativo de alto nivel sobre cómo opera el grupo.'},
{lesson:5,prompt:'¿Qué NO puede concluirse automáticamente de un CbC Report?',options:['Que existen métricas agregadas por jurisdicción','Que una jurisdicción tiene un problema de TP por tener alta utilidad y pocos empleados','Qué entidades constitutivas existen','Que puede servir para risk assessment'],correctIndex:1,feedback:'El CbC es una herramienta de transparencia y evaluación de riesgos, no una prueba arm\'s length por sí sola.'},
{lesson:6,prompt:'EPT y Local File son siempre exactamente lo mismo.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Pueden compartir mucho contenido, pero terminología y obligaciones varían según contexto y jurisdicción.'},
{lesson:7,prompt:'Master File y CbC Report responden exactamente la misma pregunta.',options:['Verdadero','Falso'],correctIndex:1,feedback:'El Master File explica cómo opera el grupo; el CbC muestra métricas agregadas por jurisdicción.'},
{lesson:8,prompt:'Si Master File y Local File describen funciones incompatibles de la misma entidad, ¿qué debe hacer el consultor?',options:['Ignorarlo','Investigar la inconsistencia antes de concluir','Elegir el documento más reciente','Copiar el texto del Master File'],correctIndex:1,feedback:'La consistencia documental exige compatibilidad de hechos y narrativa económica, no copiar el mismo texto.'}
];