export const j3Assessments = [
  { lesson: 1, prompt: '¿Qué describe mejor un análisis FAR?', options: ['Una lista de departamentos.', 'Una descripción de funciones, activos y riesgos económicamente relevantes vinculados con la operación.', 'Un inventario contable de activos.', 'Una selección anticipada del método.'], correctIndex: 1, feedback: 'FAR busca explicar la realidad económica de la operación mediante funciones, activos y riesgos relevantes.' },
  { lesson: 2, prompt: 'Dos entidades dicen realizar marketing. ¿Qué pregunta es más útil para FAR?', options: ['¿Usan el mismo logotipo?', '¿Quién toma decisiones, define presupuesto y puede modificar la campaña?', '¿Cuántos años tiene el grupo?', '¿Qué firma auditó los estados financieros?'], correctIndex: 1, feedback: 'La profundidad funcional depende de decisiones, recursos y consecuencias económicas, no de la etiqueta de la actividad.' },
  { lesson: 3, prompt: 'Una planta valiosa pertenece a una entidad, pero la operación analizada es un servicio administrativo prestado desde otra oficina. ¿La planta es automáticamente relevante?', options: ['Sí, por estar en el balance.', 'Sí, si su valor es material.', 'No; debe analizarse su relación con la operación específica.', 'No, porque los activos tangibles nunca importan.'], correctIndex: 2, feedback: 'La relevancia de un activo depende de su conexión económica con la operación analizada.' },
  { lesson: 4, prompt: 'El contrato dice que una distribuidora asume riesgo de inventario, pero la matriz decide niveles y absorbe pérdidas. ¿Qué conclusión es prudente?', options: ['La distribuidora controla el riesgo porque así lo dice el contrato.', 'Debe analizarse la divergencia entre contrato, decisiones y consecuencias económicas.', 'El riesgo no importa para FAR.', 'La matriz controla todos los riesgos del grupo por definición.'], correctIndex: 1, feedback: 'La asunción económica del riesgo requiere analizar conducta, control y capacidad financiera.' },
  { lesson: 5, prompt: '¿Por qué importa identificar a las personas que toman decisiones?', options: ['Porque toda decisión debe aparecer en el organigrama.', 'Porque las empresas ejercen control y toman decisiones a través de personas.', 'Porque el número de empleados determina el método.', 'Porque sólo los directores pueden asumir riesgos.'], correctIndex: 1, feedback: 'Seguir la capacidad real de decisión ayuda a comprender quién controla funciones y riesgos relevantes.' },
  { lesson: 6, prompt: '¿Cuál es una señal de mayor complejidad funcional en un fabricante?', options: ['Opera maquinaria siguiendo especificaciones recibidas.', 'Realiza control de calidad estándar.', 'Desarrolla tecnología, decide inversiones y gestiona proveedores críticos.', 'Compra insumos de proveedores aprobados.'], correctIndex: 2, feedback: 'Desarrollo tecnológico, decisiones de inversión y control de riesgos relevantes apuntan a mayor complejidad funcional.' },
  { lesson: 7, prompt: 'En Transfer Pricing, decir que una entidad es “rutinaria” significa:', options: ['Que su trabajo carece de valor.', 'Que no utiliza activos.', 'Que sus funciones, activos y riesgos son relativamente menos complejos respecto de la operación analizada.', 'Que siempre debe obtener el mismo margen.'], correctIndex: 2, feedback: 'Rutinario es una caracterización relativa; no significa irrelevante ni determina automáticamente una remuneración.' },
  { lesson: 8, prompt: '¿Cuál es la secuencia correcta?', options: ['Etiqueta → método → hechos.', 'Hechos → FAR → relación entre las partes → caracterización preliminar.', 'Método → comparables → FAR.', 'Sector → margen → caracterización.'], correctIndex: 1, feedback: 'La caracterización debe construirse desde los hechos y el FAR, no utilizarse como una etiqueta predeterminada para escoger método.' },
];
