export const j4Assessments = [
  { lesson: 1, prompt: '¿Cuál es la mejor razón para seleccionar un método de Precios de Transferencia?', options: ['Porque fue usado el año anterior.', 'Porque responde de forma confiable a la operación analizada considerando FAR e información disponible.', 'Porque es el más común en la firma.', 'Porque produce el resultado fiscal más conveniente.'], correctIndex: 1, feedback: 'El método debe seleccionarse por su adecuación a la operación y la confiabilidad de la comparación, no por costumbre.' },
  { lesson: 2, prompt: '¿Qué compara directamente el método CUP?', options: ['Un margen neto.', 'Una utilidad combinada.', 'Un precio o condición de una operación controlada con una operación independiente comparable.', 'Un mark-up sobre costos.'], correctIndex: 2, feedback: 'CUP compara directamente precios o condiciones, siempre sujeto a suficiente comparabilidad.' },
  { lesson: 3, prompt: '¿Qué dato económico es central en RPM?', options: ['Margen bruto de reventa.', 'Margen neto sobre ventas.', 'Precio por unidad exclusivamente.', 'Utilidad residual combinada.'], correctIndex: 0, feedback: 'RPM parte de la reventa a independientes y analiza un margen bruto apropiado para la actividad de distribución.' },
  { lesson: 4, prompt: '¿Qué describe mejor la lógica del Cost Plus?', options: ['Precio de reventa menos margen bruto.', 'Costos relevantes más un mark-up apropiado.', 'Margen neto sobre activos.', 'División automática de utilidad 50/50.'], correctIndex: 1, feedback: 'Cost Plus parte de una base de costos relevante y añade un mark-up de plena competencia.' },
  { lesson: 5, prompt: '¿Qué analiza TNMM?', options: ['Un indicador de rentabilidad neta relativo a una base apropiada.', 'Sólo precios directos de productos idénticos.', 'Exclusivamente márgenes brutos.', 'La utilidad combinada de todas las entidades del grupo.'], correctIndex: 0, feedback: 'TNMM analiza un margen neto en relación con una base apropiada; tested party y PLI se desarrollarán después.' },
  { lesson: 6, prompt: '¿Qué situación puede hacer conceptualmente relevante un Profit Split?', options: ['Una parte rutinaria y un CUP interno perfecto.', 'Dos partes con contribuciones únicas y valiosas o actividades altamente integradas.', 'Una distribución simple con márgenes brutos confiables.', 'Cualquier operación entre relacionadas.'], correctIndex: 1, feedback: 'Profit Split puede ser relevante cuando múltiples partes realizan contribuciones que no pueden evaluarse confiablemente de forma separada.' },
  { lesson: 7, prompt: '¿Cuál clasificación es correcta?', options: ['CUP, RPM y Cost Plus son métodos tradicionales; TNMM y Profit Split son métodos basados en resultados.', 'Todos son métodos de precio directo.', 'TNMM es tradicional y CUP es de resultados.', 'Profit Split es un tipo de CUP.'], correctIndex: 0, feedback: 'La clasificación ayuda a entender qué compara cada método, pero no establece una jerarquía automática.' },
  { lesson: 8, prompt: 'Un archivo del año pasado aplicó TNMM. ¿Qué debería hacer primero el consultor este año?', options: ['Copiar TNMM para mantener consistencia.', 'Confirmar operación, FAR, disponibilidad de información y confiabilidad antes de seleccionar método.', 'Usar Profit Split porque es más sofisticado.', 'Buscar comparables antes de entender la operación.'], correctIndex: 1, feedback: 'La selección debe revalidarse desde los hechos. La costumbre no sustituye el análisis del método más apropiado.' },
];
