export const j5Assessments = [
  { lesson: 1, prompt: 'Dos empresas pertenecen a la misma industria. ¿Eso basta para considerarlas comparables?', options: ['Sí, si tienen el mismo código de industria.', 'Sí, si están en el mismo país.', 'No; deben evaluarse las diferencias que puedan afectar materialmente la condición analizada.', 'Sí, si ambas son rentables.'], correctIndex: 2, feedback: 'Comparabilidad no exige identidad absoluta, pero sí evaluar si las diferencias son materiales o pueden ajustarse confiablemente.' },
  { lesson: 2, prompt: '¿Qué describe mejor un comparable interno?', options: ['Una empresa del mismo grupo.', 'Una operación similar entre una de las partes de la operación controlada y un independiente.', 'Cualquier empresa de la misma industria.', 'Una operación controlada de otro año.'], correctIndex: 1, feedback: 'El comparable interno surge de una operación con un independiente realizada por una de las partes de la operación controlada.' },
  { lesson: 3, prompt: '¿Cuál es un riesgo típico al seleccionar comparables externos?', options: ['Revisar demasiado las funciones.', 'Asumir comparabilidad sólo por compartir un código de industria.', 'Tener información pública disponible.', 'Documentar las razones de aceptación.'], correctIndex: 1, feedback: 'El código de industria es sólo un punto de partida; descripción de negocio, funciones y datos disponibles siguen siendo esenciales.' },
  { lesson: 4, prompt: 'Dos préstamos tienen el mismo monto. ¿Son automáticamente comparables?', options: ['Sí, el monto determina la comparabilidad.', 'Sí, si fueron otorgados el mismo año.', 'No; plazo, moneda, garantía, crédito y otras características pueden ser determinantes.', 'Sólo si ambos son intragrupo.'], correctIndex: 2, feedback: 'Las características de la operación pueden modificar materialmente el valor aun cuando el monto sea idéntico.' },
  { lesson: 5, prompt: '¿Por qué FAR es central para la comparabilidad?', options: ['Porque sustituye el análisis contractual.', 'Porque ayuda a entender diferencias económicas en funciones, activos y riesgos que pueden justificar remuneraciones distintas.', 'Porque elimina la necesidad de información independiente.', 'Porque determina automáticamente el método.'], correctIndex: 1, feedback: 'Dos negocios comercialmente parecidos pueden tener perfiles económicos distintos si sus funciones, activos y riesgos difieren.' },
  { lesson: 6, prompt: 'Dos distribuidores compran el mismo producto, pero uno tiene volumen mínimo alto y no puede devolver inventario. ¿Qué exige atención?', options: ['Sólo la marca del producto.', 'Términos contractuales y sus efectos económicos.', 'Sólo el país.', 'Nada, porque el producto es idéntico.'], correctIndex: 1, feedback: 'Volumen mínimo, devoluciones, pago, garantía, territorio y otros términos pueden afectar precio, margen y riesgo.' },
  { lesson: 7, prompt: '¿Cuál puede ser una circunstancia económica relevante?', options: ['El color del logotipo.', 'El tamaño del despacho asesor.', 'Competencia, geografía, regulación y condiciones de oferta y demanda.', 'El formato del informe.'], correctIndex: 2, feedback: 'Las condiciones del mercado pueden hacer que operaciones aparentemente similares no sean directamente comparables.' },
  { lesson: 8, prompt: 'Una empresa afirma que sus pérdidas se deben a una estrategia de penetración. ¿Qué debe hacer el analista?', options: ['Aceptar siempre la explicación.', 'Ignorar toda estrategia empresarial.', 'Evaluar si la estrategia es coherente con los hechos, está documentada y tiene sustancia económica.', 'Concluir automáticamente que no es comparable.'], correctIndex: 2, feedback: 'Las estrategias pueden afectar resultados, pero una afirmación sin sustancia ni evidencia no basta.' },
  { lesson: 9, prompt: '¿Cuál es el objetivo de un ajuste de comparabilidad?', options: ['Eliminar cualquier diferencia aunque sea irrelevante.', 'Aumentar artificialmente la muestra.', 'Mejorar la confiabilidad frente a una diferencia material cuando el ajuste puede realizarse razonablemente.', 'Garantizar que todas las empresas sean aceptadas.'], correctIndex: 2, feedback: 'Un ajuste sólo tiene sentido si mejora la confiabilidad; un ajuste sustentado en supuestos débiles puede introducir más error.' },
];
