export const s2Course={id:'course-s2',curriculumVersion:'v1',level:'Senior Knowledge',code:'S2',title:'Advanced Method Selection',description:'Selecciona el método más apropiado conectando FAR con la calidad de la información financiera disponible y comparando explícitamente la confiabilidad relativa entre alternativas plausibles.',prerequisites:['S1 recomendado'],estimatedMinutes:220,lessonCount:8,passingScore:80,learningOutcomes:['Conectar FAR con selección metodológica avanzada.','Evaluar calidad y segmentación de la información financiera.','Comparar métodos plausibles por confiabilidad relativa.','Seleccionar tested party y PLI cuando corresponda.','Documentar por qué una alternativa plausible es descartada.']};
export const s2Lessons=[
{id:'s2-1',courseId:'course-s2',curriculumVersion:'v1',sequence:1,title:'El método no se selecciona en abstracto',estimatedMinutes:25,learningOutcomes:['Distinguir encaje económico de aplicabilidad confiable.']},
{id:'s2-2',courseId:'course-s2',curriculumVersion:'v1',sequence:2,title:'FAR como primer filtro',estimatedMinutes:25,learningOutcomes:['Usar FAR para filtrar métodos incompatibles.']},
{id:'s2-3',courseId:'course-s2',curriculumVersion:'v1',sequence:3,title:'Información financiera disponible',estimatedMinutes:27,learningOutcomes:['Evaluar segmentación, clasificación y calidad de datos.']},
{id:'s2-4',courseId:'course-s2',curriculumVersion:'v1',sequence:4,title:'Métodos plausibles y confiabilidad relativa',estimatedMinutes:27,learningOutcomes:['Comparar alternativas con una matriz de confiabilidad.']},
{id:'s2-5',courseId:'course-s2',curriculumVersion:'v1',sequence:5,title:'Ventajas y desventajas: ejemplos',estimatedMinutes:28,learningOutcomes:['Reconocer ventajas y limitaciones específicas de CUP, RPM, Cost Plus, TNMM y Profit Split.']},
{id:'s2-6',courseId:'course-s2',curriculumVersion:'v1',sequence:6,title:'Tested party, PLI y segmentación',estimatedMinutes:27,learningOutcomes:['Validar tested party, PLI, denominador y segmentación.']},
{id:'s2-7',courseId:'course-s2',curriculumVersion:'v1',sequence:7,title:'Documentar por qué se descarta',estimatedMinutes:25,learningOutcomes:['Documentar explícitamente ventajas, limitaciones y descarte.']},
{id:'s2-8',courseId:'course-s2',curriculumVersion:'v1',sequence:8,title:'Casos de métodos plausibles',estimatedMinutes:36,learningOutcomes:['Resolver casos con dos métodos inicialmente plausibles.']}
];