export const s2Assessments=[
{lesson:1,prompt:'¿Qué dos preguntas deben resolverse al seleccionar método?',options:['Qué método se usa normalmente y cuál es más rápido','Qué método representa mejor la operación y cuál puede aplicarse con mayor confiabilidad','Qué método produce mejor resultado y cuál usa la firma','Qué método usó el año anterior y cuál pide el cliente'],correctIndex:1,feedback:'La selección Senior combina encaje económico con aplicabilidad confiable.'},
{lesson:2,prompt:'¿Qué debe revisarse antes de mirar números?',options:['FAR y caracterización','La mediana','El resultado deseado','Sólo la industria'],correctIndex:0,feedback:'FAR es el primer filtro metodológico.'},
{lesson:3,prompt:'Un dato disponible es automáticamente útil.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Disponibilidad no equivale a calidad; importa segmentación, clasificación y consistencia.'},
{lesson:4,prompt:'Si dos métodos son plausibles, ¿qué sigue?',options:['Elegir el más simple','Comparar confiabilidad relativa bajo los hechos','Promediar ambos','Usar el del año anterior'],correctIndex:1,feedback:'La decisión debe ser específica a los hechos y la calidad de datos.'},
{lesson:5,prompt:'¿Qué método puede perder confiabilidad por clasificación entre costo de ventas y gastos operativos?',options:['RPM','CUP','Profit Split','Todos por igual'],correctIndex:0,feedback:'RPM es especialmente sensible al margen bruto y su clasificación contable.'},
{lesson:6,prompt:'Elegir TNMM termina la selección metodológica.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Aún deben validarse tested party, PLI, segmentación, denominador y partidas operativas.'},
{lesson:7,prompt:'Una selección Senior debe documentar:',options:['Sólo el método elegido','Método elegido y por qué se descartan alternativas plausibles','Sólo el resultado','Sólo la tested party'],correctIndex:1,feedback:'Hacer visible el descarte evita una conclusión aparente de conveniencia.'},
{lesson:8,prompt:'En Manufacturas del Bajío, ¿por qué TNMM gana provisionalmente sobre Cost Plus?',options:['Porque TNMM siempre es superior','Porque los datos operativos sobre costos totales son más consistentes y la clasificación de costos externos limita Cost Plus','Porque no hay maquinaria','Porque Cost Plus no aplica a manufactura'],correctIndex:1,feedback:'Cost Plus sigue siendo plausible, pero pierde confiabilidad relativa por calidad de comparables.'}
];