export const s3Course={id:'course-s3',curriculumVersion:'v1',level:'Senior Knowledge',code:'S3',title:'Advanced Comparability',description:'Evalúa comparables imperfectos, pérdidas, información multianual y ajustes para decidir cuándo una diferencia es tolerable, ajustable o erosiona materialmente la confiabilidad.',prerequisites:['S2 recomendado'],estimatedMinutes:225,lessonCount:8,passingScore:80,learningOutcomes:['Distinguir imperfección de falta de comparabilidad.','Evaluar materialidad acumulada de diferencias.','Analizar pérdidas sin filtros mecánicos.','Usar información multianual para interpretar ciclos y tendencias.','Cuestionar ajustes que reducen confiabilidad.','Documentar criterios de rechazo y rediseño del set.']};
export const s3Lessons=[
{id:'s3-1',courseId:'course-s3',curriculumVersion:'v1',sequence:1,title:'Comparable perfecto vs. suficientemente fiable',estimatedMinutes:25,learningOutcomes:['Evaluar si una diferencia material impide una comparación fiable.']},
{id:'s3-2',courseId:'course-s3',curriculumVersion:'v1',sequence:2,title:'Materialidad acumulada',estimatedMinutes:26,learningOutcomes:['Analizar diferencias individualmente y en conjunto.']},
{id:'s3-3',courseId:'course-s3',curriculumVersion:'v1',sequence:3,title:'Pérdidas: señal, no prueba automática',estimatedMinutes:28,learningOutcomes:['Distinguir pérdidas aisladas de pérdidas recurrentes.']},
{id:'s3-4',courseId:'course-s3',curriculumVersion:'v1',sequence:4,title:'Pérdidas de tested party vs. comparables',estimatedMinutes:30,learningOutcomes:['Separar el análisis de pérdidas de la tested party y de comparables.']},
{id:'s3-5',courseId:'course-s3',curriculumVersion:'v1',sequence:5,title:'Información multianual',estimatedMinutes:27,learningOutcomes:['Usar múltiples años para comprender contexto económico, no para ocultar resultados.']},
{id:'s3-6',courseId:'course-s3',curriculumVersion:'v1',sequence:6,title:'Ajustes avanzados y pérdida de confiabilidad',estimatedMinutes:30,learningOutcomes:['Determinar cuándo un ajuste mejora o debilita la comparación.']},
{id:'s3-7',courseId:'course-s3',curriculumVersion:'v1',sequence:7,title:'Criterios de rechazo',estimatedMinutes:27,learningOutcomes:['Sustentar ACCEPT, REVIEW o REJECT con razones económicas y calidad de datos.']},
{id:'s3-8',courseId:'course-s3',curriculumVersion:'v1',sequence:8,title:'Cuándo el set deja de ser confiable',estimatedMinutes:32,learningOutcomes:['Detectar debilidades sistémicas que obligan a rediseñar búsqueda, tested party, PLI o método.']}
];