export const s3Assessments=[
{lesson:1,prompt:'La existencia de diferencias invalida automáticamente una comparable.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Una comparable imperfecta puede seguir siendo suficientemente fiable si las diferencias no son materiales o pueden ajustarse razonablemente.'},
{lesson:2,prompt:'Varias diferencias pequeñas deben evaluarse:',options:['Sólo individualmente','Individualmente y también en conjunto','Sólo por margen','Sólo por industria'],correctIndex:1,feedback:'La acumulación de diferencias puede erosionar confiabilidad aunque cada diferencia aislada parezca menor.'},
{lesson:3,prompt:'Una pérdida aislada significa automáticamente falta de plena competencia.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Partes independientes pueden incurrir en pérdidas por razones comerciales normales.'},
{lesson:4,prompt:'Pérdidas persistentes de una tested party rutinaria deben llevar a:',options:['Revisar FAR, riesgos, segmentación y caracterización','Ajustar automáticamente a la mediana','Ignorar el contrato','Eliminar años negativos'],correctIndex:0,feedback:'Las pérdidas recurrentes intensifican el escrutinio y pueden cuestionar la caracterización.'},
{lesson:5,prompt:'¿Para qué sirve principalmente la información multianual?',options:['Para ocultar pérdidas','Para comprender ciclos, tendencias y circunstancias extraordinarias','Para eliminar años negativos','Para sustituir FAR'],correctIndex:1,feedback:'Los múltiples años aportan contexto económico; no son una técnica para suavizar resultados.'},
{lesson:6,prompt:'Un ajuste de comparabilidad siempre mejora la confiabilidad.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Ajustes grandes, sensibles a supuestos o basados en datos débiles pueden reducirla.'},
{lesson:7,prompt:'¿Cuál NO es una razón válida de rechazo?',options:['Funciones materialmente distintas','Intangibles propios relevantes','El margen reduce el rango','Información financiera no segmentable'],correctIndex:2,feedback:'Aceptar o rechazar por conveniencia del margen es un criterio inválido.'},
{lesson:8,prompt:'Si el set completo exige ajustes materiales generalizados, puede ser necesario:',options:['Forzar los ajustes','Rediseñar búsqueda, tested party, PLI o incluso método','Eliminar sólo pérdidas','Usar promedio multianual'],correctIndex:1,feedback:'La comparabilidad puede obligar a regresar a decisiones anteriores del análisis.'}
];