export const s4Course={id:'course-s4',curriculumVersion:'v1',level:'Senior Knowledge',code:'S4',title:'Integrated Transfer Pricing Analysis',description:'Integra negocio, delimitación, FAR, método, tested party, PLI, comparabilidad, ajustes, rango y conclusión en una sola historia económica coherente.',prerequisites:['S1–S3'],estimatedMinutes:240,lessonCount:8,passingScore:80,learningOutcomes:['Reconstruir la lógica económica de una operación desde un expediente completo.','Distinguir hechos, inferencias, afirmaciones no soportadas e información faltante.','Integrar FAR, delimitación y caracterización.','Conectar FAR y calidad de datos con método, tested party y PLI.','Evaluar comparables, ajustes, pérdidas y rango sin cherry-picking.','Redactar conclusiones proporcionales a la evidencia y reabrir etapas cuando existan inconsistencias.']};
export const s4Lessons=[
{id:'s4-1',courseId:'course-s4',curriculumVersion:'v1',sequence:1,title:'Del negocio a la operación',estimatedMinutes:25,learningOutcomes:['Comprender primero cómo gana dinero el negocio y por qué existe la operación.']},
{id:'s4-2',courseId:'course-s4',curriculumVersion:'v1',sequence:2,title:'Del expediente a los hechos',estimatedMinutes:27,learningOutcomes:['Clasificar evidencia por nivel de soporte.']},
{id:'s4-3',courseId:'course-s4',curriculumVersion:'v1',sequence:3,title:'FAR y delimitación integrados',estimatedMinutes:30,learningOutcomes:['Construir FAR y delimitación como una sola cadena lógica.']},
{id:'s4-4',courseId:'course-s4',curriculumVersion:'v1',sequence:4,title:'Método, información financiera y confiabilidad',estimatedMinutes:30,learningOutcomes:['Comparar métodos por confiabilidad relativa y calidad de datos.']},
{id:'s4-5',courseId:'course-s4',curriculumVersion:'v1',sequence:5,title:'Tested party, PLI y segmentación',estimatedMinutes:28,learningOutcomes:['Justificar tested party, PLI y segmentación.']},
{id:'s4-6',courseId:'course-s4',curriculumVersion:'v1',sequence:6,title:'Comparabilidad, ajustes y pérdidas',estimatedMinutes:32,learningOutcomes:['Evaluar comparables, pérdidas y ajustes con criterio Senior.']},
{id:'s4-7',courseId:'course-s4',curriculumVersion:'v1',sequence:7,title:'Rango e interpretación',estimatedMinutes:28,learningOutcomes:['Interpretar rango sin usarlo para corregir un análisis defectuoso.']},
{id:'s4-8',courseId:'course-s4',curriculumVersion:'v1',sequence:8,title:'Conclusión y coherencia narrativa',estimatedMinutes:40,learningOutcomes:['Construir una conclusión integrada y reconocer cuándo reabrir etapas anteriores.']}
];