export const s4Assessments=[
{lesson:1,prompt:'¿Dónde debe comenzar un análisis integrado?',options:['En el rango','En el negocio y la operación','En la mediana','En el PLI'],correctIndex:1,feedback:'Primero debe comprenderse cómo gana dinero el negocio y por qué existe la operación.'},
{lesson:2,prompt:'Una conclusión Senior debe distinguir:',options:['Hechos, inferencias, afirmaciones no soportadas e información faltante','Sólo contratos y estados financieros','Método y rango','Sólo hechos'],correctIndex:0,feedback:'El expediente debe clasificarse por nivel de soporte.'},
{lesson:3,prompt:'La caracterización debe:',options:['Definirse antes del FAR','Derivarse del FAR y conducta real','Copiarse del contrato','Seguir el año anterior'],correctIndex:1,feedback:'La caracterización es consecuencia del análisis funcional y delimitación.'},
{lesson:4,prompt:'¿Cuál es la secuencia correcta?',options:['Método→FAR→rango','FAR→datos→métodos plausibles→confiabilidad relativa','Rango→PLI→FAR','Benchmark→contrato→FAR'],correctIndex:1,feedback:'S4 integra FAR, calidad de datos y selección metodológica.'},
{lesson:5,prompt:'La tested party se selecciona por:',options:['Ser local','Ser la menos compleja y permitir aplicación confiable','Tener menor margen','Tener más activos'],correctIndex:1,feedback:'Debe conectarse con FAR y aplicabilidad confiable.'},
{lesson:6,prompt:'Una pérdida aislada:',options:['Prueba no arm’s length','Debe investigarse en contexto','Obliga a excluir','Elimina TNMM'],correctIndex:1,feedback:'Una pérdida aislada es una señal de análisis, no una prueba automática.'},
{lesson:7,prompt:'El rango:',options:['Corrige un set débil','Organiza resultados previamente confiables','Sustituye comparabilidad','Valida cualquier FAR'],correctIndex:1,feedback:'El rango no rescata un análisis defectuoso.'},
{lesson:8,prompt:'Si TNMM queda dentro de rango pero FAR contradice la caracterización:',options:['Se cierra el análisis','Se reabre FAR, tested party y método','Se ajusta a la mediana','Se ignora FAR'],correctIndex:1,feedback:'Una inconsistencia relevante obliga a reabrir etapas previas.'}
];