export const s5Course={id:'course-s5',curriculumVersion:'v1',level:'Senior Knowledge',code:'S5',title:'Case Law & Transfer Pricing Reasoning',description:'Aprende a leer jurisprudencia de precios de transferencia como laboratorio de razonamiento: hechos, controversia, posiciones, evidencia, reasoning, decisión, valor persuasivo y límites.',prerequisites:['S1–S4'],estimatedMinutes:230,lessonCount:8,passingScore:80,learningOutcomes:['Separar hechos, argumentos, razonamiento y decisión.','Formular con precisión la controversia técnica de un caso.','Reconstruir la mejor versión de las posiciones del contribuyente y la autoridad.','Identificar el puente entre evidencia, razonamiento y holding.','Extraer principios condicionados sin convertir precedentes en reglas universales.','Comparar precedentes por hechos, FAR, operación, método, jurisdicción y procedimiento.','Redactar fichas jurisprudenciales breves, rigurosas y trazables a fuente primaria.']};
export const s5Lessons=[
{id:'s5-1',courseId:'course-s5',curriculumVersion:'v1',sequence:1,title:'Leer un caso no es leer el resultado',estimatedMinutes:25,learningOutcomes:['Reconstruir un caso más allá de quién ganó.']},
{id:'s5-2',courseId:'course-s5',curriculumVersion:'v1',sequence:2,title:'Hechos, argumentos y conclusiones',estimatedMinutes:25,learningOutcomes:['Distinguir hechos probados de posiciones y conclusiones.']},
{id:'s5-3',courseId:'course-s5',curriculumVersion:'v1',sequence:3,title:'Formular la controversia técnica',estimatedMinutes:25,learningOutcomes:['Reducir el expediente a una pregunta técnica precisa.']},
{id:'s5-4',courseId:'course-s5',curriculumVersion:'v1',sequence:4,title:'Posiciones de las partes',estimatedMinutes:25,learningOutcomes:['Exponer con rigor los argumentos competidores y su evidencia.']},
{id:'s5-5',courseId:'course-s5',curriculumVersion:'v1',sequence:5,title:'Razonamiento del tribunal',estimatedMinutes:30,learningOutcomes:['Identificar qué evidencia y supuestos sostienen el razonamiento central.']},
{id:'s5-6',courseId:'course-s5',curriculumVersion:'v1',sequence:6,title:'Qué se puede transferir a otro caso',estimatedMinutes:28,learningOutcomes:['Convertir una lección jurisprudencial en un principio condicionado por hechos.']},
{id:'s5-7',courseId:'course-s5',curriculumVersion:'v1',sequence:7,title:'Cuando dos casos parecen iguales y no lo son',estimatedMinutes:30,learningOutcomes:['Distinguir precedentes aparentemente similares mediante comparabilidad jurisprudencial.']},
{id:'s5-8',courseId:'course-s5',curriculumVersion:'v1',sequence:8,title:'Plantilla de ficha jurisprudencial',estimatedMinutes:42,learningOutcomes:['Construir una ficha con fuente primaria, estado procesal, razonamiento, lección y límites.']}
];