export const s6Course={id:'course-s6',curriculumVersion:'v1',level:'Senior Knowledge',code:'S6',title:'Challenging a Transfer Pricing Position',description:'Entrena la revisión crítica de una posición de precios de transferencia ya construida para identificar debilidades menores, problemas de evidencia y fallas estructurales antes de auditoría o controversia.',prerequisites:['S1–S5'],estimatedMinutes:235,lessonCount:8,passingScore:80,learningOutcomes:['Reconstruir una posición desde hechos y no desde el rango.','Detectar fallas en FAR, delimitación, método, tested party, PLI y segmentación.','Identificar cherry-picking, pérdidas mal analizadas y ajustes débiles.','Distinguir problemas menores, moderados y críticos.','Priorizar hallazgos y proponer remediación proporcional.']};
export const s6Lessons=[
{id:'s6-1',courseId:'course-s6',curriculumVersion:'v1',sequence:1,title:'Cambiar de rol: de construir a desafiar',estimatedMinutes:25,learningOutcomes:['Reconstruir la lógica desde cero antes de aceptar una conclusión.']},
{id:'s6-2',courseId:'course-s6',curriculumVersion:'v1',sequence:2,title:'Fallas en FAR y delimitación',estimatedMinutes:28,learningOutcomes:['Clasificar contradicciones FAR/delimitación por materialidad.']},
{id:'s6-3',courseId:'course-s6',curriculumVersion:'v1',sequence:3,title:'Fallas en selección del método',estimatedMinutes:28,learningOutcomes:['Desafiar método, tested party y alternativas plausibles.']},
{id:'s6-4',courseId:'course-s6',curriculumVersion:'v1',sequence:4,title:'Información financiera, segmentación y PLI',estimatedMinutes:28,learningOutcomes:['Rastrear el PLI hasta información financiera reconciliada y segmentada.']},
{id:'s6-5',courseId:'course-s6',curriculumVersion:'v1',sequence:5,title:'Comparables, pérdidas y cherry-picking',estimatedMinutes:28,learningOutcomes:['Detectar filtros sesgados, pérdidas mal tratadas y cherry-picking.']},
{id:'s6-6',courseId:'course-s6',curriculumVersion:'v1',sequence:6,title:'Ajustes de comparabilidad bajo escrutinio',estimatedMinutes:28,learningOutcomes:['Evaluar si un ajuste realmente mejora la comparabilidad.']},
{id:'s6-7',courseId:'course-s6',curriculumVersion:'v1',sequence:7,title:'La narrativa puede fallar aunque el número “dé”',estimatedMinutes:25,learningOutcomes:['Revisar consistencia vertical y horizontal aunque el resultado esté dentro de rango.']},
{id:'s6-8',courseId:'course-s6',curriculumVersion:'v1',sequence:8,title:'Triage de hallazgos y remediación',estimatedMinutes:45,learningOutcomes:['Priorizar hallazgos y definir acciones de remediación.']}
];