export const s6Assessments=[
{lesson:1,prompt:'¿Dónde debe comenzar una revisión Senior?',options:['En el rango','En los hechos y la operación','En la mediana','En el estilo del reporte'],correctIndex:1,feedback:'La revisión reconstruye la lógica desde los hechos antes de aceptar la conclusión.'},
{lesson:2,prompt:'Contrato y conducta divergen en la asignación de riesgos. Esto puede ser:',options:['Irrelevante si el resultado está en rango','Un hallazgo crítico','Sólo un problema editorial','Un problema estadístico'],correctIndex:1,feedback:'Una contradicción material entre FAR declarado y conducta puede invalidar caracterización y conclusión.'},
{lesson:3,prompt:'Otro método sea imaginable significa automáticamente que el método elegido es débil.',options:['Verdadero','Falso'],correctIndex:1,feedback:'La debilidad surge cuando no se razona la elección frente a alternativas plausibles y a la calidad de los datos.'},
{lesson:4,prompt:'Una segmentación que mezcla operaciones con terceros puede:',options:['Ser irrelevante','Contaminar el PLI de la operación controlada','Mejorar siempre el análisis','Sustituir el FAR'],correctIndex:1,feedback:'El resultado debe representar la operación controlada que realmente se analiza.'},
{lesson:5,prompt:'Excluir automáticamente comparables con pérdidas aisladas es:',options:['Una práctica neutral','Potencial cherry-picking','Siempre obligatorio','Una regla OCDE universal'],correctIndex:1,feedback:'Las pérdidas aisladas requieren contexto; la exclusión mecánica puede sesgar el set.'},
{lesson:6,prompt:'Un ajuste complejo con supuestos débiles:',options:['Siempre mejora comparabilidad','Puede reducir confiabilidad','Debe aplicarse si existe cualquier diferencia','Es preferible a no ajustar'],correctIndex:1,feedback:'Materialidad, cuantificación y transparencia importan tanto como la existencia de la diferencia.'},
{lesson:7,prompt:'Un resultado dentro de rango valida toda la narrativa técnica.',options:['Verdadero','Falso'],correctIndex:1,feedback:'El rango sólo valida una parte de la cadena y no corrige inconsistencias previas.'},
{lesson:8,prompt:'Un problema estructural debería remediarse principalmente con:',options:['Mejor redacción','La acción que reabra la etapa afectada, como FAR, segmentación, método o comparables','Un disclaimer','Cambiar la mediana'],correctIndex:1,feedback:'La remediación debe atacar la causa técnica del hallazgo, no maquillarla.'}
];