export const s7Course={id:'course-s7',curriculumVersion:'v1',level:'Senior Knowledge',code:'S7',title:'Professional Judgment',description:'Desarrolla juicio profesional para decidir qué pregunta debe responderse, qué hechos son suficientes, qué información falta, qué inferencias son razonables y qué límites debe reconocer una conclusión técnica.',prerequisites:['S1–S6'],estimatedMinutes:235,lessonCount:8,passingScore:80,learningOutcomes:['Distinguir hecho, supuesto e inferencia.','Identificar la pregunta técnica real detrás de una solicitud.','Priorizar información por su capacidad de cambiar la conclusión.','Reconocer límites y ajustar el nivel de certeza del lenguaje.','Documentar alternativas, decisión y sensibilidades de juicio profesional.']};
export const s7Lessons=[
{id:'s7-1',courseId:'course-s7',curriculumVersion:'v1',sequence:1,title:'Identificar la verdadera pregunta',estimatedMinutes:25,learningOutcomes:['Reformular instrucciones operativas como preguntas técnicas.']},
{id:'s7-2',courseId:'course-s7',curriculumVersion:'v1',sequence:2,title:'Hecho, supuesto e inferencia',estimatedMinutes:25,learningOutcomes:['Separar hechos observados, supuestos adoptados e inferencias razonables.']},
{id:'s7-3',courseId:'course-s7',curriculumVersion:'v1',sequence:3,title:'Pedir información que cambia la conclusión',estimatedMinutes:28,learningOutcomes:['Formular requerimientos de alto valor y priorizarlos por impacto.']},
{id:'s7-4',courseId:'course-s7',curriculumVersion:'v1',sequence:4,title:'Reconocer límites del análisis',estimatedMinutes:25,learningOutcomes:['Reconocer cuándo una conclusión requiere reserva o no puede emitirse.']},
{id:'s7-5',courseId:'course-s7',curriculumVersion:'v1',sequence:5,title:'Consistencia narrativa',estimatedMinutes:28,learningOutcomes:['Comprobar coherencia entre hechos, FAR, método, datos, resultado y documentación.']},
{id:'s7-6',courseId:'course-s7',curriculumVersion:'v1',sequence:6,title:'Nivel de certeza y lenguaje profesional',estimatedMinutes:28,learningOutcomes:['Ajustar el lenguaje al grado real de soporte de la evidencia.']},
{id:'s7-7',courseId:'course-s7',curriculumVersion:'v1',sequence:7,title:'Cuándo regresar en el análisis',estimatedMinutes:28,learningOutcomes:['Reconocer hallazgos que obligan a regresar y reconsiderar decisiones previas.']},
{id:'s7-8',courseId:'course-s7',curriculumVersion:'v1',sequence:8,title:'Documentar juicio profesional',estimatedMinutes:48,learningOutcomes:['Documentar pregunta, hechos, faltantes, alternativas, decisión y sensibilidades.']}
];