export const ss1Course={id:'course-ss1',curriculumVersion:'v1',level:'Semi Senior',code:'SS1',title:'Servicios Intragrupo',description:'Analiza si existe realmente un servicio remunerable, quién se beneficia, cómo se asignan los costos y qué lógica económica debe preceder a cualquier mark-up.',prerequisites:['Junior Foundations','Transfer Pricing Practitioner'],estimatedMinutes:190,lessonCount:8,passingScore:80,learningOutcomes:['Aplicar conceptualmente el benefit test.','Distinguir shareholder activities, duplicative services e incidental benefits.','Diferenciar direct charge e indirect charge y seleccionar allocation keys razonables.','Comprender cost base, pass-through costs y low-value-adding intra-group services.']};export const ss1Lessons=[
{id:'ss1-1',sequence:1,title:'¿Existe realmente un servicio?',estimatedMinutes:20,learningOutcomes:['Distinguir actividad intragrupo de servicio remunerable.','Aplicar la pregunta de disposición a pagar o realizar internamente.']},
{id:'ss1-2',sequence:2,title:'Benefit Test',estimatedMinutes:22,learningOutcomes:['Evaluar beneficio económico o comercial esperado.','Distinguir beneficio razonable de éxito financiero ex post.']},
{id:'ss1-3',sequence:3,title:'Shareholder Activities',estimatedMinutes:20,learningOutcomes:['Identificar actividades propias del accionista.','Evitar clasificar toda actividad corporativa como shareholder activity.']},
{id:'ss1-4',sequence:4,title:'Duplicative Services e Incidental Benefits',estimatedMinutes:22,learningOutcomes:['Analizar duplicidad en sustancia.','Distinguir beneficio incidental de servicio identificable.']},
{id:'ss1-5',sequence:5,title:'Direct Charge Method',estimatedMinutes:20,learningOutcomes:['Reconocer cuándo los costos y beneficiarios pueden trazarse directamente.','Explicar ventajas y límites del cargo directo.']},
{id:'ss1-6',sequence:6,title:'Indirect Charge Method y Allocation Keys',estimatedMinutes:26,learningOutcomes:['Seleccionar claves vinculadas razonablemente al beneficio.','Evitar usar una sola métrica por conveniencia.']},
{id:'ss1-7',sequence:7,title:'Remuneración y Mark-up',estimatedMinutes:28,learningOutcomes:['Analizar cost base y pass-through costs.','Evitar asumir mark-ups universales.']},
{id:'ss1-8',sequence:8,title:'Low-Value-Adding Intra-Group Services',estimatedMinutes:32,learningOutcomes:['Reconocer características conceptuales del enfoque simplificado.','Resolver laboratorios y Fase 12 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss1',curriculumVersion:'v1'}));