export const ss2Course={id:'course-ss2',curriculumVersion:'v1',level:'Semi Senior',code:'SS2',title:'Activos Intangibles',description:'Identifica intangibles relevantes para Precios de Transferencia, separa propiedad legal de contribución económica y reconoce cuándo el análisis exige algo más que una etiqueta jurídica o contable.',prerequisites:['Junior Foundations','Transfer Pricing Practitioner','SS1'],estimatedMinutes:190,lessonCount:8,passingScore:80,learningOutcomes:['Identificar activos intangibles relevantes para TP aunque no estén registrados contablemente.','Distinguir propiedad legal de derecho económico a retornos.','Usar DEMPE como mapa inicial de preguntas sin convertirlo en checklist mecánico.','Distinguir licencias, transferencias, uso, financiamiento y HTVI a nivel conceptual.']};export const ss2Lessons=[
{id:'ss2-1',sequence:1,title:'¿Qué es un intangible para Precios de Transferencia?',estimatedMinutes:22,learningOutcomes:['Distinguir intangible económico de registro contable.','Reconocer ejemplos frecuentes y límites conceptuales.']},
{id:'ss2-2',sequence:2,title:'Intangible, propiedad legal y retornos',estimatedMinutes:22,learningOutcomes:['Separar titularidad jurídica de asignación económica de retornos.','Conectar funciones, activos, riesgos y contribuciones.']},
{id:'ss2-3',sequence:3,title:'Introducción a DEMPE',estimatedMinutes:24,learningOutcomes:['Reconocer Development, Enhancement, Maintenance, Protection y Exploitation.','Usar DEMPE como mapa de preguntas antes de SS3.']},
{id:'ss2-4',sequence:4,title:'Tipos de intangibles y su importancia económica',estimatedMinutes:22,learningOutcomes:['Distinguir tecnología, know-how, marcas, software y derechos contractuales.','Evitar que la etiqueta sustituya el análisis económico.']},
{id:'ss2-5',sequence:5,title:'Licencia, uso y transferencia',estimatedMinutes:22,learningOutcomes:['Distinguir derecho de uso, transferencia de derechos y servicios relacionados.','Delimitar correctamente la operación según los derechos concedidos.']},
{id:'ss2-6',sequence:6,title:'Métodos y valoración: visión conceptual',estimatedMinutes:26,learningOutcomes:['Reconocer CUP, Profit Split, métodos basados en utilidad y técnicas de valoración como alternativas potenciales.','Entender que SS2 no pretende formar valuadores completos.']},
{id:'ss2-7',sequence:7,title:'Financiamiento y riesgo',estimatedMinutes:22,learningOutcomes:['Explicar por qué financiar no equivale a controlar riesgos.','Relacionar remuneración con funciones, activos y riesgos controlados.']},
{id:'ss2-8',sequence:8,title:'Hard-to-Value Intangibles (HTVI): introducción',estimatedMinutes:30,learningOutcomes:['Reconocer el concepto HTVI y su contexto de incertidumbre.','Resolver laboratorios y la Fase 13 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss2',curriculumVersion:'v1'}));