export const ss2Assessments=[
{lesson:1,prompt:'¿Que un activo no esté reconocido contablemente impide que sea relevante para TP?',options:['Sí','No'],correctIndex:1,feedback:'En TP puede existir un intangible económicamente relevante aunque no figure como activo contable.'},
{lesson:2,prompt:'¿La propiedad legal determina automáticamente todos los retornos del intangible?',options:['Sí','No'],correctIndex:1,feedback:'La titularidad jurídica es relevante, pero deben analizarse funciones, activos, riesgos y contribuciones económicas.'},
{lesson:3,prompt:'En SS2, DEMPE debe utilizarse principalmente como:',options:['Checklist mecánico de remuneración','Mapa inicial de preguntas sobre funciones y riesgos','Método de valoración','Sustituto del FAR'],correctIndex:1,feedback:'SS2 introduce DEMPE como mapa conceptual; el análisis profundo corresponde a SS3.'},
{lesson:4,prompt:'¿La etiqueta “marca” o “software” basta para determinar su importancia económica?',options:['Sí','No'],correctIndex:1,feedback:'Dos intangibles con la misma etiqueta pueden tener perfiles económicos completamente distintos.'},
{lesson:5,prompt:'TechCo conserva la propiedad del software y concede uso limitado por cinco años, sin sublicencia ni modificación. ¿Qué describe mejor la operación?',options:['Venta definitiva','Licencia o derecho de uso limitado','Servicio de marketing','Transferencia total del intangible'],correctIndex:1,feedback:'Los hechos describen un derecho de uso sin transferencia de propiedad.'},
{lesson:6,prompt:'Si no existen licencias comparables confiables, ¿pueden considerarse otras aproximaciones?',options:['No, CUP es obligatorio','Sí, según hechos pueden considerarse Profit Split, métodos de utilidad o técnicas de valoración','Sólo TNMM','Sólo valor contable'],correctIndex:1,feedback:'No existe un único método para intangibles; la confiabilidad depende de los hechos y datos disponibles.'},
{lesson:7,prompt:'¿Aportar financiamiento para desarrollar un intangible equivale automáticamente a controlar el riesgo de desarrollo?',options:['Sí','No'],correctIndex:1,feedback:'Financiar es relevante, pero no sustituye funciones ni control efectivo de riesgos.'},
{lesson:8,prompt:'¿Todo intangible novedoso debe clasificarse automáticamente como HTVI?',options:['Sí','No'],correctIndex:1,feedback:'HTVI es un concepto específico ligado a determinados supuestos de incertidumbre y asimetría de información.'}
];