export const ss3Course={id:'course-ss3',curriculumVersion:'v1',level:'Semi Senior',code:'SS3',title:'DEMPE',description:'Analiza de forma estructurada Development, Enhancement, Maintenance, Protection y Exploitation y conecta cada función con personas, decisiones, activos, riesgos, financiamiento y asignación de retornos.',prerequisites:['SS2 — Activos Intangibles'],estimatedMinutes:200,lessonCount:8,passingScore:80,learningOutcomes:['Explicar el propósito del análisis DEMPE y diferenciar sus cinco funciones.','Identificar qué entidad realiza materialmente cada función y distinguir ejecución de control del riesgo.','Analizar el papel de activos, capacidad financiera y financiamiento en actividades relacionadas con intangibles.','Construir un mapa DEMPE coherente y conectarlo con la asignación económica de retornos.']};export const ss3Lessons=[
{id:'ss3-1',sequence:1,title:'DEMPE como marco de análisis',estimatedMinutes:22,learningOutcomes:['Explicar qué es y qué no es DEMPE.','Formular preguntas sobre funciones, decisiones, activos y riesgos.']},
{id:'ss3-2',sequence:2,title:'Development',estimatedMinutes:24,learningOutcomes:['Identificar actividades de desarrollo.','Distinguir financiamiento de dirección y control del desarrollo.']},
{id:'ss3-3',sequence:3,title:'Enhancement',estimatedMinutes:24,learningOutcomes:['Reconocer mejoras económicamente significativas.','Distinguir Enhancement de mantenimiento rutinario.']},
{id:'ss3-4',sequence:4,title:'Maintenance',estimatedMinutes:22,learningOutcomes:['Identificar actividades destinadas a conservar valor o funcionalidad.','Evaluar importancia, complejidad y riesgo de las actividades de mantenimiento.']},
{id:'ss3-5',sequence:5,title:'Protection',estimatedMinutes:22,learningOutcomes:['Reconocer actividades de protección jurídica y operativa.','Distinguir ejecución administrativa de decisiones estratégicas de protección.']},
{id:'ss3-6',sequence:6,title:'Exploitation',estimatedMinutes:22,learningOutcomes:['Explicar cómo un intangible genera valor económico.','Distinguir explotación estratégica de distribución rutinaria.']},
{id:'ss3-7',sequence:7,title:'Control del riesgo, activos y financiamiento',estimatedMinutes:30,learningOutcomes:['Conectar DEMPE con control de riesgos y capacidad financiera.','Distinguir remuneración por financiamiento de retornos asociados a funciones y riesgos controlados.']},
{id:'ss3-8',sequence:8,title:'De DEMPE a asignación de retornos',estimatedMinutes:34,learningOutcomes:['Integrar funciones, activos, riesgos, financiamiento, contratos y conducta.','Resolver laboratorios y la Fase 14 de Manufacturas del Bajío sin asignaciones mecánicas.']}
].map(x=>({...x,courseId:'course-ss3',curriculumVersion:'v1'}));