export const ss3Assessments=[
{lesson:1,prompt:'¿Cuál describe mejor DEMPE?',options:['Un método de valoración','Un marco para analizar funciones relacionadas con intangibles','Una fórmula para repartir regalías','Una clasificación contable'],correctIndex:1,feedback:'DEMPE organiza el análisis de funciones relacionadas con intangibles; no es un método de valoración ni una fórmula de reparto.'},
{lesson:2,prompt:'IP Holding financia I+D, pero TechCo emplea científicos, decide líneas de investigación y cuándo abandonar proyectos. ¿Qué conclusión es más sólida?',options:['IP Holding realiza Development por pagar','TechCo parece realizar y controlar aspectos sustanciales de Development','Ambas reciben automáticamente 50%','La propiedad legal decide'],correctIndex:1,feedback:'El financiamiento no sustituye la evidencia sobre personal, decisiones y control del riesgo de desarrollo.'},
{lesson:3,prompt:'Una filial adapta tecnología existente y sus mejoras incrementan materialmente su funcionalidad y se usan en otras plantas. Esto puede ser:',options:['Sólo Maintenance','Enhancement','Sólo Protection','Irrelevante si no posee la patente'],correctIndex:1,feedback:'Las mejoras significativas pueden constituir Enhancement aunque la filial no sea propietaria legal.'},
{lesson:4,prompt:'¿Cuál es la mejor descripción de Maintenance?',options:['Crear siempre un intangible desde cero','Conservar valor o funcionalidad del intangible','Registrar legalmente una patente','Aportar financiamiento'],correctIndex:1,feedback:'Maintenance comprende actividades destinadas a conservar el valor o funcionalidad del intangible.'},
{lesson:5,prompt:'LegalCo renueva registros siguiendo una política definida por otra entidad. ¿Qué debe investigarse?',options:['Nada: registrar equivale a controlar','Quién controla las decisiones estratégicas de Protection','Sólo quién paga las tasas','Sólo el país de registro'],correctIndex:1,feedback:'Debe distinguirse la ejecución administrativa de Protection del control estratégico de las decisiones.'},
{lesson:6,prompt:'Exploitation equivale siempre a distribución de productos.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Exploitation se refiere al uso del intangible para generar valor y puede incluir licencias, producción, marca, tecnología y decisiones estratégicas.'},
{lesson:7,prompt:'Una entidad aporta capital, pero no tiene personal técnico ni capacidad para decidir sobre riesgos de I+D. ¿Qué es correcto?',options:['Tiene automáticamente derecho a todo residual','El financiamiento debe analizarse separadamente del control del riesgo','Controla el riesgo porque paga','DEMPE deja de ser relevante'],correctIndex:1,feedback:'Financiar es una contribución distinta de tomar decisiones y controlar riesgos.'},
{lesson:8,prompt:'¿Cuál es la forma correcta de pasar de DEMPE a retornos?',options:['Asignar 20% por cada letra','Considerar conjuntamente funciones, activos, riesgos, importancia económica, financiamiento, contratos y conducta','Seguir sólo la propiedad legal','Contar cuántas funciones realiza cada entidad'],correctIndex:1,feedback:'La asignación de retornos no es mecánica; exige integrar contribuciones económicas, riesgos y conducta real.'}
];