export const ss4Course={id:'course-ss4',curriculumVersion:'v1',level:'Semi Senior',code:'SS4',title:'Operaciones Financieras I: Préstamos',description:'Analiza préstamos intragrupo desde la delimitación económica: borrower, lender, capacidad de endeudamiento, creditworthiness, términos, CUP financiero y estructura de tasa.',prerequisites:['SS3 — DEMPE'],estimatedMinutes:235,lessonCount:10,passingScore:80,learningOutcomes:['Distinguir deuda de capital a nivel conceptual y delimitar un préstamo intragrupo.','Analizar borrower, lender, creditworthiness y control del riesgo financiero.','Identificar términos que afectan la tasa y aplicar la lógica de un CUP financiero.','Evitar comenzar el análisis directamente con una tasa de mercado y justificar la naturaleza y monto de la financiación.']};export const ss4Lessons=[
{id:'ss4-1',sequence:1,title:'Antes de la tasa: delimitar la transacción',estimatedMinutes:22,learningOutcomes:['Identificar monto, propósito, plazo, moneda, amortización, garantías y demás condiciones.','Explicar por qué la tasa no es la primera pregunta.']},
{id:'ss4-2',sequence:2,title:'Deuda vs. capital: concepto económico',estimatedMinutes:22,learningOutcomes:['Reconocer indicadores económicos de deuda.','Distinguir análisis TP de reglas jurídicas locales.']},
{id:'ss4-3',sequence:3,title:'Borrower: el prestatario',estimatedMinutes:24,learningOutcomes:['Analizar capacidad de pago, flujo, leverage y propósito.','Entender creditworthiness como evaluación económica.']},
{id:'ss4-4',sequence:4,title:'Lender: el prestamista',estimatedMinutes:20,learningOutcomes:['Analizar capacidad para asumir riesgo financiero.','Conectar provisión de fondos con control real del riesgo.']},
{id:'ss4-5',sequence:5,title:'Creditworthiness y riesgo de crédito',estimatedMinutes:24,learningOutcomes:['Identificar factores que afectan el riesgo de crédito.','Explicar la relación entre riesgo percibido y retorno exigido.']},
{id:'ss4-6',sequence:6,title:'Términos que afectan la tasa',estimatedMinutes:24,learningOutcomes:['Analizar plazo, moneda, fecha, garantía, seniority, covenants y amortización.','Explicar por qué mismo borrower no implica misma tasa.']},
{id:'ss4-7',sequence:7,title:'CUP financiero',estimatedMinutes:24,learningOutcomes:['Identificar referencias potenciales comparables.','Controlar diferencias relevantes en condiciones financieras.']},
{id:'ss4-8',sequence:8,title:'Spread y estructura de tasa',estimatedMinutes:20,learningOutcomes:['Comprender reference rate + credit spread como concepto pedagógico.','Evitar tratar spreads por rating como regla universal.']},
{id:'ss4-9',sequence:9,title:'Garantías y subordinación',estimatedMinutes:20,learningOutcomes:['Explicar el efecto económico de garantías y subordinación.','Distinguir garantía explícita de apoyo implícito.']},
{id:'ss4-10',sequence:10,title:'Laboratorio de préstamos',estimatedMinutes:35,learningOutcomes:['Resolver casos de préstamo sencillo, distinto plazo y deuda excesiva.','Completar la Fase 15 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss4',curriculumVersion:'v1'}));