export const ss5Course={id:'course-ss5',curriculumVersion:'v1',level:'Semi Senior',code:'SS5',title:'Operaciones Financieras II',description:'Analiza garantías, implicit support, cash pooling, hedging y captive insurance desde sustancia económica, FAR, control del riesgo y beneficio real.',prerequisites:['SS4 — Operaciones Financieras I: Préstamos'],estimatedMinutes:205,lessonCount:8,passingScore:80,learningOutcomes:['Distinguir garantía explícita de implicit support y aislar beneficio incremental.','Comprender la lógica económica de cash pooling y diferenciar funciones del leader y participantes.','Analizar hedging y captive insurance desde exposición, control del riesgo y capacidad financiera.','Aplicar una secuencia de análisis antes de valorar operaciones financieras complejas.']};
export const ss5Lessons=[
{id:'ss5-1',sequence:1,title:'Garantías explícitas',estimatedMinutes:24,learningOutcomes:['Explicar qué cambia económicamente una garantía.','Separar beneficio incremental de otros efectos del grupo.']},
{id:'ss5-2',sequence:2,title:'Implicit support',estimatedMinutes:22,learningOutcomes:['Definir apoyo implícito.','Distinguirlo de una garantía contractual remunerable.']},
{id:'ss5-3',sequence:3,title:'Cash pooling',estimatedMinutes:24,learningOutcomes:['Explicar objetivos económicos del cash pool.','Distinguir physical pooling y notional pooling a alto nivel.']},
{id:'ss5-4',sequence:4,title:'Participantes y cash pool leader',estimatedMinutes:28,learningOutcomes:['Analizar funciones, activos y riesgos del leader.','Evitar remunerar por etiqueta.']},
{id:'ss5-5',sequence:5,title:'Remuneración de participantes en cash pool',estimatedMinutes:28,learningOutcomes:['Evaluar condiciones económicas de depositantes y prestatarios.','Reconocer que no existe una fórmula universal de reparto del beneficio.']},
{id:'ss5-6',sequence:6,title:'Hedging',estimatedMinutes:23,learningOutcomes:['Identificar exposición original y quién decide cubrirla.','Distinguir ejecución de cobertura de control del riesgo.']},
{id:'ss5-7',sequence:7,title:'Captive insurance',estimatedMinutes:26,learningOutcomes:['Identificar funciones reales de aseguramiento.','Evaluar si la entidad controla riesgos y tiene capacidad financiera.']},
{id:'ss5-8',sequence:8,title:'Marco de análisis y laboratorio integrado',estimatedMinutes:30,learningOutcomes:['Aplicar la secuencia de ocho pasos a operaciones financieras complejas.','Resolver los laboratorios y la Fase 16 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss5',curriculumVersion:'v1'}));