export const ss5Assessments=[
{lesson:1,prompt:'¿Qué debe preguntarse primero al analizar una garantía explícita?',options:['Qué fee cobrar','Si genera beneficio económico incremental y qué riesgo asume el garante','Qué país tiene menor tasa','Qué contrato usar'],correctIndex:1,feedback:'La remuneración sólo se analiza después de identificar el beneficio incremental y el riesgo real.'},
{lesson:2,prompt:'Implicit support significa:',options:['Garantía contractual automática','Expectativa de apoyo derivada de pertenencia al grupo y circunstancias económicas','Seguro obligatorio','Colateral específico'],correctIndex:1,feedback:'El apoyo implícito puede afectar el perfil crediticio sin constituir una garantía contractual cobrable.'},
{lesson:3,prompt:'¿Cuál es un objetivo económico típico de un cash pool?',options:['Crear intangibles','Gestionar liquidez y reducir saldos ociosos o deuda externa','Eliminar todo riesgo crediticio','Fijar una tasa universal'],correctIndex:1,feedback:'El cash pooling coordina liquidez; su estructura jurídica puede variar.'},
{lesson:4,prompt:'¿Qué determina principalmente la remuneración del cash pool leader?',options:['Su título','Sus funciones, activos, riesgos y control real','El número de participantes','El país donde se constituyó'],correctIndex:1,feedback:'Un leader administrativo y uno con funciones financieras sustantivas no deben remunerarse igual por etiqueta.'},
{lesson:5,prompt:'¿Existe una regla universal para repartir el beneficio total del cash pool?',options:['Sí','No'],correctIndex:1,feedback:'El análisis depende de posiciones, riesgos, funciones, alternativas y beneficios de sinergia.'},
{lesson:6,prompt:'Antes de valorar una cobertura, debe identificarse:',options:['Sólo el instrumento derivado','La exposición original y quién decide/controla cubrirla','Sólo la entidad que firma','Sólo el resultado contable'],correctIndex:1,feedback:'Hedging parte de la exposición económica y del control del riesgo.'},
{lesson:7,prompt:'Una captive sin empleados ni decisiones significativas debe tratarse automáticamente como aseguradora plena.',options:['Verdadero','Falso'],correctIndex:1,feedback:'La caracterización depende de underwriting, pricing, claims, control del riesgo, capacidad financiera y personal real.'},
{lesson:8,prompt:'¿Cuál es el orden profesional correcto antes de valorar una operación financiera compleja?',options:['Fee → contrato → benchmark','Identificar y delimitar → FAR/control → beneficio → alternativas → variable a valorar → método/comparables → documentar','Benchmark → spread → FAR','Contrato → fee'],correctIndex:1,feedback:'La secuencia evita valorar una etiqueta antes de entender su sustancia económica.'}
];