export const ss6Course={id:'course-ss6',curriculumVersion:'v1',level:'Semi Senior',code:'SS6',title:'Reestructuraciones Empresariales',description:'Analiza reestructuraciones comparando FAR y derechos antes y después, identificando transferencias de valor, profit potential, opciones realistamente disponibles y remuneración post-reestructuración.',prerequisites:['SS5 — Operaciones Financieras II'],estimatedMinutes:205,lessonCount:8,passingScore:80,learningOutcomes:['Identificar cuándo una reorganización puede constituir una reestructuración relevante para precios de transferencia.','Comparar FAR y derechos antes y después e identificar transferencias o terminaciones económicamente relevantes.','Analizar profit potential y opciones realistamente disponibles sin inferir compensación sólo por una caída de rentabilidad.','Separar una eventual compensación inicial de la remuneración arm’s length post-reestructuración.']};
export const ss6Lessons=[
{id:'ss6-1',sequence:1,title:'¿Qué es una reestructuración empresarial?',estimatedMinutes:22,learningOutcomes:['Reconocer escenarios típicos de reestructuración.','Analizar efectos económicos en lugar de etiquetas corporativas.']},
{id:'ss6-2',sequence:2,title:'FAR antes y después',estimatedMinutes:26,learningOutcomes:['Construir dos fotografías FAR comparables.','Identificar cambios en funciones, activos, riesgos, derechos y conducta.']},
{id:'ss6-3',sequence:3,title:'Transferencia de funciones, activos y riesgos',estimatedMinutes:26,learningOutcomes:['Identificar qué puede constituir algo de valor.','Evitar asumir que toda función eliminada genera indemnización.']},
{id:'ss6-4',sequence:4,title:'Profit potential',estimatedMinutes:24,learningOutcomes:['Explicar profit potential como expectativa económica y no como activo autónomo automático.','Considerar escenarios positivos, negativos y sustancia económica.']},
{id:'ss6-5',sequence:5,title:'¿Existiría compensación entre independientes?',estimatedMinutes:26,learningOutcomes:['Evaluar derechos contractuales, terminación y posiciones transferidas.','Reconocer que la compensación depende de hechos y circunstancias.']},
{id:'ss6-6',sequence:6,title:'Opciones realistamente disponibles',estimatedMinutes:23,learningOutcomes:['Comparar el cambio propuesto con alternativas reales.','Evitar opciones puramente teóricas.']},
{id:'ss6-7',sequence:7,title:'Remuneración post-reestructuración',estimatedMinutes:24,learningOutcomes:['Separar compensación inicial de remuneración futura.','Determinar la remuneración posterior a partir del FAR real posterior.']},
{id:'ss6-8',sequence:8,title:'Estructura de análisis y laboratorio integrado',estimatedMinutes:34,learningOutcomes:['Aplicar la secuencia de diez pasos de análisis.','Resolver los laboratorios y la Fase 17 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss6',curriculumVersion:'v1'}));