export const ss6Assessments=[
{lesson:1,prompt:'¿Cuál es la pregunta rectora al comenzar una reestructuración?',options:['¿Cuánto bajó el margen?','¿Qué cambió realmente para cada parte?','¿Qué nombre dio el grupo al proyecto?','¿Qué país tiene menor impuesto?'],correctIndex:1,feedback:'La etiqueta corporativa no determina el tratamiento; primero se identifican los efectos económicos reales.'},
{lesson:2,prompt:'El análisis FAR de una reestructuración requiere:',options:['Sólo describir el nuevo modelo','Comparar funciones, activos, riesgos, derechos y expectativas antes y después','Sólo revisar contratos','Comparar únicamente márgenes'],correctIndex:1,feedback:'Se requieren dos fotografías comparables: antes y después, incluyendo conducta real.'},
{lesson:3,prompt:'Que una entidad deje de realizar una función significa automáticamente que debe ser indemnizada.',options:['Verdadero','Falso'],correctIndex:1,feedback:'Debe identificarse si se transfirió algo de valor o si un independiente habría exigido compensación por renunciar a derechos u oportunidades.'},
{lesson:4,prompt:'Profit potential es:',options:['Siempre un activo autónomo transferible','La expectativa de beneficios futuros asociada con funciones, activos, riesgos, derechos y oportunidades','La diferencia matemática entre el margen anterior y posterior','Sólo los escenarios positivos'],correctIndex:1,feedback:'Profit potential no es automáticamente un activo y debe analizarse junto con la sustancia económica y los riesgos.'},
{lesson:5,prompt:'¿Qué factor es relevante para evaluar una eventual compensación?',options:['Sólo que la entidad quede peor','Derechos contractuales, condiciones de terminación, valor transferido y alternativas reales','Sólo el margen histórico','El nombre de la reestructuración'],correctIndex:1,feedback:'La existencia y cuantía de una compensación dependen de hechos, derechos y circunstancias comparables entre independientes.'},
{lesson:6,prompt:'Una opción realistamente disponible debe ser:',options:['Cualquier alternativa imaginable','Una alternativa que la entidad podría ejecutar realmente','La opción con mayor utilidad teórica','Una alternativa del grupo consolidado'],correctIndex:1,feedback:'No deben inventarse alternativas teóricas que la entidad no podría ejecutar.'},
{lesson:7,prompt:'Compensación inicial y remuneración post-reestructuración:',options:['Son la misma pregunta','Son preguntas distintas que deben analizarse separadamente','Siempre se compensan entre sí','Sólo dependen del contrato'],correctIndex:1,feedback:'Primero se pregunta si hubo transferencia o terminación compensable; después se remunera el FAR del nuevo modelo.'},
{lesson:8,prompt:'¿Qué debe ocurrir antes de valorar una reestructuración?',options:['Elegir una tasa de descuento','Identificar qué se transfirió o terminó y analizar FAR, derechos, profit potential y opciones','Calcular la mediana','Fijar una indemnización objetivo'],correctIndex:1,feedback:'Valorar antes de identificar qué se transfirió es uno de los errores expresamente señalados en SS6.'}
];