export const ss7Course={id:'course-ss7',curriculumVersion:'v1',level:'Semi Senior',code:'SS7',title:'Cost Contribution Arrangements',description:'Distingue un verdadero CCA de un simple reparto de costos y analiza participantes, beneficios esperados, contribuciones, balancing payments y entradas/salidas.',prerequisites:['SS6 — Reestructuraciones Empresariales'],estimatedMinutes:200,lessonCount:8,passingScore:80,learningOutcomes:['Identificar participantes elegibles y distinguirlos de proveedores de servicios al CCA.','Relacionar contribuciones con beneficios esperados mediante claves económicamente razonables.','Comprender cuándo debe valorarse una contribución y cómo funcionan los balancing payments.','Analizar buy-in, buy-out, documentación y consistencia entre contrato y conducta.']};
export const ss7Lessons=[
{id:'ss7-1',sequence:1,title:'¿Qué es un Cost Contribution Arrangement?',estimatedMinutes:22,learningOutcomes:['Definir un CCA desde su sustancia económica.','Distinguirlo de un simple mecanismo para dividir facturas.']},
{id:'ss7-2',sequence:2,title:'¿Quién puede ser participante?',estimatedMinutes:22,learningOutcomes:['Identificar participantes elegibles.','Distinguir participante de proveedor remunerado de servicios.']},
{id:'ss7-3',sequence:3,title:'Expected Benefits / Beneficios esperados',estimatedMinutes:25,learningOutcomes:['Relacionar contribuciones con beneficios esperados.','Seleccionar claves de asignación con conexión económica.']},
{id:'ss7-4',sequence:4,title:'Contributions / Contribuciones',estimatedMinutes:24,learningOutcomes:['Identificar distintas formas de contribución.','Reconocer cuándo el costo histórico no representa valor económico.']},
{id:'ss7-5',sequence:5,title:'Balancing Payments',estimatedMinutes:24,learningOutcomes:['Detectar desequilibrios entre contribuciones y beneficios.','Explicar la lógica económica de un pago de ajuste.']},
{id:'ss7-6',sequence:6,title:'Buy-in y Buy-out',estimatedMinutes:24,learningOutcomes:['Analizar entradas y salidas de participantes.','Identificar valor preexistente y derechos transferidos.']},
{id:'ss7-7',sequence:7,title:'CCA vs. Servicios Intragrupo',estimatedMinutes:23,learningOutcomes:['Distinguir participación conjunta de prestación de servicios.','Evitar clasificar por etiqueta contractual.']},
{id:'ss7-8',sequence:8,title:'Documentación y laboratorio integrado',estimatedMinutes:36,learningOutcomes:['Documentar participantes, beneficios, derechos, contribuciones y ajustes.','Resolver los laboratorios y la Fase 18 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss7',curriculumVersion:'v1'}));