export const ss7Assessments=[
{lesson:1,prompt:'¿Un acuerdo para dividir una factura externa entre filiales es necesariamente un CCA?',options:['Sí','No; debe existir participación económica conjunta, contribuciones, riesgos y beneficios esperados'],correctIndex:1,feedback:'La sustancia económica, no el reparto contable, determina si existe un verdadero CCA.'},
{lesson:2,prompt:'¿Qué caracteriza a un participante de un CCA?',options:['Paga una parte del costo','Espera beneficios del acuerdo y tiene derechos o intereses consistentes con su participación','Está en el mismo grupo','Firma cualquier contrato'],correctIndex:1,feedback:'Pagar no basta: debe existir participación económica y expectativa razonable de beneficio.'},
{lesson:3,prompt:'¿Qué debe guiar la clave para asignar contribuciones?',options:['La facilidad de cálculo','La conexión con los beneficios esperados','El número de participantes','La jerarquía corporativa'],correctIndex:1,feedback:'No existe una clave universal; debe guardar relación económica con el beneficio esperado.'},
{lesson:4,prompt:'¿El costo histórico refleja siempre el valor de una contribución?',options:['Sí','No'],correctIndex:1,feedback:'Tecnología, know-how u otros activos pueden tener un valor económico muy distinto de su costo histórico.'},
{lesson:5,prompt:'¿Para qué sirve un balancing payment?',options:['Igualar utilidades','Alinear contribuciones económicas con beneficios esperados','Reducir impuestos','Hacer que todos paguen lo mismo'],correctIndex:1,feedback:'El objetivo es restablecer el equilibrio económico del CCA.'},
{lesson:6,prompt:'Una nueva entidad entra a un CCA y recibe derechos sobre tecnología preexistente. ¿Qué debe analizarse?',options:['Sólo costos futuros','Si corresponde una compensación de entrada por valor preexistente','Sólo headcount','Nada adicional'],correctIndex:1,feedback:'La entrada puede requerir buy-in cuando se reciben derechos o valor desarrollado previamente.'},
{lesson:7,prompt:'Tech Services desarrolla código, cobra cost plus, no tiene derechos sobre el software ni beneficios de uso. ¿Qué parece ser?',options:['Participante del CCA','Prestador de servicios al CCA','Propietario residual','Beneficiario principal'],correctIndex:1,feedback:'Puede prestar servicios al CCA sin ser participante económico.'},
{lesson:8,prompt:'¿Qué debe ser consistente con la documentación del CCA?',options:['Sólo el contrato','La conducta real de los participantes','Sólo la contabilidad','Sólo la clave de reparto'],correctIndex:1,feedback:'Participantes, derechos, riesgos, contribuciones y beneficios deben reflejar la conducta efectiva.'}
];