export const ss8Course={id:'course-ss8',curriculumVersion:'v1',level:'Semi Senior',code:'SS8',title:'Introducción a Controversias de TP',description:'Comprende cómo nacen las controversias de precios de transferencia, cómo puede surgir doble imposición y qué función cumplen conceptualmente primary adjustment, corresponding adjustment, MAP, APA y documentación defensiva.',prerequisites:['SS7 — Cost Contribution Arrangements'],estimatedMinutes:205,lessonCount:8,passingScore:80,learningOutcomes:['Explicar primary adjustment, corresponding adjustment y double taxation.','Distinguir MAP de procedimientos domésticos y APA como mecanismo preventivo de certeza.','Identificar qué suele estar bajo escrutinio en una auditoría de TP.','Diagnosticar técnicamente una controversia desde hechos, delimitación, FAR, método, comparabilidad y documentación.']};
export const ss8Lessons=[
{id:'ss8-1',sequence:1,title:'¿Cómo nace una controversia de TP?',estimatedMinutes:24,learningOutcomes:['Identificar puntos donde puede originarse una controversia.','Reconocer que el desacuerdo puede comenzar antes del cálculo final.']},
{id:'ss8-2',sequence:2,title:'Primary Adjustment',estimatedMinutes:22,learningOutcomes:['Definir ajuste primario.','Distinguir la arquitectura OCDE de consecuencias jurídicas locales.']},
{id:'ss8-3',sequence:3,title:'Corresponding Adjustment y Doble Imposición',estimatedMinutes:24,learningOutcomes:['Explicar cómo surge doble imposición.','Entender que el ajuste correlativo no es automático.']},
{id:'ss8-4',sequence:4,title:'Mutual Agreement Procedure / MAP',estimatedMinutes:25,learningOutcomes:['Explicar la función de coordinación entre autoridades competentes.','Distinguir MAP de auditoría, juicio o negociación privada.']},
{id:'ss8-5',sequence:5,title:'Advance Pricing Arrangements / APA',estimatedMinutes:24,learningOutcomes:['Explicar el propósito preventivo de un APA.','Distinguir APA unilateral, bilateral y multilateral a nivel conceptual.']},
{id:'ss8-6',sequence:6,title:'Auditoría de TP: qué suele estar bajo escrutinio',estimatedMinutes:25,learningOutcomes:['Reconocer áreas técnicas comúnmente revisadas.','Entender por qué una defensa no se reduce al benchmark.']},
{id:'ss8-7',sequence:7,title:'Documentación como herramienta de defensa',estimatedMinutes:25,learningOutcomes:['Conectar evidencia contemporánea con defensa técnica.','Distinguir hechos, supuestos, estimaciones, juicios y limitaciones.']},
{id:'ss8-8',sequence:8,title:'Estrategia técnica y laboratorio integrado',estimatedMinutes:36,learningOutcomes:['Aplicar una secuencia de diagnóstico técnico de controversias.','Resolver laboratorios y la Fase 19 de Manufacturas del Bajío.']}
].map(x=>({...x,courseId:'course-ss8',curriculumVersion:'v1'}));