export const ss8Assessments=[
{lesson:1,prompt:'Cuando una autoridad cuestiona el resultado, ¿qué debe revisarse primero?',options:['Sólo el rango','La cadena completa: hechos → delimitación → FAR → método → comparabilidad → resultado → documentación','Sólo el cálculo','Sólo la declaración'],correctIndex:1,feedback:'Una controversia puede originarse mucho antes del cálculo final.'},
{lesson:2,prompt:'¿Qué es un primary adjustment?',options:['El ajuste inicial de una administración a una operación controlada','Un ajuste correlativo','Un APA','Un benchmark'],correctIndex:0,feedback:'Es el ajuste inicial efectuado por una administración al considerar que la operación no cumple plena competencia.'},
{lesson:3,prompt:'¿El corresponding adjustment es automático en todos los casos?',options:['Sí','No'],correctIndex:1,feedback:'La otra jurisdicción puede necesitar evaluar si acepta el ajuste primario y en qué medida.'},
{lesson:4,prompt:'MAP es principalmente:',options:['Una auditoría local','Coordinación entre autoridades competentes bajo un tratado','Un método TP','Una garantía de resultado'],correctIndex:1,feedback:'MAP busca resolver imposición no conforme con el tratado mediante coordinación entre autoridades competentes.'},
{lesson:5,prompt:'¿Cuál es la diferencia central entre MAP y APA?',options:['MAP atiende controversias ya surgidas; APA busca certeza anticipada para operaciones cubiertas','Son equivalentes','APA es judicial','MAP fija tasas futuras'],correctIndex:0,feedback:'MAP es principalmente resolutivo; APA, preventivo y prospectivo.'},
{lesson:6,prompt:'Si la autoridad cuestiona la caracterización funcional, ¿basta defender el benchmark?',options:['Sí','No; deben revisarse hechos, FAR y delimitación antes del benchmark'],correctIndex:1,feedback:'Si cambia la caracterización, puede cambiar tested party, método o remuneración.'},
{lesson:7,prompt:'¿Qué hace valiosa a la evidencia contemporánea?',options:['Que es más extensa','Que muestra qué se sabía y cómo se razonó al momento del análisis','Que siempre favorece al contribuyente','Que sustituye el FAR'],correctIndex:1,feedback:'Una defensa sólida se construye con evidencia existente y coherente antes de la controversia.'},
{lesson:8,prompt:'En Fase 19, la autoridad cuestiona riesgo de mercado y caracterización. ¿Dónde está el núcleo técnico?',options:['Sólo en el rango','En FAR, control del riesgo y caracterización','Sólo en la tasa fiscal','Sólo en el formato del Local File'],correctIndex:1,feedback:'El benchmark es posterior a la premisa funcional que ahora está bajo controversia.'}
];