export type C1Question = { id: number; prompt: string; options: string[]; correctIndex: number; feedback: string };
const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):C1Question=>({id,prompt,options,correctIndex,feedback});
export const c1FinalBank:C1Question[]=[
q(1,'¿Cuál es el punto de partida adecuado para delimitar una operación?',['Elegir TNMM','Identificar hechos, términos, FAR y circunstancias relevantes','Calcular el rango intercuartil','Buscar comparables'],1,'El método viene después de comprender y delimitar la operación.'),
q(2,'El nombre jurídico del contrato determina por sí solo la naturaleza económica de la operación.',['Verdadero','Falso'],1,'La conducta y los hechos deben contrastarse con el contrato.'),
q(3,'¿Qué ocurre si contrato y conducta son coherentes?',['El contrato puede describir adecuadamente la operación','Debe ignorarse el contrato','Siempre debe aplicarse Profit Split','La operación no requiere análisis'],0,'La coherencia entre contrato y conducta permite usar el contrato como descripción relevante, sujeto al resto de los hechos.'),
q(4,'¿Cuál NO es una característica económicamente relevante?',['Funciones, activos y riesgos','Términos contractuales','Circunstancias económicas','Color corporativo del logotipo'],3,'El color del logotipo no determina las condiciones económicas de la operación.'),
q(5,'En un préstamo intragrupo, ¿qué conjunto es especialmente relevante?',['Monto, moneda, plazo, garantía y solvencia','Logo, sitio web y número de empleados','Sólo el nombre del contrato','Únicamente la tasa'],0,'La delimitación del financiamiento requiere considerar sus condiciones económicas relevantes.'),
q(6,'Para que una asignación contractual de riesgo sea económicamente consistente debe revisarse especialmente:',['Quién firmó primero','Control del riesgo y capacidad financiera','Tamaño del grupo','País de constitución'],1,'La asignación contractual no basta: importa quién controla el riesgo y tiene capacidad financiera para asumirlo.'),
q(7,'Control del riesgo significa, en términos prácticos:',['Pagar cualquier costo relacionado','Tomar decisiones relevantes para aceptar, evitar o mitigar el riesgo','Tener más empleados','Aparecer como responsable en el contrato'],1,'El control se vincula con la toma real de decisiones relevantes sobre el riesgo.'),
q(8,'Una descripción fuerte de una operación debe:',['Limitarse a decir compra-venta','Explicar naturaleza económica y hechos relevantes','Copiar el objeto social','Elegir primero un método'],1,'La delimitación debe producir una descripción económica verificable.'),
q(9,'La secuencia conceptual correcta es:',['Método → hechos → comparables → contrato','Hechos → delimitación → caracterización → método','Comparables → método → hechos → FAR','Contrato → TNMM → rango → hechos'],1,'El método se selecciona después de comprender y caracterizar la operación.'),
q(10,'Si cambian materialmente las funciones y riesgos de un distribuidor:',['La caracterización económica puede cambiar','La etiqueta distribuidor impide cualquier cambio','Siempre se vuelve fabricante','Nada cambia si existe contrato'],0,'La caracterización depende de los hechos, no sólo de la etiqueta.'),
q(11,'Un contrato prevé servicios mensuales, pero el supuesto prestador no tiene personal ni terceros y no hay evidencia. ¿Qué conclusión es más prudente?',['El contrato prueba por sí solo el servicio','Debe verificarse si el servicio ocurrió realmente','Debe aplicarse Cost Plus automáticamente','El pago demuestra el beneficio'],1,'La existencia contractual no demuestra por sí sola la prestación efectiva.'),
q(12,'¿Qué elemento debe incluir una delimitación bien redactada?',['Partes, naturaleza, FAR, riesgos y términos relevantes','Sólo el monto facturado','Únicamente el método','Sólo la conclusión'],0,'Una delimitación útil conecta las partes, la operación y sus características económicamente relevantes.'),
q(13,'La capacidad financiera para asumir un riesgo es irrelevante si el contrato lo asigna expresamente.',['Verdadero','Falso'],1,'La capacidad financiera forma parte del análisis económico de la asignación del riesgo.'),
q(14,'Una entidad decide precios, clientes, inventarios y campañas relevantes aunque el contrato la llame distribuidor de riesgo limitado. ¿Qué procede?',['Aceptar la etiqueta contractual','Contrastar la etiqueta con la conducta y reconsiderar la caracterización','Ignorar todas sus funciones','Elegir RPM automáticamente'],1,'Los hechos pueden mostrar un perfil económico distinto del descrito contractualmente.'),
q(15,'¿Cuál es la mejor regla práctica para C1?',['Primero describe hechos; después asigna etiquetas','Primero selecciona el método','El contrato siempre prevalece','Primero busca comparables'],0,'La delimitación comienza con hechos y conducta.'),
q(16,'En manufactura, una entidad opera planta y controla calidad mientras la relacionada controla diseño, volúmenes y mercado. ¿Qué debe reflejar la delimitación?',['La distribución real de funciones y riesgos entre ambas partes','Sólo quién emite la factura','Sólo quién posee más activos','Que ambas partes hacen lo mismo'],0,'La delimitación debe reflejar las contribuciones económicas efectivas de cada parte.'),
q(17,'Una distribuidora ejecuta campañas aprobadas por matriz, mantiene inventario corto y no controla estrategia global. Inicialmente parece:',['Distribuidor rutinario, sujeto a confirmar los hechos','Propietario de intangibles únicos','Prestamista','Fabricante complejo'],0,'Los hechos apuntan preliminarmente a funciones rutinarias de distribución.'),
q(18,'AdminCo tiene personal propio de contabilidad y nómina, costos identificables y receptores sin ese personal. ¿Qué apoyan esos hechos?',['La existencia efectiva de servicios intragrupo','La inexistencia del servicio','Un préstamo implícito','Una licencia de intangible'],0,'Personal, actividades y evidencia operativa apoyan la prestación efectiva.'),
q(19,'En un financiamiento intragrupo, el prestamista tiene tesorería que evalúa solvencia y monitorea pagos. Esto es relevante porque:',['Evidencia funciones reales vinculadas al riesgo de crédito','Elimina la necesidad de contrato','Determina automáticamente la tasa','Convierte el préstamo en capital'],0,'Las funciones reales de evaluación y monitoreo ayudan a delimitar el financiamiento y el control del riesgo.'),
q(20,'¿Cuál es un error frecuente de delimitación?',['Validar contrato contra conducta','Conectar funciones con riesgos','Usar etiquetas limited risk sin explicar hechos','Identificar circunstancias económicas'],2,'Las etiquetas sin sustento fáctico debilitan la caracterización.'),
q(21,'Describir FAR como una lista aislada es insuficiente porque:',['Debe explicar cómo funciones, activos y riesgos se conectan con la operación','FAR sólo sirve para impuestos locales','Siempre debe contener comparables','Debe sustituirse por el contrato'],0,'El valor del FAR está en explicar la contribución económica de las partes.'),
q(22,'¿Qué parte parece controlar un riesgo comercial si decide precios, clientes y promociones y soporta descuentos?',['La que toma esas decisiones y soporta las consecuencias','Siempre el fabricante','Siempre la matriz','La que aparece primero en el contrato'],0,'Las decisiones y consecuencias económicas son evidencia central del control.'),
q(23,'¿Cuándo puede ser necesario reconsiderar una caracterización contractual?',['Cuando la conducta efectiva contradice materialmente los términos pactados','Nunca','Sólo si cambia el nombre legal','Únicamente cuando hay pérdidas'],0,'Una contradicción material entre contrato y conducta exige revisar la operación efectivamente realizada.'),
q(24,'Las circunstancias económicas:',['Pueden ser relevantes para delimitar y comparar operaciones','Nunca importan','Sólo importan en préstamos','Sustituyen el FAR'],0,'Mercado, geografía, ciclo y otras circunstancias pueden afectar las condiciones de la operación.'),
q(25,'Las estrategias empresariales:',['Son una de las categorías de características económicamente relevantes','No pertenecen al análisis','Determinan automáticamente el método','Sólo importan para marketing'],0,'Las estrategias empresariales forman parte de las características económicamente relevantes.'),
q(26,'Una delimitación profesional debe ser:',['Clara, breve y verificable','Lo más extensa posible','Una copia del contrato','Una conclusión sin hechos'],0,'La calidad está en conectar hechos relevantes con una conclusión económica defendible.'),
q(27,'Si faltan hechos críticos para determinar quién controla un riesgo, lo correcto es:',['Pedir información adicional','Inventar un supuesto','Aceptar la asignación contractual sin revisión','Elegir TNMM'],0,'La falta de evidencia se resuelve buscando hechos, no inventándolos.'),
q(28,'C1 busca principalmente que el alumno:',['Aplique un método complejo','Reconstruya la operación real a partir de hechos y conducta','Calcule ajustes de capital de trabajo','Domine Profit Split'],1,'El propósito central de C1 es la delimitación precisa de la operación.'),
q(29,'Una venta recurrente de producto terminado por un fabricante a un distribuidor relacionado debe describirse únicamente como compra-venta.',['Verdadero','Falso'],1,'La descripción debe incorporar las funciones, activos, riesgos y condiciones que expliquen su naturaleza económica.'),
q(30,'¿Por qué la delimitación precede a la selección del método?',['Porque el método debe aplicarse a la operación económica correctamente entendida','Porque todos los métodos producen lo mismo','Porque el contrato no importa','Porque evita revisar comparabilidad'],0,'Un método técnicamente correcto aplicado a una operación mal delimitada puede producir una conclusión equivocada.')
];
export const C1_ATTEMPT_SIZE=15;
export const C1_PASS_SCORE=80;
