export type C3Question={id:number;prompt:string;options:string[];correctIndex:number;feedback:string}; const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):C3Question=>({id,prompt,options,correctIndex,feedback});
export const c3FinalBank:C3Question[]=[
q(1,'TNMM compara principalmente:',['Precio unitario','Margen neto relativo a una base apropiada','Tasa legal','Impuesto'],1,'TNMM analiza rentabilidad neta respecto de una base económica apropiada.'),
q(2,'La tested party debe elegirse por tener menor utilidad.',['Verdadero','Falso'],1,'La selección depende de confiabilidad, FAR y comparables.'),
q(3,'Operating Margin = Utilidad Operativa / Ventas.',['Verdadero','Falso'],0,'Esa es la fórmula usada en C3.'),
q(4,'Mark-up on Costs relaciona utilidad operativa con costos relevantes.',['Verdadero','Falso'],0,'El denominador debe ser una base de costos económicamente apropiada.'),
q(5,'Berry Ratio =',['Utilidad Operativa/Ventas','Utilidad Bruta/Gastos Operativos','Utilidad Operativa/Activos','Ventas/Costos'],1,'Berry Ratio usa utilidad bruta sobre gastos operativos.'),
q(6,'ROA relaciona utilidad operativa con:',['Ventas','Costos','Activos operativos','Pasivos'],2,'ROA usa activos operativos como base.'),
q(7,'En los ejercicios de C3, intereses son operativos en todos los casos.',['Verdadero','Falso'],1,'Para estos ejercicios se consideran no operativos.'),
q(8,'En los ejercicios de C3, impuestos sobre la renta forman parte de utilidad operativa.',['Verdadero','Falso'],1,'Se excluyen de utilidad operativa.'),
q(9,'Ventas 1,000; utilidad operativa 50. Operating Margin:',['2.5%','5.0%','10.0%','20.0%'],1,'50/1,000=5%.'),
q(10,'Utilidad operativa 100; costos 800. Mark-up:',['8%','10%','12.5%','20%'],2,'100/800=12.5%.'),
q(11,'Utilidad bruta 150; gastos operativos 125. Berry Ratio:',['0.83','1.20','1.50','2.00'],1,'150/125=1.20.'),
q(12,'Utilidad operativa 60; activos 500. ROA:',['5%','10%','12%','15%'],2,'60/500=12%.'),
q(13,'Una entidad con manufactura y distribución puede requerir segmentación.',['Verdadero','Falso'],0,'Perfiles funcionales distintos pueden requerir análisis segmentado.'),
q(14,'La segmentación debe usar criterios razonables y documentables.',['Verdadero','Falso'],0,'La asignación de ingresos, costos y gastos debe ser defendible.'),
q(15,'TNMM elimina la necesidad de comparabilidad.',['Verdadero','Falso'],1,'TNMM sigue requiriendo comparabilidad funcional y contable.'),
q(16,'TNMM puede ser menos sensible que CUP a ciertas diferencias de producto.',['Verdadero','Falso'],0,'Pero sigue siendo sensible a diferencias funcionales y contables.'),
q(17,'Diferencias funcionales pueden afectar TNMM.',['Verdadero','Falso'],0,'La comparabilidad funcional sigue siendo central.'),
q(18,'Si un resultado cae dentro de un rango, toda la entidad cumple arm’s length para cualquier operación.',['Verdadero','Falso'],1,'La conclusión debe limitarse al alcance analizado.'),
q(19,'Una fórmula correcta compensa datos mal clasificados.',['Verdadero','Falso'],1,'La calidad de datos es parte de la confiabilidad.'),
q(20,'La consistencia contable entre tested party y comparables importa.',['Verdadero','Falso'],0,'Diferencias de clasificación pueden distorsionar el PLI.'),
q(21,'Gastos no relacionados con la actividad analizada pueden distorsionar el PLI.',['Verdadero','Falso'],0,'Por eso debe evaluarse segmentación y clasificación.'),
q(22,'Para un distribuidor, Operating Margin puede ser razonable dependiendo de los hechos.',['Verdadero','Falso'],0,'La selección del PLI es contextual.'),
q(23,'Para un fabricante, Mark-up on Costs puede ser razonable dependiendo de los hechos.',['Verdadero','Falso'],0,'Los costos pueden reflejar una base económica apropiada.'),
q(24,'Berry Ratio debe usarse para cualquier distribuidor.',['Verdadero','Falso'],1,'Su uso es limitado y depende de funciones y estructura económica.'),
q(25,'ROA puede ser útil cuando activos operativos son relevantes y medibles.',['Verdadero','Falso'],0,'La base de activos debe reflejar la actividad analizada.'),
q(26,'Ventas 800; utilidad operativa 32. Operating Margin:',['2%','4%','6%','8%'],1,'32/800=4%.'),
q(27,'Costos 500; utilidad operativa 40. Mark-up:',['4%','6%','8%','10%'],2,'40/500=8%.'),
q(28,'Utilidad bruta 120; gastos operativos 100. Berry Ratio:',['1.00','1.20','1.40','2.00'],1,'120/100=1.20.'),
q(29,'Utilidad operativa 75; activos operativos 625. ROA:',['8%','10%','12%','15%'],2,'75/625=12%.'),
q(30,'Una entidad tiene dos segmentos funcionalmente distintos y sólo uno corresponde a la operación controlada. ¿Qué debe evaluarse?',['Usar estados totales siempre','Segmentar razonablemente y analizar el segmento pertinente','Promediar ambas actividades','Cambiar de método automáticamente'],1,'El análisis debe procurar aislar la actividad pertinente con criterios razonables.')
]; export const C3_ATTEMPT_SIZE=12; export const C3_PASS_SCORE=80;