export type C4Question={id:number;prompt:string;options:string[];correctIndex:number;feedback:string};const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):C4Question=>({id,prompt,options,correctIndex,feedback});
export const c4FinalBank:C4Question[]=[
q(1,'Comparabilidad significa identidad perfecta.',['Verdadero','Falso'],1,'Comparabilidad admite diferencias que no sean materiales o puedan ajustarse confiablemente.'),
q(2,'La búsqueda debe comenzar antes de delimitar la operación.',['Verdadero','Falso'],1,'La operación correctamente delimitada es el punto de partida.'),
q(3,'Una empresa del mismo sector es automáticamente comparable.',['Verdadero','Falso'],1,'La industria no sustituye FAR y demás condiciones relevantes.'),
q(4,'Un comparable interno puede ser especialmente informativo, pero requiere análisis.',['Verdadero','Falso'],0,'Conocer mejor sus condiciones no elimina diferencias potenciales.'),
q(5,'¿Qué debe orientar los criterios de búsqueda?',['Resultado deseado','FAR y operación delimitada','Número mínimo de empresas','Costumbre'],1,'Los criterios deben responder a la economía de la operación.'),
q(6,'Disponibilidad de estados financieros puede ser un filtro cuantitativo.',['Verdadero','Falso'],0,'Es un dato estructurado relevante para la usabilidad del candidato.'),
q(7,'Leer descripciones de negocio es parte de la revisión cualitativa.',['Verdadero','Falso'],0,'La revisión funcional exige entender la actividad real.'),
q(8,'Rechazar una empresa sólo por margen alto es apropiado.',['Verdadero','Falso'],1,'El margen no debe usarse como filtro ex post.'),
q(9,'ACCEPT significa:',['Empresa idéntica','Cumple criterios y no se identifican diferencias materiales incompatibles','Margen dentro del rango','Misma jurisdicción'],1,'Accept es una conclusión basada en criterios y evidencia disponible.'),
q(10,'Si falta información suficiente puede usarse Review antes de decidir.',['Verdadero','Falso'],0,'No debe forzarse una conclusión sin evidencia.'),
q(11,'La independencia puede ser un criterio relevante.',['Verdadero','Falso'],0,'Puede formar parte del diseño de búsqueda.'),
q(12,'Los códigos de industria sustituyen la revisión funcional.',['Verdadero','Falso'],1,'Son un punto de partida, no una conclusión de comparabilidad.'),
q(13,'¿Qué debe documentarse?',['Sólo comparables finales','Criterios y razones de exclusión','Sólo el rango','Sólo fecha'],1,'La trazabilidad de criterios y decisiones es esencial.'),
q(14,'El conjunto final puede depender de la calidad de información disponible.',['Verdadero','Falso'],0,'La usabilidad depende también de la evidencia disponible.'),
q(15,'Cambiar criterios después de ver resultados puede introducir sesgo.',['Verdadero','Falso'],0,'Los criterios deben definirse antes del resultado y aplicarse consistentemente.'),
q(16,'Marca propia e I+D significativa pueden ser problemáticas para comparar con un distribuidor rutinario.',['Verdadero','Falso'],0,'Pueden reflejar funciones e intangibles incompatibles.'),
q(17,'Una empresa integrada fabricante-distribuidor puede requerir rechazo si no puede segmentarse y difiere del perfil.',['Verdadero','Falso'],0,'La integración puede afectar materialmente comparabilidad.'),
q(18,'Las pérdidas recurrentes deben eliminarse siempre.',['Verdadero','Falso'],1,'Un filtro de pérdidas requiere justificación económica.'),
q(19,'Un filtro de pérdidas puede usarse con justificación económica y aplicación consistente.',['Verdadero','Falso'],0,'No debe ser un filtro mecánico para mejorar resultados.'),
q(20,'Los ajustes de capital tienen una fórmula OCDE única obligatoria.',['Verdadero','Falso'],1,'La Academy enseña la lógica económica y reconoce variaciones metodológicas.'),
q(21,'CxC, CxP, inventarios y PP&E pueden generar diferencias económicas relevantes aunque las fórmulas de ajuste varíen.',['Verdadero','Falso'],0,'C5 profundizará su lógica económica.'),
q(22,'El análisis de comparabilidad está conectado con el método seleccionado.',['Verdadero','Falso'],0,'Método y características relevantes condicionan la búsqueda.'),
q(23,'Falta de información financiera del periodo puede ser razón válida de exclusión.',['Verdadero','Falso'],0,'Sin datos necesarios el candidato puede no ser usable.'),
q(24,'Una descripción de negocio compatible basta siempre para aceptar.',['Verdadero','Falso'],1,'Debe cumplirse el resto de criterios y existir información suficiente.'),
q(25,'¿Cuál es una razón pobre de rechazo?',['Intangibles únicos','Manufactura no comparable','Margen demasiado alto','Datos insuficientes'],2,'El resultado financiero no es por sí mismo criterio de comparabilidad.'),
q(26,'Distribuidor rutinario vs. empresa que diseña, fabrica y patenta.',['ACCEPT','REJECT','ACCEPT por misma industria','ACCEPT si el margen es bajo'],1,'Las funciones e intangibles son significativamente distintos.'),
q(27,'Fabricante por contrato, sin I+D, funciones compatibles.',['Potencial ACCEPT sujeto al resto de criterios','REJECT automático','REJECT por no tener marca','ACCEPT sin revisar datos'],0,'El perfil funcional es compatible, sujeto a los demás criterios.'),
q(28,'Empresa funcionalmente compatible pero sin información financiera necesaria.',['Siempre ACCEPT','Normalmente no usable para el análisis propuesto','Accept si tiene web','Ignorar el periodo'],1,'La falta de información puede impedir aplicar el análisis.'),
q(29,'¿Por qué documentar Accept/Reject?',['Para reducir el rango','Para reproducibilidad, transparencia y defensa del razonamiento','Para escoger márgenes','No es necesario'],1,'La documentación permite entender y defender el proceso.'),
q(30,'¿Por qué no eliminar un comparable sólo por su margen?',['Porque todos los márgenes son válidos','Porque crea riesgo de sesgo ex post y manipulación del rango','Porque el margen nunca importa','Porque OCDE prohíbe cualquier filtro'],1,'La exclusión debe basarse en comparabilidad o calidad de información, no en el resultado deseado.')
];export const C4_ATTEMPT_SIZE=12;export const C4_PASS_SCORE=80;