export type CaseQuestion={id:string;domain:string;prompt:string;options:string[];correct:number[];explanation:string};
export const CONSULTANT_CASE_PASS_SCORE=80;
export const consultantCaseQuestions:CaseQuestion[]=[
{id:'case-1',domain:'Delimitación',prompt:'Considerando contrato y conducta consistentes, ¿cuál es la delimitación más sólida?',options:['Manufacturas del Bajío explota intangibles técnicos y controla la estrategia comercial.','Manufacturas del Bajío presta manufactura intragrupo relativamente rutinaria conforme a especificaciones y estrategia controladas por la relacionada.','Ambas partes aportan intangibles únicos y deben compartir utilidades.','La operación se delimita únicamente como venta de componentes porque así se factura.'],correct:[1],explanation:'Los hechos muestran manufactura rutinaria, activos ordinarios y ausencia de intangibles únicos en Manufacturas del Bajío; la relacionada controla diseño, intangibles y estrategia.'},
{id:'case-2',domain:'Tested party',prompt:'¿Qué parte es la candidata más razonable a tested party?',options:['La relacionada porque posee los intangibles más valiosos.','Manufacturas del Bajío porque es la parte menos compleja y existen comparables de fabricantes por contrato.','La empresa con mayores ventas.','No puede existir tested party bajo TNMM.'],correct:[1],explanation:'La tested party suele ser la parte menos compleja para la que puede aplicarse el método de forma confiable.'},
{id:'case-3',domain:'Método',prompt:'¿Qué conclusión sobre método y PLI está mejor sustentada por los hechos?',options:['CUP, porque los métodos tradicionales tienen prioridad jerárquica.','Cost Plus con margen bruto, porque toda manufactura debe analizarse así.','TNMM sobre Manufacturas del Bajío con Operating Margin, dada la disponibilidad de márgenes operativos comparables y las limitaciones de CUP y margen bruto.','Profit Split, porque siempre es preferible cuando existen intangibles en el grupo.'],correct:[2],explanation:'La confiabilidad relativa favorece TNMM con Operating Margin bajo los hechos proporcionados.'},
{id:'case-4',domain:'Método',prompt:'Selecciona TODAS las razones sustentadas por los hechos para considerar menos confiables CUP y Cost Plus.',options:['No existe una venta interna suficientemente comparable para CUP.','Los datos públicos de margen bruto presentan inconsistencias importantes de clasificación contable.','TNMM siempre tiene prioridad sobre CUP y Cost Plus.','Manufacturas del Bajío tiene un margen de 5.9%.'],correct:[0,1],explanation:'Las limitaciones provienen de comparabilidad y calidad de datos, no de una jerarquía automática ni del resultado observado.'},
{id:'case-5',domain:'Proceso',prompt:'¿Cuál es la secuencia conceptual correcta?',options:['Método → rango → delimitación → comparables.','Delimitación/FAR → tested party y método/PLI → comparables → ajustes si mejoran confiabilidad → rango → documentación.','Comparables → mediana → método → FAR.','Rango → ajuste → delimitación → método.'],correct:[1],explanation:'La evaluación integra la cadena de razonamiento desarrollada en C1–C7.'},
{id:'case-6',domain:'Comparabilidad',prompt:'¿Qué papel cumplen los siete comparables identificados?',options:['Crean comparabilidad porque generan un rango.','Proporcionan referencias independientes razonablemente confiables después del proceso de búsqueda y evaluación.','Son válidos sólo porque sus márgenes rodean 5.9%.','Eliminan la necesidad de analizar diferencias económicas.'],correct:[1],explanation:'El rango organiza resultados de comparables previamente evaluados; no crea comparabilidad.'},
{id:'case-7',domain:'Ajustes',prompt:'Al observar mayores cuentas por cobrar e inventarios en algunos comparables, ¿qué debe hacerse primero?',options:['Aplicar automáticamente la fórmula propia de la firma.','Ajustar hasta que la mediana coincida con 5.9%.','Evaluar si las diferencias son materiales y si un ajuste razonablemente fiable mejora la comparabilidad.','Excluir automáticamente a todos esos comparables.'],correct:[2],explanation:'C5 exige existencia, materialidad y confiabilidad antes de ajustar.'},
{id:'case-8',domain:'Ajustes',prompt:'Selecciona TODAS las afirmaciones técnicamente consistentes sobre working capital.',options:['CxC, CxP e inventarios pueden reflejar diferencias de financiamiento operativo.','La metodología utilizada debe explicarse y documentarse.','La Academy prescribe una fórmula universal obligatoria.','Si el ajuste introduce más incertidumbre que la diferencia, puede ser preferible no ajustar.'],correct:[0,1,3],explanation:'La Academy enseña la lógica económica y no prescribe una fórmula universal.'},
{id:'case-9',domain:'Rango',prompt:'IQR 3.8%–7.2%, mediana 5.4%, resultado 5.9%. ¿Cuál es la interpretación correcta?',options:['Debe ajustarse a 5.4% porque todo resultado debe igualar la mediana.','Está dentro del rango y, bajo los hechos y metodología proporcionados, es consistente con el rango de plena competencia.','Incumple porque está por encima de la mediana.','El rango no puede utilizarse con TNMM.'],correct:[1],explanation:'Estar dentro del rango definido puede ser consistente con plena competencia bajo el análisis realizado.'},
{id:'case-10',domain:'Revisión técnica',prompt:'Un consultor escribe: “Como 5.9% supera la mediana de 5.4%, debe ajustarse a la mediana”. ¿Cuál es el problema principal?',options:['No calculó Q1.','Confunde la mediana con un objetivo obligatorio pese a que el resultado está dentro del rango.','Debió usar Profit Split.','Debió eliminar el comparable con margen más alto.'],correct:[1],explanation:'La mediana no convierte automáticamente los demás resultados dentro del rango en incumplimiento.'},
{id:'case-11',domain:'Documentación',prompt:'Selecciona TODOS los elementos que deberían conectarse coherentemente en el EPT/Local File de este caso.',options:['Hechos y FAR.','Delimitación y selección de método/PLI.','Búsqueda y evaluación de comparables, ajustes y rango.','Conclusión y limitaciones relevantes.','Sólo la tabla final del rango.'],correct:[0,1,2,3],explanation:'La documentación debe mostrar una cadena coherente entre hechos, análisis y conclusión.'},
{id:'case-12',domain:'Revisión técnica',prompt:'¿Cuál es la conclusión integral más defendible?',options:['El 5.9% prueba por sí solo plena competencia y vuelve innecesaria la documentación.','TNMM/Operating Margin sobre Manufacturas del Bajío es razonable bajo los hechos; los comparables y posibles ajustes deben sustentarse; 5.9% está dentro del rango y la conclusión debe documentarse coherentemente.','Cost Plus debe utilizarse porque Manufacturas del Bajío fabrica.','Debe aplicarse un working capital adjustment aunque no se demuestre materialidad.'],correct:[1],explanation:'Esta opción integra delimitación, método, comparabilidad, ajustes, rango y documentación sin introducir reglas no soportadas.'}
];
