export type JuniorDomain = 'Fundamentos' | 'Arm\'s Length / delimitación' | 'FAR' | 'Métodos' | 'Comparabilidad';
export type JuniorQuestion = { id: number; domain: JuniorDomain; prompt: string; options: string[]; correctIndex: number; feedback: string };
const q=(id:number,domain:JuniorDomain,prompt:string,options:string[],correctIndex:number,feedback:string):JuniorQuestion=>({id,domain,prompt,options,correctIndex,feedback});
export const juniorFoundationsBank: JuniorQuestion[] = [
q(1,'Fundamentos','Una operación entre empresas relacionadas:', ['Es automáticamente incorrecta','Puede requerir análisis bajo el principio de plena competencia','Siempre debe eliminarse','Sólo importa si existe pérdida fiscal'],1,'Una operación controlada no es incorrecta por sí misma; debe evaluarse bajo el principio de plena competencia.'),
q(2,'Fundamentos','Transfer Pricing analiza exclusivamente precios unitarios.', ['Verdadero','Falso'],1,'TP analiza condiciones de operaciones controladas, no sólo precios unitarios.'),
q(3,'Fundamentos','Antes de ejecutar un benchmark, el consultor debe primero:', ['Elegir TNMM','Entender la operación','Calcular el rango','Descargar comparables'],1,'El análisis comienza con los hechos y la operación, no con la herramienta.'),
q(4,'Arm\'s Length / delimitación','El principio de plena competencia evalúa si las condiciones entre relacionadas son consistentes con las que habrían acordado independientes en circunstancias comparables.', ['Verdadero','Falso'],0,'Esa es la lógica central del arm’s length principle.'),
q(5,'Arm\'s Length / delimitación','Si contrato y conducta real difieren materialmente, el análisis debe considerar:', ['Sólo el contrato','Sólo la factura','La conducta real y los hechos económicamente relevantes','El documento más antiguo'],2,'La delimitación precisa exige contrastar contrato con conducta y hechos.'),
q(6,'FAR','FAR significa:', ['Finance, Accounting, Revenue','Functions, Assets and Risks','Fiscal Allocation Rules','Functional Adjustment Range'],1,'FAR significa Functions, Assets and Risks.'),
q(7,'FAR','¿Cuál es una función?', ['Ejecutar manufactura','Poseer una marca','Asumir riesgo cambiario','Tener inventario'],0,'Manufacturar es una actividad realizada: una función.'),
q(8,'FAR','¿Cuál es un activo?', ['Política de descuentos','Maquinaria','Riesgo de inventario','Negociación con clientes'],1,'La maquinaria es un activo utilizado en la operación.'),
q(9,'FAR','¿Cuál es un riesgo?', ['Obsolescencia de inventario','Prestar servicio','Utilizar oficina','Tener empleados'],0,'La obsolescencia de inventario es una exposición económica.'),
q(10,'FAR','Dos empresas con funciones diferentes pueden requerir remuneraciones diferentes aunque vendan el mismo producto.', ['Verdadero','Falso'],0,'La remuneración depende del perfil económico, no sólo del producto.'),
q(11,'Métodos','CUP compara principalmente:', ['Precios o contraprestaciones de operaciones comparables','Margen neto','Retorno sobre activos únicamente','Utilidad residual'],0,'CUP compara directamente precios o condiciones de operaciones comparables.'),
q(12,'Métodos','RPM suele ser conceptualmente relevante cuando:', ['Un distribuidor revende bienes sin agregar valor sustancial','Se analiza un préstamo','Ambas partes poseen intangibles únicos','Se valora una garantía financiera'],0,'RPM puede ser natural para distribución de reventa sin transformación sustancial.'),
q(13,'Métodos','Cost Plus parte de:', ['Costo más margen','Precio de reventa menos margen','Utilidad residual','Tasa libre de riesgo'],0,'Cost Plus añade un mark-up apropiado a una base de costos relevante.'),
q(14,'Métodos','TNMM analiza:', ['Exclusivamente el precio unitario','Margen neto respecto de una base apropiada','Únicamente contratos','Sólo intangibles'],1,'TNMM compara rentabilidad neta relativa a una base apropiada.'),
q(15,'Métodos','Profit Split puede ser relevante cuando:', ['Ambas partes realizan contribuciones únicas y valiosas','Existe una transacción simple con CUP confiable','No hay información de ninguna clase','Siempre que haya pérdidas'],0,'Contribuciones únicas, valiosas o altamente integradas pueden justificar Profit Split.'),
q(16,'Métodos','El método más apropiado se selecciona automáticamente por tipo de operación.', ['Verdadero','Falso'],1,'La selección depende de hechos, FAR, información y confiabilidad.'),
q(17,'Comparabilidad','Un comparable interno es:', ['Una empresa del mismo grupo','Una operación similar entre una de las partes y un tercero independiente','Cualquier competidor','Un contrato histórico interno'],1,'El comparable interno surge de una operación de una de las partes con un independiente.'),
q(18,'Comparabilidad','Un comparable externo proviene de:', ['Operaciones o empresas independientes externas a las partes','Únicamente una subsidiaria hermana','Información interna confidencial','Cualquier sociedad del grupo'],0,'El comparable externo se obtiene fuera de las partes de la operación controlada.'),
q(19,'Comparabilidad','El mismo código de industria garantiza comparabilidad.', ['Verdadero','Falso'],1,'El código de industria es sólo un punto de partida.'),
q(20,'Comparabilidad','¿Cuál NO es un factor de comparabilidad?', ['Características del bien o servicio','FAR','Términos contractuales','Color corporativo'],3,'El color corporativo no es un factor económico de comparabilidad.'),
q(21,'FAR','Una distribuidora relacionada no posee intangibles, realiza funciones rutinarias y asume riesgos limitados. ¿Qué caracterización parece inicialmente coherente?', ['Distribuidor rutinario o de riesgo limitado, sujeto a confirmar hechos','Emprendedor principal','Propietario de intangibles únicos','Prestamista'],0,'El perfil descrito apunta inicialmente a una distribución rutinaria.'),
q(22,'Arm\'s Length / delimitación','El contrato asigna riesgo de inventario a A, pero B decide volúmenes, controla compras y absorbe pérdidas por obsolescencia. ¿Qué debe revisarse?', ['Sólo la firma del contrato','Quién controla y soporta económicamente el riesgo','El tamaño de A','La antigüedad del contrato'],1,'La asignación del riesgo requiere analizar control y capacidad financiera, no sólo texto contractual.'),
q(23,'Comparabilidad','Mismo producto se vende a relacionada y a tercero en el mismo mercado, pero el tercero compra 50% más volumen. ¿Qué debe analizarse?', ['Nada: el producto es idéntico','Impacto del volumen y otras diferencias comerciales','Sólo el país','Sólo la moneda'],1,'El volumen puede afectar precio y exige análisis de comparabilidad.'),
q(24,'Comparabilidad','Una venta a tercero del mismo producto siempre es un CUP perfecto.', ['Verdadero','Falso'],1,'Aun un CUP interno requiere revisar diferencias relevantes.'),
q(25,'Métodos','Una empresa de servicios administrativos rutinarios podría analizarse conceptualmente mediante:', ['Cost Plus o TNMM, dependiendo de hechos y comparabilidad','Profit Split necesariamente','Sólo CUP','Ningún método'],0,'La selección depende de los hechos y de la información confiable disponible.'),
q(26,'Fundamentos','¿Qué afirmación es correcta sobre las Directrices OCDE?', ['Sustituyen la legislación local','Son un marco internacional de referencia cuya aplicación debe contrastarse con la norma local','Son una plantilla de estudio','Sólo sirven para empresas europeas'],1,'Las Directrices son referencia doctrinal; la norma local sigue siendo determinante.'),
q(27,'Comparabilidad','La comparabilidad exige identidad absoluta.', ['Verdadero','Falso'],1,'Puede existir comparabilidad si las diferencias no son materiales o pueden ajustarse confiablemente.'),
q(28,'Comparabilidad','Un ajuste de comparabilidad puede ser apropiado cuando:', ['Una diferencia material puede ajustarse de forma confiable','Queremos aumentar artificialmente la muestra','Existe cualquier diferencia','Faltan hechos'],0,'El objetivo es mejorar confiabilidad frente a una diferencia material.'),
q(29,'Comparabilidad','Si un ajuste depende de supuestos muy débiles:', ['Siempre debe aplicarse','Puede reducir la confiabilidad','Mejora necesariamente el análisis','Sustituye FAR'],1,'Un ajuste débil puede introducir más error del que corrige.'),
q(30,'FAR','Un distribuidor que desarrolla marca propia puede no ser comparable con uno rutinario principalmente por diferencias en:', ['FAR','Únicamente tamaño','Sólo país','Nada relevante'],0,'Funciones y activos intangibles pueden cambiar sustancialmente el perfil económico.'),
q(31,'Arm\'s Length / delimitación','Manufacturas del Bajío: el contrato asigna inventario a la relacionada, pero Manufacturas decide niveles, recompras y absorbe obsolescencia; además hay una venta a tercero con plazos y volúmenes distintos. ¿Qué dos áreas revisar primero?', ['Control del riesgo y comparabilidad de la venta a tercero','Sólo el método y la mediana','Únicamente el contrato','Sólo el tamaño del grupo'],0,'Primero deben resolverse la delimitación del riesgo y la confiabilidad de la referencia independiente.'),
q(32,'FAR','¿Qué debe producir un buen FAR?', ['Una lista larga de funciones','Una explicación económica de cómo las partes contribuyen a la operación','Un rango intercuartil','Una tasa de impuesto'],1,'FAR debe explicar la contribución económica de las partes.'),
q(33,'FAR','El hecho de que una entidad tenga activos en su balance significa automáticamente que todos son económicamente relevantes para la transacción.', ['Verdadero','Falso'],1,'Sólo importan los activos relevantes para la operación y la creación de valor analizada.'),
q(34,'FAR','¿Cuál es la mejor pregunta al revisar un riesgo?', ['¿Quién aparece en el organigrama?','¿Quién controla decisiones y tiene capacidad financiera relacionada con el riesgo?','¿Qué entidad es más grande?','¿Qué contrato es más reciente?'],1,'Control y capacidad financiera son elementos centrales del análisis de riesgo.'),
q(35,'Métodos','La selección de método debe considerar:', ['Naturaleza de la operación','Disponibilidad de información','Comparabilidad','Todas las anteriores'],3,'La selección requiere considerar conjuntamente esos factores.'),
q(36,'FAR','Una empresa con intangibles únicos y valiosos puede requerir un análisis distinto de una entidad rutinaria.', ['Verdadero','Falso'],0,'Los intangibles y contribuciones únicas cambian el perfil económico.'),
q(37,'Comparabilidad','Dos operaciones idénticas en producto pero distintas en mercado pueden no ser comparables directamente.', ['Verdadero','Falso'],0,'Las circunstancias económicas son un factor de comparabilidad.'),
q(38,'Fundamentos','Si no existen hechos suficientes, la respuesta profesional correcta puede ser:', ['Inventar un supuesto','Pedir información adicional','Elegir TNMM','Aceptar el contrato sin revisión'],1,'La falta de hechos debe resolverse con información adicional, no con supuestos inventados.'),
q(39,'Fundamentos','El objetivo del nivel Junior es:', ['Formar un Senior completo','Dominar fundamentos y lenguaje técnico suficiente para avanzar a aplicación','Enseñar legislación de todos los países','Enseñar gestión de equipos'],1,'Junior Foundations construye fundamentos y lenguaje para avanzar al nivel Consultant.'),
q(40,'Arm\'s Length / delimitación','Una entidad relacionada presta servicios contables rutinarios usando personal propio y sin intangibles únicos. ¿Qué debe hacer primero antes de pensar en método?', ['Confirmar operación, funciones, activos, riesgos, términos y condiciones relevantes','Elegir Cost Plus automáticamente','Calcular el rango','Buscar empresas'],0,'La secuencia correcta comienza por entender y delimitar la operación.'),
];
export const JUNIOR_ATTEMPT_SIZE = 20;
export const JUNIOR_PASS_SCORE = 80;
export const JUNIOR_DOMAIN_FLOOR = 60;
export const juniorDomains: JuniorDomain[] = ['Fundamentos','Arm\'s Length / delimitación','FAR','Métodos','Comparabilidad'];