export type AdvancedCaseQuestion={id:string;domain:string;prompt:string;options:string[];correct:number[];explanation:string};export const ADVANCED_CASE_PASS_SCORE=80;
export const caseA={title:'Caso A — Centro regional, intangible y servicios',facts:'Grupo NovaTech opera en tres países. Nova IP posee legalmente una plataforma tecnológica. Nova Dev cuenta con el equipo de desarrolladores que mejora sustancialmente la plataforma, define prioridades técnicas y controla riesgos de desarrollo. Nova Services presta servicios administrativos regionales y distribuye costos mediante claves de asignación. Una parte de los servicios corresponde a reportes solicitados exclusivamente por la matriz para sus accionistas.',questions:[
{id:'a1',domain:'DEMPE + servicios',prompt:'¿Qué lectura integra correctamente DEMPE y servicios?',options:['Nova Dev debe analizarse por sus funciones DEMPE y Nova Services por actividad, beneficio y cargo','Todo es un servicio rutinario','Todo retorno pertenece automáticamente a Nova IP','La clave de asignación resuelve DEMPE'],correct:[0],explanation:'Nova Dev realiza funciones relevantes de desarrollo/mejora y controla riesgos; Nova Services requiere un análisis separado de servicios intragrupo.'},
{id:'a2',domain:'DEMPE',prompt:'¿Por qué la propiedad legal de Nova IP no resuelve por sí sola los retornos?',options:['Porque los retornos deben considerar funciones DEMPE, activos, riesgos y control','Porque la propiedad legal nunca importa','Porque siempre debe aplicarse TNMM','Porque Nova Dev debe ser legal owner'],correct:[0],explanation:'La propiedad legal es relevante, pero no sustituye el análisis de contribuciones DEMPE y control de riesgos.'},
{id:'a3',domain:'Servicios',prompt:'Los reportes solicitados exclusivamente por la matriz para sus accionistas son conceptualmente:',options:['Shareholder activities','Servicios operativos cargables automáticamente','CCA','Buy-in'],correct:[0],explanation:'Las actividades puramente de accionista no deben cargarse como servicio intragrupo al beneficiario operativo.'},
{id:'a4',domain:'Servicios',prompt:'Antes de aplicar un mark-up a Nova Services deben demostrarse TODAS las siguientes:',options:['Prestación de la actividad y beneficio','Base de costos confiable','Lógica de asignación o cargo','Propiedad legal de la plataforma'],correct:[0,1,2],explanation:'Antes del mark-up deben acreditarse servicio, beneficio, cost base y lógica de asignación.'},
{id:'a5',domain:'Evidencia',prompt:'¿Qué evidencia contemporánea sería especialmente útil? Selecciona TODAS las aplicables.',options:['Registros de decisiones técnicas de Nova Dev','Entregables y evidencia de servicios','Políticas y claves de asignación con soporte','Sólo el organigrama legal'],correct:[0,1,2],explanation:'La evidencia debe conectar conducta, decisiones, prestación, beneficio y asignación; un organigrama por sí solo no basta.'}
] as AdvancedCaseQuestion[]};
export const caseB={title:'Caso B — Financiamiento, reestructuración y controversia',facts:'Manufacturas del Bajío era fabricante con funciones comerciales limitadas. Posteriormente transfiere ciertas funciones estratégicas a otra entidad del grupo y pasa a operar como fabricante más rutinario. Al mismo tiempo entra a un cash pool regional y recibe financiamiento de una entidad relacionada. Dos años después una autoridad cuestiona que el cambio funcional haya sido correctamente documentado y sostiene que la entidad local cedió un profit potential significativo sin compensación. También cuestiona el spread del financiamiento.',questions:[
{id:'b1',domain:'Reestructuración',prompt:'¿Qué análisis before/after es el punto de partida?',options:['FAR, derechos, activos, riesgos, profit potential y opciones realistamente disponibles','Sólo comparar márgenes','Sólo revisar el contrato nuevo','Sólo contar empleados'],correct:[0],explanation:'La reestructuración exige reconstruir la posición económica antes y después, incluyendo derechos, riesgos, activos y alternativas.'},
{id:'b2',domain:'Reestructuración',prompt:'Una menor utilidad futura prueba por sí sola una transferencia compensable.',options:['Verdadero','Falso'],correct:[1],explanation:'Debe distinguirse una reducción de utilidad futura de la transferencia o terminación de algo de valor que partes independientes habrían compensado.'},
{id:'b3',domain:'Financiamiento',prompt:'Respecto del cash pool leader y del préstamo deben revisarse TODAS las siguientes:',options:['Rol real y riesgos del cash pool leader','Creditworthiness del borrower','Plazo, moneda, garantía y subordinación','Sólo una tasa de referencia'],correct:[0,1,2],explanation:'La delimitación financiera requiere analizar funciones, riesgos y términos económicamente relevantes antes del pricing.'},
{id:'b4',domain:'Financiamiento',prompt:'¿Por qué una tasa de referencia no basta para defender el spread?',options:['Porque el spread depende de comparabilidad y riesgo de la transacción delimitada','Porque las tasas nunca sirven','Porque todo préstamo relacionado es capital','Porque el cash pool elimina creditworthiness'],correct:[0],explanation:'La referencia debe evaluarse frente a borrower, plazo, moneda, garantía, subordinación y demás factores de comparabilidad.'},
{id:'b5',domain:'Controversia',prompt:'Si la autoridad aumenta la utilidad local y la contraparte ya tributó sobre el resultado original, puede surgir:',options:['Doble imposición','Buy-in','Shareholder activity','CCA'],correct:[0],explanation:'El primary adjustment puede superponer imposición sobre la misma utilidad económica si la otra jurisdicción mantiene el resultado original.'},
{id:'b6',domain:'Controversia',prompt:'¿Cuál secuencia conceptual es correcta?',options:['Primary adjustment: ajuste inicial; corresponding adjustment: posible alivio correlativo; MAP: coordinación entre autoridades competentes','MAP: auditoría; primary: APA; corresponding: litigio','Corresponding adjustment: automático; MAP: tasa de referencia','APA y MAP son idénticos'],correct:[0],explanation:'El ajuste correlativo no es automático y MAP es un mecanismo de tratado de coordinación entre autoridades competentes.'}
] as AdvancedCaseQuestion[]};