export type SS2Question={id:number;prompt:string;options:string[];correctIndex:number;feedback:string};const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):SS2Question=>({id,prompt,options,correctIndex,feedback});export const ss2FinalBank:SS2Question[]=[
q(1,'Un activo debe estar registrado contablemente para ser intangible de TP.',['Verdadero','Falso'],1,'El análisis de TP no se limita al reconocimiento contable.'),
q(2,'La propiedad legal determina automáticamente todos los retornos.',['Verdadero','Falso'],1,'La titularidad jurídica no sustituye el análisis económico.'),
q(3,'DEMPE significa Development, Enhancement, Maintenance, Protection and Exploitation.',['Verdadero','Falso'],0,'Es el acrónimo utilizado para funciones relacionadas con intangibles.'),
q(4,'¿Cuál puede constituir un intangible relevante?',['Patente','Know-how','Marca','Todas las anteriores'],3,'Todas pueden ser relevantes según los hechos.'),
q(5,'Una fuerza laboral capacitada es automáticamente un intangible transferible.',['Verdadero','Falso'],1,'Puede generar valor sin constituir necesariamente un intangible transferible separado.'),
q(6,'Una licencia y una venta son siempre equivalentes.',['Verdadero','Falso'],1,'Una licencia puede conceder uso sin transferir propiedad.'),
q(7,'¿Qué debe analizarse además de propiedad legal?',['FAR y DEMPE','Sólo contrato','Sólo valor contable','Sólo país'],0,'Funciones, activos, riesgos y contribuciones son esenciales.'),
q(8,'Financiar desarrollo equivale automáticamente a controlar riesgo.',['Verdadero','Falso'],1,'Financiamiento y control del riesgo son conceptos distintos.'),
q(9,'¿Qué función DEMPE se relaciona con creación inicial?',['Development','Protection','Maintenance','Exploitation'],0,'Development se refiere al desarrollo.'),
q(10,'¿Cuál se relaciona con mejoras posteriores?',['Enhancement','Protection','Maintenance','Exploitation'],0,'Enhancement se refiere a mejora.'),
q(11,'¿Cuál se relaciona con conservar utilidad y vigencia?',['Development','Maintenance','Protection','Exploitation'],1,'Maintenance se refiere al mantenimiento.'),
q(12,'¿Cuál puede incluir defensa de derechos?',['Development','Enhancement','Protection','Exploitation'],2,'Protection comprende protección jurídica o comercial.'),
q(13,'¿Cuál se relaciona con decisiones de uso comercial?',['Maintenance','Development','Exploitation','Protection'],2,'Exploitation se vincula con explotación comercial.'),
q(14,'CUP puede ser relevante si existen licencias comparables confiables.',['Verdadero','Falso'],0,'La existencia de comparables suficientemente confiables puede hacer relevante CUP.'),
q(15,'Profit Split puede considerarse cuando varias partes aportan contribuciones únicas y valiosas.',['Verdadero','Falso'],0,'Puede ser relevante en escenarios de contribuciones únicas y valiosas e integración.'),
q(16,'Toda marca genera automáticamente una regalía.',['Verdadero','Falso'],1,'La existencia de una marca no determina por sí sola una regalía.'),
q(17,'Un procedimiento técnico confidencial no patentado puede constituir know-how.',['Verdadero','Falso'],0,'La ausencia de patente no impide que exista know-how.'),
q(18,'El análisis de intangibles comienza y termina con documentos legales.',['Verdadero','Falso'],1,'Debe contrastarse con funciones, activos, riesgos y conducta económica.'),
q(19,'¿Qué distingue una licencia?',['Derecho de uso sin necesariamente transferir propiedad','Venta definitiva del activo','Servicio rutinario','Financiamiento'],0,'La licencia puede conceder uso manteniendo la propiedad.'),
q(20,'¿Qué distingue una transferencia?',['Cambio o cesión de derechos sobre el intangible','Sólo uso temporal','Servicio administrativo','Préstamo'],0,'Una transferencia implica cesión o cambio de derechos.'),
q(21,'HTVI significa que toda tecnología nueva debe ajustarse automáticamente.',['Verdadero','Falso'],1,'HTVI no aplica automáticamente a todo intangible novedoso.'),
q(22,'La ausencia de comparables puede llevar a considerar técnicas de valoración.',['Verdadero','Falso'],0,'Puede ser necesario considerar enfoques alternativos según los hechos.'),
q(23,'SS2 pretende formar valuadores completos.',['Verdadero','Falso'],1,'El objetivo es criterio conceptual, no una formación completa en valuación.'),
q(24,'HoldCo posee patente; R&D Co controla desarrollo y riesgo. ¿Basta la propiedad legal para asignar todo retorno?',['Sí','No'],1,'La titularidad legal por sí sola no basta.'),
q(25,'Una entidad usa marca bajo contrato temporal sin derecho de venta. La operación probable es:',['Licencia','Venta','Servicio financiero','Transferencia total'],0,'Los hechos apuntan a una licencia.'),
q(26,'Una entidad vende definitivamente derechos territoriales exclusivos. Puede existir transferencia parcial o total de derechos según hechos.',['Verdadero','Falso'],0,'La naturaleza depende del alcance de los derechos cedidos.'),
q(27,'Una empresa financia I+D pero no toma decisiones ni controla riesgos. ¿Financiamiento basta para justificar residual?',['Sí','No'],1,'El financiamiento no equivale automáticamente a control de riesgos ni a derecho al residual.'),
q(28,'¿Cuál es la mejor pregunta inicial sobre retornos de intangibles?',['Quién aparece en balance','Quién realiza funciones relevantes y controla riesgos','Quién tiene más empleados','Quién factura más'],1,'El análisis debe concentrarse en contribuciones y control de riesgos.'),
q(29,'¿Puede un intangible estar relacionado con marketing?',['Sí','No'],0,'Marcas y otros intangibles de marketing pueden ser relevantes.'),
q(30,'¿Por qué legal ownership no equivale a economic entitlement?',['Porque la propiedad legal es irrelevante','Porque los retornos deben ser consistentes con funciones, activos y riesgos, incluyendo DEMPE y control','Porque sólo importa el país','Porque siempre aplica Profit Split'],1,'La titularidad legal es un elemento, no la conclusión económica completa.')
];export const SS2_ATTEMPT_SIZE=12;export const SS2_PASS_SCORE=80;