export type SS3Question={id:number;prompt:string;options:string[];correctIndex:number;feedback:string};const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):SS3Question=>({id,prompt,options,correctIndex,feedback});export const ss3FinalBank:SS3Question[]=[
q(1,'DEMPE es:',['Un método de valoración','Un marco para analizar funciones relacionadas con intangibles','Una fórmula de regalías','Un requisito de una firma'],1,'DEMPE es un marco funcional, no un método de valoración.'),
q(2,'Development se relaciona principalmente con:',['Creación o desarrollo','Registro contable','Facturación','Auditoría'],0,'Development comprende la creación o desarrollo del intangible.'),
q(3,'Enhancement implica:',['Sólo mantenimiento rutinario','Mejoras significativas','Sólo protección legal','Financiamiento'],1,'Enhancement se refiere a mejoras que incrementan significativamente valor, funcionalidad o alcance.'),
q(4,'Maintenance busca principalmente:',['Crear desde cero','Conservar valor o funcionalidad','Transferir legalmente','Financiar'],1,'Maintenance conserva el valor o funcionalidad del intangible.'),
q(5,'Protection puede incluir registro y defensa de derechos.',['Verdadero','Falso'],0,'Protection puede comprender acciones jurídicas y operativas de protección.'),
q(6,'Exploitation se refiere al uso del intangible para generar valor económico.',['Verdadero','Falso'],0,'Exploitation analiza cómo el intangible se utiliza económicamente.'),
q(7,'Una entidad que ejecuta pruebas controla necesariamente el riesgo de desarrollo.',['Verdadero','Falso'],1,'Ejecución y control del riesgo deben distinguirse.'),
q(8,'¿Qué es relevante para control del riesgo?',['Capacidad real de decisión','Tamaño del logotipo','País únicamente','Número de facturas'],0,'El control exige capacidad y ejercicio de decisiones relevantes.'),
q(9,'Financiar desarrollo otorga automáticamente todos los retornos residuales.',['Verdadero','Falso'],1,'El financiamiento es una contribución distinta del control de funciones y riesgos.'),
q(10,'La propiedad legal es irrelevante.',['Verdadero','Falso'],1,'Es relevante, pero no determina por sí sola todos los retornos.'),
q(11,'Un mapa DEMPE debe analizar a las personas que toman decisiones.',['Verdadero','Falso'],0,'Las decisiones reales son centrales para evaluar control.'),
q(12,'¿Puede una misma entidad realizar varias funciones DEMPE?',['Sí','No'],0,'Una entidad puede realizar varias funciones.'),
q(13,'¿Puede una función DEMPE estar distribuida entre varias entidades?',['Sí','No'],0,'Una función puede distribuirse entre entidades según los hechos.'),
q(14,'Asignar 20% del retorno por cada letra DEMPE es apropiado.',['Verdadero','Falso'],1,'DEMPE no es una fórmula mecánica de reparto.'),
q(15,'Una mejora sustancial de software puede ser Enhancement.',['Verdadero','Falso'],0,'Una mejora material puede constituir Enhancement.'),
q(16,'Una actualización menor rutinaria puede ser Maintenance.',['Verdadero','Falso'],0,'El mantenimiento puede incluir actualizaciones rutinarias.'),
q(17,'Registrar una patente significa necesariamente controlar Protection estratégicamente.',['Verdadero','Falso'],1,'La ejecución administrativa debe distinguirse del control estratégico.'),
q(18,'¿Qué debe analizarse junto con DEMPE?',['FAR y riesgos','Sólo organigrama','Sólo contrato','Sólo contabilidad'],0,'DEMPE debe conectarse con FAR, riesgos y conducta.'),
q(19,'Si una entidad financia pero no controla riesgos técnicos, debe analizarse una remuneración coherente con su financiamiento y riesgo real.',['Verdadero','Falso'],0,'El retorno debe corresponder a la contribución y riesgo efectivamente asumido.'),
q(20,'Exploitation equivale siempre a distribución.',['Verdadero','Falso'],1,'La explotación puede adoptar múltiples formas y no se limita a distribución.'),
q(21,'Una entidad de marketing puede contribuir a Enhancement si aumenta materialmente el valor de una marca.',['Verdadero','Falso'],0,'La relevancia depende de la sustancia e importancia de la contribución.'),
q(22,'Para asignar retornos basta identificar quién ejecuta tareas.',['Verdadero','Falso'],1,'También importan decisiones, riesgos, activos, financiamiento e importancia económica.'),
q(23,'¿Qué tres preguntas resume La Silla del Consultor?',['Quién hace, quién decide y quién asume consecuencias económicas','Quién factura, quién registra y quién firma','Quién tiene más empleados, ventas y activos','Quién posee, licencia y factura'],0,'El mapa útil conecta ejecución, decisión y consecuencias económicas.'),
q(24,'HoldCo paga; TechCo decide I+D y tiene personal. ¿Quién parece controlar el riesgo técnico?',['HoldCo','TechCo','Ambas automáticamente','Nadie'],1,'Los hechos apuntan a TechCo por su capacidad y decisiones sobre I+D.'),
q(25,'LegalCo renueva marcas siguiendo instrucciones. ¿Realiza Protection?',['No','Sí, al menos ejecución; debe investigarse control estratégico','Controla necesariamente todo Protection','Sólo si es propietario'],1,'Puede ejecutar Protection sin controlar necesariamente la estrategia.'),
q(26,'LocalCo adapta tecnología y sus mejoras se usan globalmente. ¿Debe ignorarse por no ser propietario legal?',['Sí','No'],1,'La contribución económica debe analizarse independientemente de la titularidad legal.'),
q(27,'DEMPE sustituye al análisis de comparabilidad.',['Verdadero','Falso'],1,'DEMPE no sustituye comparabilidad.'),
q(28,'DEMPE sustituye a la selección de método.',['Verdadero','Falso'],1,'DEMPE no sustituye la selección del método más apropiado.'),
q(29,'Un análisis de retornos debe considerar la importancia económica de las contribuciones.',['Verdadero','Falso'],0,'No todas las funciones tienen el mismo peso económico.'),
q(30,'¿Por qué “quien paga” y “quien controla” no son necesariamente la misma entidad?',['Porque financiar y tomar decisiones/controlar riesgos son contribuciones distintas','Porque el pago nunca importa','Porque sólo importa la propiedad legal','Porque DEMPE elimina el análisis de riesgos'],0,'Financiamiento y control del riesgo deben analizarse separadamente.')
];export const SS3_ATTEMPT_SIZE=12;export const SS3_PASS_SCORE=80;