export type SS4Question={id:number;prompt:string;options:string[];correctIndex:number;feedback:string};const q=(id:number,prompt:string,options:string[],correctIndex:number,feedback:string):SS4Question=>({id,prompt,options,correctIndex,feedback});export const ss4FinalBank:SS4Question[]=[
q(1,'La primera pregunta en un préstamo intragrupo debe ser:',['Qué tasa usar','Qué operación existe y cuáles son sus condiciones','Qué base de datos usar','Qué rating produce menor spread'],1,'Primero se delimita la operación.'),
q(2,'Una transferencia documentada como préstamo siempre debe analizarse como deuda por el monto completo.',['Verdadero','Falso'],1,'Debe analizarse la sustancia económica y capacidad razonable de endeudamiento.'),
q(3,'Creditworthiness significa únicamente rating externo.',['Verdadero','Falso'],1,'Es una evaluación económica más amplia.'),
q(4,'Un plazo mayor puede afectar la tasa.',['Verdadero','Falso'],0,'El plazo es una condición económicamente relevante.'),
q(5,'La moneda es irrelevante si borrower y lender son relacionadas.',['Verdadero','Falso'],1,'La moneda puede afectar referencia, riesgo y comparabilidad.'),
q(6,'Una garantía puede afectar el riesgo y la tasa.',['Verdadero','Falso'],0,'Puede reducir la exposición del acreedor.'),
q(7,'La subordinación puede aumentar el riesgo del prestamista.',['Verdadero','Falso'],0,'Menor prioridad de cobro puede elevar el riesgo.'),
q(8,'Una tasa de referencia por sí sola siempre representa plena competencia.',['Verdadero','Falso'],1,'Puede ser sólo un componente del precio financiero.'),
q(9,'¿Cuál es factor de crédito?',['Flujo de efectivo','Leverage','Liquidez','Todas las anteriores'],3,'Todos pueden ser relevantes.'),
q(10,'El lender debe analizarse también desde control del riesgo.',['Verdadero','Falso'],0,'La provisión de fondos no basta para demostrar control.'),
q(11,'Un CUP financiero requiere comparar condiciones económicamente relevantes.',['Verdadero','Falso'],0,'Crédito, moneda, plazo, seniority, garantías y fecha importan.'),
q(12,'Mismo borrower significa misma tasa para todos los préstamos.',['Verdadero','Falso'],1,'Los términos pueden justificar precios distintos.'),
q(13,'Una deuda a 1 año y otra a 8 años pueden diferir en precio.',['Verdadero','Falso'],0,'El plazo puede modificar riesgo y referencia.'),
q(14,'¿Qué variable no debe ignorarse?',['Fecha','Moneda','Seniority','Ninguna de las anteriores'],3,'Todas deben considerarse cuando sean relevantes.'),
q(15,'Si el borrower no puede razonablemente pagar el monto, buscar un spread resuelve el problema.',['Verdadero','Falso'],1,'Debe revisarse primero la delimitación económica de la financiación.'),
q(16,'Un préstamo garantizado puede tener distinto riesgo que uno no garantizado.',['Verdadero','Falso'],0,'La garantía puede modificar la exposición del prestamista.'),
q(17,'La capacidad de repago es relevante para delimitar.',['Verdadero','Falso'],0,'Es central para evaluar la naturaleza y monto de la deuda.'),
q(18,'El propósito del financiamiento puede ser relevante.',['Verdadero','Falso'],0,'El uso de fondos forma parte de la delimitación.'),
q(19,'Una emisión de bono puede servir como referencia potencial si es comparable.',['Verdadero','Falso'],0,'Puede ser una referencia observable si la comparabilidad es suficiente.'),
q(20,'Un comparable interno debe analizarse antes de asumir que es fiable.',['Verdadero','Falso'],0,'La condición de interno no elimina diferencias relevantes.'),
q(21,'“Reference rate + spread” es en SS4:',['Regla legal','Concepto pedagógico','Fórmula universal','Porcentaje obligatorio'],1,'Es una representación conceptual.'),
q(22,'Un spread de crédito debe reflejar, entre otros, riesgo y términos.',['Verdadero','Falso'],0,'El spread no es independiente de las características económicas.'),
q(23,'La legislación local puede contener reglas adicionales sobre deuda/capital.',['Verdadero','Falso'],0,'SS4 distingue análisis TP de reglas jurídicas locales.'),
q(24,'La Academy enseña una regla universal de thin capitalization.',['Verdadero','Falso'],1,'Las reglas locales quedan fuera del core curriculum.'),
q(25,'Seniority describe principalmente:',['Prioridad de cobro respecto de otros acreedores','Moneda del préstamo','Monto principal','Fecha de contrato'],0,'Seniority se refiere a prelación.'),
q(26,'Collateral describe principalmente:',['Activo o soporte específico que reduce exposición del acreedor','Spread fijo','Plazo','Rating'],0,'Es garantía o colateral.'),
q(27,'Borrower estable, 5 años USD, sin garantía. Antes de buscar comparables se debe:',['Delimitar términos y evaluar crédito','Escoger la tasa más baja','Usar sólo una tasa base','Ignorar seniority'],0,'La delimitación y el análisis de crédito preceden al benchmark.'),
q(28,'Mismo préstamo pero con garantía sólida. ¿Puede cambiar la tasa?',['Sí','No'],0,'La garantía puede modificar el riesgo.'),
q(29,'Prestatario con flujo insuficiente para servir deuda. ¿Debe analizarse sólo tasa?',['Sí','No, también monto y naturaleza de financiación'],1,'La capacidad de endeudamiento forma parte de la delimitación.'),
q(30,'¿Cuál conjunto contiene variables de comparabilidad de un préstamo?',['Monto, plazo, moneda, fecha, creditworthiness y garantía','Sólo monto y tasa','Sólo rating','Sólo moneda y país'],0,'El análisis requiere múltiples características económicamente relevantes.')
];export const SS4_ATTEMPT_SIZE=12;export const SS4_PASS_SCORE=80;