export type ConsultantDomain='C1'|'C2'|'C3'|'C4'|'C5'|'C6'|'C7';
export type ConsultantQuestion={id:number;domain:ConsultantDomain;prompt:string;options:string[];correctIndex:number;feedback:string};
const q=(id:number,domain:ConsultantDomain,prompt:string,options:string[],correctIndex:number,feedback:string):ConsultantQuestion=>({id,domain,prompt,options,correctIndex,feedback});
export const consultantBank:ConsultantQuestion[]=[
q(1,'C1','La delimitación precisa debe partir principalmente de:',['Contrato','Conducta','Hechos, contrato y conducta analizados conjuntamente','Método'],2,'La delimitación integra hechos, contrato y conducta.'),
q(2,'C1','Si contrato y conducta difieren materialmente, debe prevalecer automáticamente el contrato.',['Verdadero','Falso'],1,'La conducta efectiva debe investigarse y contrastarse.'),
q(3,'C1','Una operación debe delimitarse antes de seleccionar el método.',['Verdadero','Falso'],0,'La secuencia técnica exige comprender primero la operación.'),
q(4,'C1','El análisis de riesgo requiere considerar control y capacidad financiera.',['Verdadero','Falso'],0,'Ambos elementos son relevantes.'),
q(5,'C1','La etiqueta “servicio” es suficiente para delimitar una operación.',['Verdadero','Falso'],1,'Las etiquetas no sustituyen los hechos.'),
q(6,'C1','Una descripción precisa debe identificar FAR y condiciones económicamente relevantes.',['Verdadero','Falso'],0,'Es parte central de la delimitación.'),
q(7,'C1','Contrato: A asume inventario; conducta: B decide compras, administra inventario y absorbe pérdidas. ¿Qué procede?',['Aceptar el contrato','Investigar la asignación contractual','Ignorar la conducta','Elegir TNMM'],1,'Debe investigarse la asignación real del riesgo.'),
q(8,'C2','“Aplicable” y “más apropiado” significan lo mismo.',['Verdadero','Falso'],1,'Un método puede ser aplicable sin ser el más confiable.'),
q(9,'C2','Un CUP interno altamente comparable puede merecer prioridad sobre TNMM.',['Verdadero','Falso'],0,'La confiabilidad relativa puede favorecer CUP.'),
q(10,'C2','La selección del método depende de naturaleza de operación, datos y comparabilidad.',['Verdadero','Falso'],0,'Es una decisión basada en hechos y calidad de información.'),
q(11,'C2','La tested party debe elegirse por tamaño.',['Verdadero','Falso'],1,'Se elige típicamente por menor complejidad y disponibilidad de comparables confiables.'),
q(12,'C2','Profit Split puede ser relevante cuando ambas partes aportan contribuciones únicas y valiosas.',['Verdadero','Falso'],0,'Es una situación donde puede ganar confiabilidad.'),
q(13,'C2','“Usamos TNMM porque siempre se usa para distribuidores” es justificación suficiente.',['Verdadero','Falso'],1,'La selección requiere razonamiento específico.'),
q(14,'C2','Existe venta casi idéntica a tercero con diferencias cuantificables de flete. Primera alternativa a investigar:',['TNMM','Profit Split','CUP interno','RPM automático'],2,'Un comparable interno cercano merece evaluación prioritaria.'),
q(15,'C3','Operating Margin normalmente relaciona utilidad operativa con ventas.',['Verdadero','Falso'],0,'Es la relación conceptual usual.'),
q(16,'C3','Mark-up on Costs normalmente relaciona utilidad operativa con una base de costos.',['Verdadero','Falso'],0,'Ese es su denominador económico.'),
q(17,'C3','Berry Ratio es lo mismo que operating margin.',['Verdadero','Falso'],1,'Son indicadores distintos.'),
q(18,'C3','ROA puede ser relevante cuando los activos operativos son una base económica significativa.',['Verdadero','Falso'],0,'El PLI debe reflejar la forma de generación de valor.'),
q(19,'C3','La clasificación operativo/no operativo puede afectar el PLI.',['Verdadero','Falso'],0,'La clasificación financiera impacta el numerador/denominador.'),
q(20,'C3','Segmentación financiera irrelevante puede distorsionar el resultado.',['Verdadero','Falso'],0,'La segmentación debe corresponder a la operación analizada.'),
q(21,'C3','Ventas 1,000; utilidad operativa 60. Operating Margin:',['3%','6%','10%','16%'],1,'60/1,000 = 6%.'),
q(22,'C3','Costos 800; utilidad operativa 80. Mark-up on Costs:',['8%','10%','12%','20%'],1,'80/800 = 10%.'),
q(23,'C3','Si gross profit=250 y gastos operativos=200, Berry Ratio simplificado:',['0.8','1.0','1.25','2.0'],2,'250/200 = 1.25 bajo los hechos indicados.'),
q(24,'C3','Una pérdida operativa implica automáticamente incumplimiento arm\'s length.',['Verdadero','Falso'],1,'Una pérdida requiere análisis de hechos y comparabilidad.'),
q(25,'C4','Una empresa se acepta porque su margen cae cerca de la mediana.',['Verdadero','Falso'],1,'Accept/Reject se basa en comparabilidad, no en resultado.'),
q(26,'C4','Accept/Reject debe basarse en comparabilidad y calidad de información.',['Verdadero','Falso'],0,'Es la regla central de selección.'),
q(27,'C4','La similitud de actividad por sí sola siempre es suficiente.',['Verdadero','Falso'],1,'Debe revisarse FAR y demás factores.'),
q(28,'C4','Intangibles únicos pueden justificar rechazo frente a una parte rutinaria.',['Verdadero','Falso'],0,'Pueden introducir diferencias materiales.'),
q(29,'C4','Si la información es insuficiente, REVIEW puede ser más adecuado.',['Verdadero','Falso'],0,'No debe forzarse una decisión sin evidencia.'),
q(30,'C4','Un comparable interno requiere evaluar diferencias materiales.',['Verdadero','Falso'],0,'Interno no significa automáticamente comparable.'),
q(31,'C4','Empresa manufactura, diseña, patenta y explota marca; tested party es fabricante rutinario sin intangibles.',['ACCEPT','REJECT','REVIEW por margen','ACCEPT si es misma industria'],1,'El perfil funcional e intangibles son incompatibles.'),
q(32,'C5','Todo diferencial observado exige ajuste.',['Verdadero','Falso'],1,'Deben evaluarse materialidad y confiabilidad.'),
q(33,'C5','Un ajuste sólo debe realizarse si mejora razonablemente comparabilidad.',['Verdadero','Falso'],0,'El ajuste es una herramienta de confiabilidad.'),
q(34,'C5','Working capital puede considerar CxC, CxP e inventarios.',['Verdadero','Falso'],0,'Son componentes típicos de la lógica de capital de trabajo.'),
q(35,'C5','Existe una fórmula universal de working capital aceptada por todas las firmas.',['Verdadero','Falso'],1,'Las metodologías pueden variar.'),
q(36,'C5','PP&E puede ser relevante ante diferencias materiales en intensidad de activos.',['Verdadero','Falso'],0,'La intensidad de capital puede afectar rentabilidad esperada.'),
q(37,'C5','Si el ajuste introduce más incertidumbre que la diferencia, puede ser preferible no ajustar.',['Verdadero','Falso'],0,'La confiabilidad prima sobre sofisticación.'),
q(38,'C5','Las fórmulas de la Academy deben presentarse como ejemplos didácticos, no estándar universal.',['Verdadero','Falso'],0,'Es una regla pedagógica expresa.'),
q(39,'C6','El rango organiza resultados de comparables previamente considerados razonablemente confiables.',['Verdadero','Falso'],0,'El rango no crea comparabilidad.'),
q(40,'C6','La mediana convierte automáticamente cualquier resultado fuera de rango en incumplimiento legal.',['Verdadero','Falso'],1,'La consecuencia jurídica depende de la normativa aplicable.'),
q(41,'C6','Q1 y Q3 pueden variar según la convención estadística.',['Verdadero','Falso'],0,'Distintas convenciones pueden producir resultados distintos.'),
q(42,'C6','Debe eliminarse un comparable por ser outlier si su margen es incómodo.',['Verdadero','Falso'],1,'Eso sería cherry-picking sin fundamento independiente.'),
q(43,'C6','Si el resultado cae dentro del rango definido, puede ser consistente con plena competencia bajo el análisis.',['Verdadero','Falso'],0,'Es la conclusión económica básica bajo ese rango.'),
q(44,'C7','EPT y Local File son sinónimos universales.',['Verdadero','Falso'],1,'Pueden compartir contenido, pero no son equivalentes universalmente.'),
q(45,'C7','Master File ofrece una visión global del grupo.',['Verdadero','Falso'],0,'Su perspectiva es global.'),
q(46,'C7','CbCR sustituye el análisis transaccional de TP.',['Verdadero','Falso'],1,'Es una herramienta agregada de transparencia/riesgo.'),
q(47,'C7','La consistencia entre documentos es relevante.',['Verdadero','Falso'],0,'Los hechos y narrativa deben ser compatibles.'),
q(48,'C7','Que una jurisdicción concentre utilidades en CbCR prueba por sí mismo un ajuste de TP.',['Verdadero','Falso'],1,'El dato agregado no sustituye hechos, FAR y análisis.')
];
export const consultantAttemptPlan:Record<ConsultantDomain,number>={C1:4,C2:4,C3:5,C4:4,C5:2,C6:2,C7:3};
export const CONSULTANT_PASS_SCORE=80;
export const CONSULTANT_DOMAIN_FLOOR=60;

export type PractitionerCaseQuestion={id:string;domain:string;prompt:string;options:string[];correct:number[];explanation:string};
export const CONSULTANT_CASE_PASS_SCORE=80;
export const practitionerCaseQuestions:PractitionerCaseQuestion[]=[
{id:'case-1',domain:'Delimitación',prompt:'Considerando contrato y conducta consistentes, ¿cuál es la delimitación más sólida?',options:['Manufacturas del Bajío explota intangibles técnicos y controla la estrategia comercial.','Manufacturas del Bajío presta manufactura intragrupo relativamente rutinaria conforme a especificaciones y estrategia controladas por la relacionada.','Ambas partes aportan intangibles únicos y deben compartir utilidades.','La operación se delimita únicamente como venta de componentes porque así se factura.'],correct:[1],explanation:'Los hechos muestran manufactura rutinaria, activos ordinarios y ausencia de intangibles únicos en Manufacturas del Bajío; la relacionada controla diseño, intangibles y estrategia.'},
{id:'case-2',domain:'Tested party',prompt:'¿Qué parte es la candidata más razonable a tested party?',options:['La relacionada porque posee los intangibles más valiosos.','Manufacturas del Bajío porque es la parte menos compleja y existen comparables de fabricantes por contrato.','La empresa con mayores ventas.','No puede existir tested party bajo TNMM.'],correct:[1],explanation:'La tested party suele ser la parte menos compleja para la que puede aplicarse el método de forma confiable.'},
{id:'case-3',domain:'Método',prompt:'¿Qué conclusión sobre método y PLI está mejor sustentada por los hechos?',options:['CUP, porque los métodos tradicionales tienen prioridad jerárquica.','Cost Plus con margen bruto, porque toda manufactura debe analizarse así.','TNMM sobre Manufacturas del Bajío con Operating Margin, dada la disponibilidad de márgenes operativos comparables y las limitaciones de CUP y margen bruto.','Profit Split, porque siempre es preferible cuando existen intangibles en el grupo.'],correct:[2],explanation:'La confiabilidad relativa favorece TNMM con Operating Margin bajo los hechos proporcionados.'},
{id:'case-4',domain:'Método',prompt:'Selecciona TODAS las razones sustentadas por los hechos para considerar menos confiables CUP y Cost Plus.',options:['No existe una venta interna suficientemente comparable para CUP.','Los datos públicos de margen bruto presentan inconsistencias importantes de clasificación contable.','TNMM siempre tiene prioridad sobre CUP y Cost Plus.','Manufacturas del Bajío tiene un margen de 5.9%.'],correct:[0,1],explanation:'Las limitaciones provienen de comparabilidad y calidad de datos, no de una jerarquía automática ni del resultado observado.'},
{id:'case-5',domain:'Proceso',prompt:'¿Cuál es la secuencia conceptual correcta?',options:['Método → rango → delimitación → comparables.','Delimitación/FAR → tested party y método/PLI → comparables → ajustes si mejoran confiabilidad → rango → documentación.','Comparables → mediana → método → FAR.','Rango → ajuste → delimitación → método.'],correct:[1],explanation:'La evaluación integra la cadena de razonamiento desarrollada en C1–C7.'},
{id:'case-6',domain:'Comparabilidad',prompt:'¿Qué papel cumplen los siete comparables identificados?',options:['Crean comparabilidad porque generan un rango.','Proporcionan referencias independientes razonablemente confiables después del proceso de búsqueda y evaluación.','Son válidos sólo porque sus márgenes rodean 5.9%.','Eliminan la necesidad de analizar diferencias económicas.'],correct:[1],explanation:'El rango organiza resultados de comparables previamente evaluados; no crea comparabilidad.'},
{id:'case-7',domain:'Ajustes',prompt:'Al observar mayores cuentas por cobrar e inventarios en algunos comparables, ¿qué debe hacerse primero?',options:['Aplicar automáticamente la fórmula propia de la firma.','Ajustar hasta que la mediana coincida con 5.9%.','Evaluar si las diferencias son materiales y si un ajuste razonablemente fiable mejora la comparabilidad.','Excluir automáticamente a todos esos comparables.'],correct:[2],explanation:'C5 exige existencia, materialidad y confiabilidad antes de ajustar.'},
{id:'case-8',domain:'Ajustes',prompt:'Selecciona TODAS las afirmaciones técnicamente consistentes sobre working capital.',options:['CxC, CxP e inventarios pueden reflejar diferencias de financiamiento operativo.','La metodología utilizada debe explicarse y documentarse.','La Academy prescribe una fórmula universal obligatoria.','Si el ajuste introduce más incertidumbre que la diferencia, puede ser preferible no ajustar.'],correct:[0,1,3],explanation:'La Academy enseña la lógica económica y no prescribe una fórmula universal.'},
{id:'case-9',domain:'Rango',prompt:'IQR 3.8%–7.2%, mediana 5.4%, resultado 5.9%. ¿Cuál es la interpretación correcta?',options:['Debe ajustarse a 5.4% porque todo resultado debe igualar la mediana.','Está dentro del rango y, bajo los hechos y metodología proporcionados, es consistente con el rango de plena competencia.','Incumple porque está por encima de la mediana.','El rango no puede utilizarse con TNMM.'],correct:[1],explanation:'Estar dentro del rango definido puede ser consistente con plena competencia bajo el análisis realizado.'},
{id:'case-10',domain:'Revisión técnica',prompt:'Un consultor escribe: “Como 5.9% supera la mediana de 5.4%, debe ajustarse a la mediana”. ¿Cuál es el problema principal?',options:['No calculó Q1.','Confunde la mediana con un objetivo obligatorio pese a que el resultado está dentro del rango.','Debió usar Profit Split.','Debió eliminar el comparable con margen más alto.'],correct:[1],explanation:'La mediana no convierte automáticamente los demás resultados dentro del rango en incumplimiento.'},
{id:'case-11',domain:'Documentación',prompt:'Selecciona TODOS los elementos que deberían conectarse coherentemente en el EPT/Local File de este caso.',options:['Hechos y FAR.','Delimitación y selección de método/PLI.','Búsqueda y evaluación de comparables, ajustes y rango.','Conclusión y limitaciones relevantes.','Sólo la tabla final del rango.'],correct:[0,1,2,3],explanation:'La documentación debe mostrar una cadena coherente entre hechos, análisis y conclusión.'},
{id:'case-12',domain:'Revisión técnica',prompt:'¿Cuál es la conclusión integral más defendible?',options:['El 5.9% prueba por sí solo plena competencia y vuelve innecesaria la documentación.','TNMM/Operating Margin sobre Manufacturas del Bajío es razonable bajo los hechos; los comparables y posibles ajustes deben sustentarse; 5.9% está dentro del rango y la conclusión debe documentarse coherentemente.','Cost Plus debe utilizarse porque Manufacturas del Bajío fabrica.','Debe aplicarse un working capital adjustment aunque no se demuestre materialidad.'],correct:[1],explanation:'Esta opción integra delimitación, método, comparabilidad, ajustes, rango y documentación sin introducir reglas no soportadas.'}
];

export const practitionerCaseFacts='Manufacturas del Bajío produce componentes industriales para una entidad relacionada que diseña el producto, posee intangibles técnicos y define estrategia comercial. Manufacturas del Bajío ejecuta manufactura rutinaria, utiliza activos productivos ordinarios y no desarrolla intangibles únicos. El contrato establece que la relacionada controla decisiones estratégicas y asume riesgo de mercado; la conducta observada es consistente con ello. No existe una venta interna comparable suficientemente similar para CUP. Los datos públicos de margen bruto presentan inconsistencias importantes de clasificación contable. Existe información confiable de margen operativo para fabricantes por contrato funcionalmente comparables. Se identifican siete comparables razonablemente confiables; IQR 3.8%–7.2%, mediana 5.4%. Manufacturas del Bajío obtiene Operating Margin de 5.9%. Algunos comparables tienen mayores cuentas por cobrar e inventarios y la firma utiliza una metodología propia de working capital adjustment.';
