import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { c1Lessons } from '../content/curriculum/v1/c1';
import { c1Assessments } from '../content/curriculum/v1/c1Assessments';
import { markCourseLessonCompleted, markCourseLessonVisited } from '../services/courseProgress';

const lessonBodies = [
  { heading: 'La operación económica se reconstruye; no se adivina por su nombre', paragraphs: ['Una operación controlada no debe describirse sólo por su etiqueta jurídica. “Venta”, “servicio”, “préstamo” o “licencia” son puntos de partida, no conclusiones.', 'Para delimitar una operación debes entender qué se entrega, quién hace qué, qué activos se utilizan, qué riesgos se asumen y controlan, qué términos se pactaron, qué ocurre en la práctica y bajo qué circunstancias económicas.'], example: 'Un contrato llama a una entidad “distribuidor de riesgo limitado”, pero esa entidad define precios, selecciona clientes, decide inventarios, asume obsolescencia y ejecuta campañas relevantes. La etiqueta contractual no basta.', chair: 'Primero describe hechos; después asigna etiquetas.', remember: 'Una delimitación sólida empieza por los hechos y termina en una descripción económica coherente.' },
  { heading: 'El contrato dice qué debía pasar; la conducta ayuda a ver qué pasó', paragraphs: ['Los contratos son una fuente importante de información porque expresan las condiciones previstas por las partes. El análisis debe verificar si la conducta es consistente con esos términos.', 'Cuando contrato y conducta coinciden, el contrato puede describir adecuadamente la operación. Cuando difieren, los hechos pueden revelar que la operación económica es distinta de la que aparenta el documento.'], example: 'Un contrato prevé soporte administrativo mensual, pero la entidad prestadora no tiene empleados, no contrata terceros y no existe evidencia del servicio. La existencia del contrato no prueba por sí sola que el servicio ocurrió.', chair: 'Un contrato te dice qué debía pasar. El análisis funcional te ayuda a entender qué pasó.', remember: 'Contrato y conducta deben analizarse juntos, no como fuentes aisladas.' },
  { heading: 'No todas las condiciones pesan igual en todas las operaciones', paragraphs: ['La delimitación precisa requiere identificar características económicamente relevantes. Las cinco categorías principales son términos contractuales; funciones, activos y riesgos; características del bien, servicio o activo; circunstancias económicas; y estrategias empresariales.', 'La relevancia depende del tipo de operación y de aquello que puede afectar sus condiciones de plena competencia.'], example: 'En un préstamo importan monto, moneda, plazo, garantía, subordinación y solvencia. En distribución pesan especialmente FAR, mercado, producto y funciones comerciales.', chair: 'No conviertas la lista de factores en un checklist mecánico: identifica cuáles explican realmente la economía de la operación.', remember: 'La delimitación precisa exige seleccionar factores relevantes, no acumular información indiscriminadamente.' },
  { heading: 'Asignar un riesgo en papel no equivale a controlarlo', paragraphs: ['Para que una asignación de riesgo sea económicamente consistente debe existir capacidad real para controlar ese riesgo y capacidad financiera para asumirlo.', 'En términos prácticos, debes identificar quién toma decisiones relevantes sobre aceptar, evitar o mitigar el riesgo y quién soporta sus consecuencias económicas.'], example: 'La matriz declara que la subsidiaria asume riesgo de inventario, pero la matriz decide cuánto producir, cuánto enviar y cuándo retirar producto obsoleto. La asignación contractual debe cuestionarse.', chair: 'Pregunta quién decide, quién puede decidir y quién soporta el efecto económico de esas decisiones.', remember: 'Pagar una pérdida no demuestra por sí solo control del riesgo.' },
  { heading: 'La delimitación debe terminar en una descripción económica', paragraphs: ['Una buena delimitación no se queda en una categoría jurídica genérica. Debe expresar qué actividad económica se realiza y qué perfil funcional sostiene esa conclusión.', 'La descripción debe ser suficientemente específica para conectar después con caracterización, comparabilidad y método.'], example: '“Compra-venta con parte relacionada” es débil. “Adquisición recurrente de producto terminado para distribución local por una entidad que realiza funciones rutinarias de venta y mantiene inventario limitado” es mucho más útil.', chair: 'Una buena descripción económica permite que otro profesional entienda el caso sin tener que adivinar qué quisiste decir.', remember: 'La precisión de la caracterización depende de la precisión de la delimitación.' },
  { heading: 'Los mismos nombres pueden esconder perfiles económicos distintos', paragraphs: ['La delimitación y la caracterización están conectadas. Si cambian los hechos, puede cambiar la forma de entender la operación aun cuando la etiqueta contractual permanezca.', 'Esto es especialmente relevante cuando aparecen funciones estratégicas, intangibles, decisiones relevantes o riesgos que antes no estaban presentes.'], example: 'Dos entidades son “distribuidores”, pero una sólo ejecuta instrucciones y la otra decide estrategia, incurre en publicidad significativa y asume riesgo comercial amplio. La etiqueta es la misma; la caracterización económica no.', chair: 'No permitas que una palabra contractual congele un análisis que los hechos ya cambiaron.', remember: 'Caracterización es consecuencia de hechos, no de nomenclatura.' },
  { heading: 'Una delimitación útil debe ser breve, clara y verificable', paragraphs: ['Una estructura práctica incluye: partes; naturaleza de la operación; bien, servicio o activo; funciones principales; activos relevantes; riesgos y quién los controla; términos económicos relevantes; y conclusión sobre la operación efectivamente realizada.', 'El objetivo no es escribir más, sino conectar los hechos que justifican la conclusión.'], example: 'Manufacturas del Bajío produce componentes y los vende a una distribuidora relacionada. La manufacturera realiza producción y control de calidad, utiliza planta y maquinaria y asume riesgos operativos; la distribuidora realiza funciones rutinarias de comercialización. La operación delimitada es una venta recurrente de producto terminado entre fabricante y distribuidor relacionado.', chair: 'Si tu delimitación no puede verificarse contra hechos concretos, todavía es una narrativa, no una conclusión técnica.', remember: 'Claridad, economía de lenguaje y trazabilidad a los hechos son parte de la calidad técnica.' },
  { heading: 'El método viene después de entender la operación', paragraphs: ['La secuencia correcta es hechos → delimitación → caracterización → método. Seleccionar metodología antes de entender la operación invierte el razonamiento.', 'C1 no busca resolver todavía casos metodológicos complejos; busca garantizar que el método futuro se aplique a la operación correcta.'], example: 'Una prestación rutinaria de servicios puede hacer conceptualmente relevante Cost Plus; una distribución rutinaria puede llevar a considerar RPM o TNMM; un comparable interno altamente confiable puede hacer preferible CUP.', chair: 'No busques el método que “funcione” con el resultado. Identifica primero qué operación estás intentando probar.', remember: 'Una metodología técnicamente correcta aplicada a la operación equivocada sigue siendo un análisis equivocado.' },
];

export function C1LessonPage() {
  const unlocked = typeof window !== 'undefined' && window.localStorage.getItem('tp-consultant-level-unlocked') === 'true';
  const { lessonNumber } = useParams();
  const sequence = Number(lessonNumber);
  const lesson = c1Lessons.find((item) => item.sequence === sequence);
  useEffect(() => { if (lesson && unlocked) markCourseLessonVisited('C1', lesson.sequence, c1Lessons.length); }, [lesson, unlocked]);
  if (!unlocked) return <Navigate to="/path" replace />;
  if (!lesson || !Number.isInteger(sequence)) return <Navigate to="/courses/c1" replace />;

  const body = lessonBodies[sequence - 1];
  const assessment = c1Assessments.find((item) => item.lesson === sequence);
  const previous = sequence > 1 ? sequence - 1 : null;
  const next = sequence < c1Lessons.length ? sequence + 1 : null;
  const lessonPercent = Math.round((sequence / c1Lessons.length) * 100);
  const check = assessment ? { id: `c1-check-${sequence}`, title: `Lección ${sequence} · Comprobación`, prompt: assessment.prompt, correctOptionId: `option-${assessment.correctIndex}`, options: assessment.options.map((label, index) => ({ id: `option-${index}`, label, feedback: index === assessment.correctIndex ? assessment.feedback : 'Contrasta tu respuesta con los hechos y el razonamiento de la lección antes de volver a intentarlo.' })) } : null;

  return <>
    <div className="lesson-topbar"><div className="container"><Link to="/courses/c1">← C1 · Delimitación Precisa de Operaciones</Link><span>Lección {sequence} de {c1Lessons.length}</span></div></div>
    <div className="lesson-progress-shell" aria-label={`Progreso de la lección ${sequence} de ${c1Lessons.length}`}><div className="container lesson-progress-inner"><strong>{sequence}/{c1Lessons.length}</strong><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={lessonPercent}><span style={{ width: `${lessonPercent}%` }} /></div><span>{lessonPercent}% de C1 recorrido</span></div></div>
    <article className="lesson-content"><div className="eyebrow">Consultant · C1 · Lección {sequence}</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min · Lección {sequence} de {c1Lessons.length}</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map((item) => <li key={item}>{item}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check && <FormativeCheck check={check} onCorrect={() => markCourseLessonCompleted('C1', sequence, c1Lessons.length)} />}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav" aria-label="Navegación entre lecciones">{previous ? <Link className="button secondary" to={`/courses/c1/lesson/${previous}`}>← Lección anterior</Link> : <span />}{next ? <Link className="button primary" to={`/courses/c1/lesson/${next}`}>Siguiente lección →</Link> : <Link className="button primary" to="/courses/c1">Volver al curso</Link>}</nav></article>
  </>;
}
