import { FormEvent, useState } from 'react';
import { Link } from 'react-router-dom';
import { C2_ATTEMPT_SIZE,C2_PASS_SCORE,C2Question,c2FinalBank } from '../content/assessments/c2Final';
import { c2Lessons } from '../content/curriculum/v1/c2';
import { getCourseProgress } from '../services/courseProgress';
const RESULT_KEY='tp-c2-final-result'; const C3_UNLOCK_KEY='tp-c3-unlocked';
function shuffle<T>(items:T[]){const r=[...items];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
function makeAttempt(){return shuffle(c2FinalBank).slice(0,C2_ATTEMPT_SIZE);}
export function C2AssessmentPage(){
 const eligible=getCourseProgress('C2',c2Lessons.length).completedLessons.length===c2Lessons.length;
 const [questions,setQuestions]=useState<C2Question[]>(()=>makeAttempt()); const [answers,setAnswers]=useState<Record<number,number>>({}); const [result,setResult]=useState<{score:number;correct:number;passed:boolean}|null>(null); const answered=Object.keys(answers).length;
 function grade(e:FormEvent){e.preventDefault();if(answered!==questions.length)return;const correct=questions.filter(q=>answers[q.id]===q.correctIndex).length;const score=Math.round(correct/questions.length*100);const passed=score>=C2_PASS_SCORE;setResult({score,correct,passed});localStorage.setItem(RESULT_KEY,JSON.stringify({score,correct,passed,completedAt:new Date().toISOString()}));if(passed)localStorage.setItem(C3_UNLOCK_KEY,'true');window.scrollTo({top:0,behavior:'smooth'});}
 function retry(){setQuestions(makeAttempt());setAnswers({});setResult(null);window.scrollTo({top:0,behavior:'smooth'});}
 if(!eligible)return <section className="section"><div className="container narrow"><div className="eyebrow">Evaluación final · C2</div><h1>Completa primero las 8 lecciones</h1><p className="lead small">La evaluación final se habilita después de completar las comprobaciones formativas de C2.</p><Link className="button primary" to="/courses/c2">Volver a C2</Link></div></section>;
 if(result)return <section className="section"><div className="container narrow assessment-result"><div className="eyebrow">Consultant · C2</div><h1>{result.passed?'C2 aprobado':'Aún no alcanzas el dominio requerido'}</h1><div className="result-score"><strong>{result.score}%</strong><span>{result.correct} de {questions.length} respuestas correctas</span></div>{result.passed?<><p>Superaste el 80% requerido. Has completado Selección del Método Más Apropiado y queda habilitada la progresión hacia C3 — TNMM / MTUO en la práctica.</p><div className="button-row"><Link className="button primary" to="/path">Continuar mi ruta</Link><Link className="button secondary" to="/courses/c2">Revisar C2</Link></div></>:<><p>Revisa especialmente confiabilidad relativa, comparables internos, tested party y justificación de alternativas. Los intentos son ilimitados.</p><button className="button primary" type="button" onClick={retry}>Intentar de nuevo</button></>}</div></section>;
 return <section className="section assessment-page"><div className="container narrow"><div className="eyebrow">Cierre de C2</div><h1>Evaluación Final — Selección del Método Más Apropiado</h1><p className="lead small">12 reactivos aleatorios del banco de 30. Necesitas 80% para aprobar. Los intentos son ilimitados.</p><div className="assessment-progress"><strong>{answered} / {questions.length}</strong><span>respondidas</span></div><form onSubmit={grade}>{questions.map((question,index)=><fieldset className="assessment-question" key={question.id}><legend><span>{index+1}</span>{question.prompt}</legend>{question.options.map((option,optionIndex)=><label className="assessment-option" key={option}><input type="radio" name={`question-${question.id}`} checked={answers[question.id]===optionIndex} onChange={()=>setAnswers(c=>({...c,[question.id]:optionIndex}))}/><span>{option}</span></label>)}</fieldset>)}<button className="button primary assessment-submit" type="submit" disabled={answered!==questions.length}>Calificar evaluación</button></form></div></section>;
}
