import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { c2Lessons } from '../content/curriculum/v1/c2';
import { c2Assessments } from '../content/curriculum/v1/c2Assessments';
import { markCourseLessonCompleted, markCourseLessonVisited } from '../services/courseProgress';

const lessonBodies = [
  { heading:'Aplicable no significa más apropiado', paragraphs:['La selección del método no comienza por facilidad, costumbre o resultado deseado. Comienza con la operación delimitada y pregunta qué método permite observarla con mayor confiabilidad.','Puede existir más de una alternativa técnicamente imaginable. La tarea profesional consiste en comparar su relación con los hechos, la calidad de los datos y las diferencias que afectan la comparación.'], example:'Dos métodos pueden calcularse, pero uno depende de datos débiles y el otro de información directamente comparable. La capacidad de cálculo no los vuelve equivalentes.', chair:'No preguntes “¿qué método podemos correr?”. Pregunta “¿qué método prueba mejor esta operación?”.', remember:'La selección es un juicio de confiabilidad relativa.' },
  { heading:'El método debe corresponder a la economía de la operación', paragraphs:['La delimitación y el FAR determinan qué métodos merecen consideración. Debes entender qué se transfiere, qué hace cada parte, qué activos utiliza, qué riesgos controla y si existen contribuciones únicas y valiosas.','Las conexiones entre tipo de operación y método son hipótesis de trabajo, no reglas automáticas.'], example:'Un producto idéntico vendido a terceros puede orientar a CUP; manufactura rutinaria puede hacer plausible Cost Plus; una parte menos compleja con datos netos comparables puede hacer viable TNMM.', chair:'Usa la caracterización para orientar la investigación, nunca para saltarte el análisis.', remember:'Los hechos reducen el universo de métodos plausibles, pero no eligen por sí solos al ganador.' },
  { heading:'La teoría necesita datos capaces de sostenerla', paragraphs:['Un método conceptualmente atractivo puede perder confiabilidad si la información necesaria no existe, es inconsistente o exige ajustes difíciles de estimar.','La disponibilidad de un comparable interno puede ser especialmente valiosa, pero sigue sujeto a análisis de producto, volumen, mercado, términos y funciones.'], example:'Una operación con tercero parece comparable, pero difiere materialmente en volumen y crédito. Antes de usarla como CUP interno debes evaluar si esas diferencias pueden analizarse o ajustarse de manera fiable.', chair:'La base de datos no selecciona el método; la calidad de la evidencia sí condiciona su aplicación.', remember:'Información disponible y confiabilidad son conceptos relacionados, pero no idénticos.' },
  { heading:'Cada método tolera diferencias de manera distinta', paragraphs:['La comparabilidad no es una revisión separada de la selección del método. Cada método observa una condición distinta y, por ello, ciertas diferencias pueden ser más críticas para uno que para otro.','CUP suele ser muy sensible a diferencias de producto y términos. TNMM puede tolerar algunas diferencias de producto mejor, pero sigue siendo sensible a diferencias funcionales, contables y de clasificación.'], example:'Dos productos similares pueden no sostener un CUP fiable, mientras una comparación de márgenes netos de entidades funcionalmente comparables podría resultar más robusta.', chair:'No preguntes sólo si hay comparables; pregunta qué diferencias afectan la comparación específica que propone el método.', remember:'La comparabilidad es relativa al método y a la condición examinada.' },
  { heading:'La tested party es una conclusión funcional', paragraphs:['En métodos unilaterales como TNMM, la parte analizada suele ser aquella para la cual el método puede aplicarse con mayor confiabilidad y para la cual existen comparables razonables.','Con frecuencia será la parte funcionalmente menos compleja y sin contribuciones únicas y valiosas relevantes. Menos compleja no significa más pequeña ni menos importante corporativamente.'], example:'Una distribuidora rutinaria sin intangibles únicos puede ser tested party frente a una relacionada que controla estrategia global y posee intangibles valiosos.', chair:'Selecciona tested party después del FAR, nunca por organigrama.', remember:'La parte analizada se elige por confiabilidad metodológica y perfil funcional.' },
  { heading:'No conviertas una preferencia doctrinal en una jerarquía mecánica', paragraphs:['Los métodos tradicionales y los métodos basados en resultados deben compararse según confiabilidad. No existe una regla que autorice a usar TNMM sólo porque sea frecuente en la práctica.','Cuando una comparación directa y otra indirecta pueden aplicarse con igual grado de confiabilidad, la comparación más directa puede tener una ventaja analítica.'], example:'Un CUP interno altamente comparable no debe ignorarse sólo porque ya exista una búsqueda TNMM preparada.', chair:'La costumbre operativa de la firma nunca sustituye la pregunta por la mejor evidencia.', remember:'La selección debe justificarse caso por caso.' },
  { heading:'Una buena selección deja visible el razonamiento', paragraphs:['La justificación debe identificar la operación delimitada, FAR, métodos considerados, información disponible, fortalezas y limitaciones relevantes, método seleccionado y razón de mayor confiabilidad.','Las frases genéricas —“es el más usado”, “es el mejor”, “es estándar para distribuidores”— son conclusiones sin análisis.'], example:'Una buena justificación explica por qué CUP pierde confiabilidad, por qué el margen bruto es inconsistente y por qué TNMM cuenta con comparables operativos funcionalmente útiles.', chair:'Si otro profesional no puede reconstruir por qué descartaste alternativas, la justificación está incompleta.', remember:'La selección del método debe ser trazable, no sólo plausible.' },
  { heading:'Laboratorio: comparar alternativas antes de decidir', paragraphs:['Caso A: mismo componente vendido a relacionada e independiente bajo condiciones muy similares y diferencia de flete cuantificable: investiga CUP interno primero. Caso B: fabricante rutinario con datos comparables de mark-up: Cost Plus o TNMM pueden ser plausibles según la calidad de datos.','Caso C: distribuidor rutinario sin CUP ni márgenes brutos consistentes pero con márgenes operativos confiables: TNMM puede ganar confiabilidad relativa. Caso D: dos partes con intangibles únicos e integración profunda: Profit Split merece consideración seria.'], example:'Manufacturas del Bajío: sin CUP suficientemente comparable, margen bruto inconsistente y márgenes operativos públicos razonablemente confiables de fabricantes comparables, TNMM aplicado a la manufacturera puede ser provisionalmente el método más apropiado.', chair:'No selecciones un método porque el caso “se parece” a otro; compara la evidencia disponible en este caso.', remember:'El método más apropiado es el que ofrece la aplicación más confiable bajo los hechos disponibles.' },
];

export function C2LessonPage(){
  const unlocked=typeof window!=='undefined'&&window.localStorage.getItem('tp-c2-unlocked')==='true';
  const {lessonNumber}=useParams(); const sequence=Number(lessonNumber); const lesson=c2Lessons.find(i=>i.sequence===sequence);
  useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('C2',lesson.sequence,c2Lessons.length);},[lesson,unlocked]);
  if(!unlocked)return <Navigate to="/path" replace/>; if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/c2" replace/>;
  const body=lessonBodies[sequence-1]; const assessment=c2Assessments.find(i=>i.lesson===sequence); const previous=sequence>1?sequence-1:null; const next=sequence<c2Lessons.length?sequence+1:null;
  const check=assessment?{id:`c2-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:assessment.prompt,correctOptionId:`option-${assessment.correctIndex}`,options:assessment.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===assessment.correctIndex?assessment.feedback:'Compara la opción con la naturaleza de la operación, FAR, datos y confiabilidad relativa antes de volver a intentarlo.'}))}:null;
  return <><div className="lesson-topbar"><div className="container"><Link to="/courses/c2">← C2 · Selección del Método Más Apropiado</Link><span>Lección {sequence} de {c2Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Consultant · C2</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(item=><li key={item}>{item}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('C2',sequence,c2Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav" aria-label="Navegación entre lecciones">{previous?<Link className="button secondary" to={`/courses/c2/lesson/${previous}`}>← Lección anterior</Link>:<span/>}{next?<Link className="button primary" to={`/courses/c2/lesson/${next}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/c2">Volver al curso</Link>}</nav></article></>;
}
