import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { c3Lessons } from '../content/curriculum/v1/c3';
import { c3Assessments } from '../content/curriculum/v1/c3Assessments';
import { markCourseLessonCompleted, markCourseLessonVisited } from '../services/courseProgress';

const bodies=[
{heading:'TNMM compara rentabilidad neta, no precio unitario',paragraphs:['TNMM compara un margen neto relativo a una base apropiada —ventas, costos o activos— obtenido por una parte en una operación controlada con márgenes de comparables independientes.','Puede ser menos sensible que CUP a ciertas diferencias de producto, pero sigue siendo sensible a diferencias funcionales, contables y de estructura de costos.'],example:'Un distribuidor con Operating Margin de 5% no se compara por el precio de cada producto, sino por su rentabilidad operativa respecto de ventas.',chair:'La fórmula es sencilla; la confiabilidad depende de qué operación, qué parte y qué datos estás midiendo.',remember:'TNMM no elimina la comparabilidad: cambia la condición económica observada.'},
{heading:'La tested party es una conclusión funcional',paragraphs:['La parte analizada suele ser aquella para la cual el método puede aplicarse con mayor confiabilidad y para la cual existan comparables razonables.','Con frecuencia será la parte funcionalmente menos compleja y sin contribuciones únicas y valiosas relevantes.'],example:'Una manufacturera rutinaria puede ser tested party frente a una relacionada que controla intangibles y riesgos estratégicos.',chair:'No elijas la parte que “conviene” al resultado; elige la que permite la prueba más confiable.',remember:'Menos compleja no significa más pequeña ni menos rentable.'},
{heading:'El PLI debe corresponder a la economía de la actividad',paragraphs:['Operating Margin relaciona utilidad operativa con ventas; Mark-up on Costs con costos relevantes; Berry Ratio con gastos operativos vía utilidad bruta; ROA con activos operativos.','El denominador expresa una hipótesis sobre qué base económica refleja mejor la creación de valor de la tested party.'],example:'Para manufactura rutinaria, una base de costos puede ser más informativa; para distribución, ventas pueden ser una base razonable según los hechos.',chair:'No memorices “tipo de empresa = PLI”. Explica por qué el denominador representa la actividad.',remember:'Un PLI técnicamente correcto puede ser conceptualmente incorrecto si la base no refleja el perfil funcional.'},
{heading:'Primero define utilidad operativa de forma consistente',paragraphs:['En C3 se separan ventas, costo de ventas, gastos operativos y utilidad operativa de intereses, partidas extraordinarias e impuestos.','En casos reales la clasificación puede requerir análisis adicional, pero la consistencia entre tested party y comparables sigue siendo esencial.'],example:'Si intereses se incluyen en una empresa y se excluyen en comparables, el margen deja de ser consistente.',chair:'Antes de calcular, pregunta qué entra al numerador y por qué.',remember:'Una fórmula impecable con datos mal clasificados produce una conclusión débil.'},
{heading:'Los estados totales pueden mezclar negocios distintos',paragraphs:['Cuando una entidad realiza múltiples actividades, la rentabilidad total puede no representar la operación analizada.','La segmentación debe asignar ingresos, costos y gastos con criterios razonables, consistentes y documentables.'],example:'Una compañía fabrica para relacionada y distribuye productos de terceros; mezclar ambos segmentos puede distorsionar el PLI de manufactura.',chair:'Segmentar no es “hacer números bonitos”; es aislar la economía de la operación analizada.',remember:'La segmentación debe ser defendible y reproducible.'},
{heading:'Cálculo: sencillo no significa trivial',paragraphs:['Operating Margin = Utilidad Operativa / Ventas. Mark-up on Costs = Utilidad Operativa / Costos relevantes. Berry Ratio = Utilidad Bruta / Gastos Operativos. ROA = Utilidad Operativa / Activos operativos.','El reto profesional no es dividir; es usar datos y bases económicamente correctos.'],example:'Ventas 1,000 y utilidad operativa 50 producen Operating Margin de 5.0%; utilidad 100 sobre costos 800 produce mark-up de 12.5%.',chair:'Comprueba siempre numerador, denominador, periodo y consistencia antes de interpretar.',remember:'El cálculo es el último paso de una cadena de decisiones técnicas.'},
{heading:'Estar dentro del rango no prueba todo',paragraphs:['El resultado del PLI debe contrastarse con un rango derivado de comparables confiables.','Una conclusión correcta se limita a la operación, tested party, PLI, periodo y comparables analizados.'],example:'Operating Margin de 5% frente a rango 3%–7% indica que el resultado está dentro de la referencia del ejercicio; no que toda la entidad sea arm’s length en absoluto.',chair:'Una conclusión profesional también se reconoce por lo que evita afirmar.',remember:'No extrapoles el rango más allá del alcance del análisis.'},
{heading:'Laboratorio: del dato a la conclusión',paragraphs:['El laboratorio usa el Dataset Didáctico C3 para calcular PLI, separar partidas y justificar segmentación.','En Manufacturas del Bajío, ventas 1,200, utilidad operativa 90 y costos operativos totales 1,110 producen Operating Margin 7.5%, mark-up 8.11% y ROA 15.0%.'],example:'Si el rango de mark-up es 5%–10%, el 8.11% se encuentra dentro del rango bajo los supuestos del ejercicio.',chair:'No entregues sólo el porcentaje: documenta qué datos usaste, cómo los clasificaste y qué significa el resultado.',remember:'El laboratorio conecta selección metodológica, datos, PLI e interpretación.'}
];
export function C3LessonPage(){const unlocked=typeof window!=='undefined'&&localStorage.getItem('tp-c3-unlocked')==='true';const {lessonNumber}=useParams();const sequence=Number(lessonNumber);const lesson=c3Lessons.find(x=>x.sequence===sequence);useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('C3',lesson.sequence,c3Lessons.length)},[lesson,unlocked]);if(!unlocked)return <Navigate to="/path" replace/>;if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/c3" replace/>;const body=bodies[sequence-1];const a=c3Assessments.find(x=>x.lesson===sequence);const check=a?{id:`c3-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:a.prompt,correctOptionId:`option-${a.correctIndex}`,options:a.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===a.correctIndex?a.feedback:'Revisa el razonamiento de la lección y vuelve a intentarlo.'}))}:null;return <><div className="lesson-topbar"><div className="container"><Link to="/courses/c3">← C3 · TNMM / MTUO en la práctica</Link><span>Lección {sequence} de {c3Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Consultant · C3</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(i=><li key={i}>{i}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('C3',sequence,c3Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav">{sequence>1?<Link className="button secondary" to={`/courses/c3/lesson/${sequence-1}`}>← Lección anterior</Link>:<span/>}{sequence<c3Lessons.length?<Link className="button primary" to={`/courses/c3/lesson/${sequence+1}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/c3">Volver al curso</Link>}</nav></article></>}
