import { useEffect } from 'react';
import { Link,Navigate,useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { c4Lessons } from '../content/curriculum/v1/c4';
import { c4Assessments } from '../content/curriculum/v1/c4Assessments';
import { markCourseLessonCompleted,markCourseLessonVisited } from '../services/courseProgress';
const bodies=[
{heading:'Comparabilidad no significa identidad',paragraphs:['Dos operaciones o empresas pueden ser comparables si sus diferencias no afectan materialmente la condición examinada o si pueden ajustarse con suficiente confiabilidad.','Antes de buscar debes saber qué operación está delimitada, qué parte se analiza, qué método se aplicará y qué características económicas son relevantes.'],example:'Dos distribuidores del mismo sector pueden no ser comparables si uno desarrolla marca y asume riesgos estratégicos mientras el otro realiza funciones rutinarias.',chair:'La industria orienta; la economía de la operación decide.',remember:'Buscar antes de delimitar la operación invierte el orden técnico.'},
{heading:'Nueve pasos como mapa de trabajo',paragraphs:['La lógica de la Academy sigue el proceso de nueve pasos: años cubiertos; circunstancias del contribuyente; operación y parte analizada; comparables internos; fuentes externas; método y PLI; candidatos; ajustes; interpretación.','La secuencia es pedagógica y puede ser iterativa en la práctica.'],example:'Antes de abrir una base externa, el consultor ya debe haber entendido la operación y revisado si existen transacciones comparables con terceros.',chair:'Una búsqueda sólida comienza mucho antes del botón Search.',remember:'El proceso conecta delimitación, método, búsqueda, ajustes e interpretación.'},
{heading:'Interno no significa automáticamente perfecto',paragraphs:['Un comparable interno surge cuando una de las partes realiza una operación potencialmente comparable con un tercero independiente. Un comparable externo se identifica fuera de las partes analizadas.','El interno puede ofrecer información rica sobre contratos, producto, volumen y condiciones, pero todavía deben evaluarse diferencias.'],example:'Ventas del mismo producto a un tercero pueden ser un comparable interno potencial, sujeto a volumen, mercado, términos y demás condiciones.',chair:'Más información mejora el análisis; no sustituye el análisis.',remember:'Revisa comparables internos antes de depender de fuentes externas.'},
{heading:'Los criterios nacen del FAR',paragraphs:['Actividad, geografía, independencia, información financiera, periodo, tamaño cuando sea relevante, pérdidas justificadas e intangibles pueden formar parte de los criterios.','No deben diseñarse para obtener muchos resultados ni para producir el rango esperado.'],example:'Si buscas un fabricante rutinario, excluir actividades de diseño e intangibles propios responde al perfil funcional, no al margen observado.',chair:'Define el filtro antes de saber a quién elimina.',remember:'Criterios ex ante reducen el riesgo de sesgo ex post.'},
{heading:'Reducir universo no es concluir comparabilidad',paragraphs:['Filtros cuantitativos usan datos estructurados como ventas, activos, años, códigos e independencia.','La revisión cualitativa exige leer descripciones, productos, segmentos, intangibles, manufactura, distribución, servicios e integración vertical.'],example:'Un código industrial puede devolver fabricantes por contrato y empresas con marca e I+D; la lectura cualitativa distingue sus perfiles.',chair:'El código encuentra candidatos; el análisis funcional decide si merecen seguir.',remember:'Los códigos de industria no sustituyen la revisión funcional.'},
{heading:'Cada decisión debe poder explicarse',paragraphs:['Accept indica que el candidato cumple los criterios y no se identifican diferencias incompatibles con la información disponible. Reject requiere una razón concreta y documentable.','Cuando la evidencia no alcanza, Review / información insuficiente es más profesional que forzar una clasificación.'],example:'Distribuciones Centro parece distribuidor, pero si no sabemos si fabrica parte relevante de sus productos, mantener Review es defendible.',chair:'La incertidumbre bien identificada es mejor que una certeza inventada.',remember:'“Margen alto” o “margen bajo” no son razones autónomas de rechazo.'},
{heading:'Una búsqueda debe dejar huella reproducible',paragraphs:['Documenta fuente, fecha, universo inicial, criterios, filtros, conteos por etapas, revisión cualitativa, razones Accept/Reject, conjunto final y limitaciones.','La lógica debe poder trasladarse entre herramientas y no depender de una base propietaria específica.'],example:'Otro analista debería poder entender por qué 120 candidatos se convirtieron en 8 comparables finales y qué ocurrió en cada etapa relevante.',chair:'Si no puedes reconstruir la búsqueda, difícilmente puedes defenderla.',remember:'Documentar no es burocracia: es parte del razonamiento técnico.'},
{heading:'Laboratorio: decide sin mirar el margen',paragraphs:['Para un distribuidor rutinario, Norte Distribución Industrial y Comercial Delta son Accept; Ingeniería Sigma y Marca Omega son Reject; Distribuciones Centro permanece Review por información insuficiente.','En Manufacturas del Bajío, Precision Contract Manufacturing y Standard Assembly Corp. son Accept; Innovatech Components e Integrated Systems Group son Reject; Manufacturing Services Ltd. no es usable por falta de información financiera del periodo.'],example:'Precision fabrica por contrato sin I+D relevante: su perfil es compatible. Innovatech diseña y patenta productos: las diferencias funcionales e intangibles justifican Reject.',chair:'Primero decide comparabilidad. Después observa el resultado financiero.',remember:'No manipules el rango eliminando candidatos por su margen.'}
];
export function C4LessonPage(){const unlocked=typeof window!=='undefined'&&localStorage.getItem('tp-c4-unlocked')==='true';const{lessonNumber}=useParams();const sequence=Number(lessonNumber);const lesson=c4Lessons.find(x=>x.sequence===sequence);useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('C4',lesson.sequence,c4Lessons.length)},[lesson,unlocked]);if(!unlocked)return <Navigate to="/path" replace/>;if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/c4" replace/>;const body=bodies[sequence-1];const a=c4Assessments.find(x=>x.lesson===sequence);const check=a?{id:`c4-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:a.prompt,correctOptionId:`option-${a.correctIndex}`,options:a.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===a.correctIndex?a.feedback:'Revisa el razonamiento de la lección y vuelve a intentarlo.'}))}:null;return <><div className="lesson-topbar"><div className="container"><Link to="/courses/c4">← C4 · Comparabilidad y Comparables</Link><span>Lección {sequence} de {c4Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Consultant · C4</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(i=><li key={i}>{i}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('C4',sequence,c4Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav">{sequence>1?<Link className="button secondary" to={`/courses/c4/lesson/${sequence-1}`}>← Lección anterior</Link>:<span/>}{sequence<c4Lessons.length?<Link className="button primary" to={`/courses/c4/lesson/${sequence+1}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/c4">Volver al curso</Link>}</nav></article></>}
