import { useEffect } from 'react';
import { Link,Navigate,useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { c5Lessons } from '../content/curriculum/v1/c5';
import { c5Assessments } from '../content/curriculum/v1/c5Assessments';
import { markCourseLessonCompleted,markCourseLessonVisited } from '../services/courseProgress';
const bodies=[
{heading:'Ajustar sólo tiene sentido si mejora comparabilidad',paragraphs:['El objetivo de un ajuste no es acercar artificialmente un resultado a una mediana o conclusión deseada. Debe reducir el efecto de una diferencia material que afecta la condición examinada.','Si el ajuste introduce datos débiles o demasiados supuestos, puede disminuir confiabilidad aunque parezca más sofisticado.'],example:'Una diferencia importante en condiciones de crédito puede justificar análisis; una corrección basada en supuestos no verificables puede empeorar la comparación.',chair:'No preguntes primero cómo ajustar. Pregunta primero si deberías ajustar.',remember:'Sofisticación no equivale a confiabilidad.'},
{heading:'Existencia, materialidad y cuantificación',paragraphs:['Antes de calcular, confirma que la diferencia existe, que puede afectar materialmente el indicador y que su efecto puede cuantificarse razonablemente.','Si falla materialidad o cuantificación fiable, documentar la limitación puede ser mejor que fabricar precisión.'],example:'32 vs. 30 días de cobro pueden ser una diferencia real pero no necesariamente material.',chair:'Una diferencia observable todavía no es una diferencia ajustable.',remember:'No toda diferencia merece ajuste.'},
{heading:'Capital de trabajo desde la economía, no desde la fórmula',paragraphs:['Mayores cuentas por cobrar pueden representar financiamiento a clientes; mayores cuentas por pagar, crédito comercial de proveedores; inventarios, recursos inmovilizados y costos asociados.','Las metodologías pueden variar en promedios, bases, tasas, periodos y signos.'],example:'Dos distribuidores similares con 60 y 30 días de cobro pueden enfrentar necesidades de financiamiento distintas.',chair:'Entiende qué recurso está financiado antes de decidir el signo o la fórmula.',remember:'Ejemplo didáctico no significa fórmula universal de mercado.'},
{heading:'PP&E e intensidad de capital',paragraphs:['Diferencias en maquinaria, instalaciones o activos operativos pueden afectar la rentabilidad esperada de funciones similares.','Antes de ajustar deben revisarse función de activos, antigüedad, depreciación, políticas contables y confiabilidad de la base.'],example:'Dos fabricantes rutinarios pueden ser funcionalmente similares pero operar con intensidades de capital muy distintas.',chair:'El saldo de PP&E por sí solo no explica la economía de los activos.',remember:'No ajustes PP&E mecánicamente.'},
{heading:'Los ajustes no viven sólo en el balance',paragraphs:['Plazos, garantías, exclusividad, entrega, duración, volumen y condiciones de mercado pueden afectar precios o márgenes.','Una diferencia geográfica o de volumen sólo justifica ajuste cuando existe evidencia de relevancia económica.'],example:'Un descuento por volumen documentado puede sustentar un ajuste cuando las cantidades son materialmente distintas.',chair:'La evidencia del efecto económico importa más que la etiqueta de la diferencia.',remember:'Geografía distinta no implica ajuste automático.'},
{heading:'Hay diferencias que un ajuste no puede salvar',paragraphs:['Funciones, activos y riesgos pueden diferir tanto que ningún ajuste razonable convierte a dos entidades en comparables.','Primero deben buscarse mejores comparables antes de acumular correcciones sobre candidatos deficientes.'],example:'Distribuidor rutinario vs. fabricante-distribuidor con I+D y marca propia: la diferencia es conceptual, no sólo financiera.',chair:'No uses fórmulas para rescatar un comparable que nunca debió entrar al set.',remember:'Mejor comparable suele ser preferible a más ajustes.'},
{heading:'No ajustar también puede ser una decisión técnica',paragraphs:['Puede ser correcto no ajustar cuando la diferencia no es material, no es cuantificable, los datos son débiles o el ajuste añade supuestos sin mejorar confiabilidad.','La decisión debe documentarse igual que una decisión de ajustar.'],example:'Una diferencia mínima en días de cobro puede no justificar una corrección si no cambia materialmente la comparación.',chair:'La ausencia de ajuste no significa ausencia de análisis.',remember:'No ajustar debe estar razonado y documentado.'},
{heading:'Laboratorio: decide antes de calcular',paragraphs:['Evalúa CxC, PP&E, volumen y comparables funcionalmente deficientes con la secuencia existencia → materialidad → cuantificación → confiabilidad.','En Manufacturas del Bajío, inventarios y activos productivos superiores al set requieren primero datos comparables, consistencia contable, naturaleza de activos, periodos y una metodología justificable.'],example:'Si no puede estimarse confiablemente el efecto, la respuesta profesional puede ser documentar la limitación o reconsiderar comparables.',chair:'La fórmula llega al final, nunca al principio.',remember:'Un ajuste sólo procede si mejora la comparación.'}
];
export function C5LessonPage(){const unlocked=typeof window!=='undefined'&&localStorage.getItem('tp-c5-unlocked')==='true';const{lessonNumber}=useParams();const sequence=Number(lessonNumber);const lesson=c5Lessons.find(x=>x.sequence===sequence);useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('C5',lesson.sequence,c5Lessons.length)},[lesson,unlocked]);if(!unlocked)return <Navigate to="/path" replace/>;if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/c5" replace/>;const body=bodies[sequence-1];const a=c5Assessments.find(x=>x.lesson===sequence);const check=a?{id:`c5-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:a.prompt,correctOptionId:`option-${a.correctIndex}`,options:a.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===a.correctIndex?a.feedback:'Revisa el razonamiento de la lección y vuelve a intentarlo.'}))}:null;return <><div className="lesson-topbar"><div className="container"><Link to="/courses/c5">← C5 · Ajustes de Comparabilidad</Link><span>Lección {sequence} de {c5Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Consultant · C5</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(i=><li key={i}>{i}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('C5',sequence,c5Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav">{sequence>1?<Link className="button secondary" to={`/courses/c5/lesson/${sequence-1}`}>← Lección anterior</Link>:<span/>}{sequence<c5Lessons.length?<Link className="button primary" to={`/courses/c5/lesson/${sequence+1}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/c5">Volver al curso</Link>}</nav></article></>}
