import { useEffect } from 'react';import { Link,Navigate,useParams } from 'react-router-dom';import { FormativeCheck } from '../components/learning/FormativeCheck';import { c6Lessons } from '../content/curriculum/v1/c6';import { c6Assessments } from '../content/curriculum/v1/c6Assessments';import { markCourseLessonCompleted,markCourseLessonVisited } from '../services/courseProgress';
const bodies=[
{heading:'El rango refleja pluralidad de mercado',paragraphs:['Empresas independientes pueden obtener resultados distintos bajo circunstancias comparables.','El rango sintetiza esa pluralidad; no identifica un único resultado correcto.'],example:'2.8%, 3.4%, 4.1%, 4.7% y 5.2% pueden coexistir dentro de un análisis confiable.',chair:'El rango es una salida del análisis, no su punto de partida.',remember:'Primero comparabilidad; después estadística.'},
{heading:'Rango completo: mínimo a máximo',paragraphs:['El rango completo contiene todas las observaciones seleccionadas entre el mínimo y el máximo.','No debe confundirse automáticamente con una regla legal local.'],example:'2.8%, 3.4%, 4.1%, 4.7%, 5.2% → rango completo 2.8%–5.2%.',chair:'No conviertas una definición estadística en una conclusión jurídica.',remember:'La legislación aplicable puede establecer reglas específicas.'},
{heading:'Q1 y Q3 dependen de una convención explícita',paragraphs:['El rango intercuartil se ubica entre Q1 y Q3.','Herramientas distintas pueden emplear convenciones inclusivas o exclusivas diferentes.'],example:'En un ejercicio, la Academy indicará expresamente la convención aplicable.',chair:'Si dos programas difieren, revisa primero la convención antes de asumir un error.',remember:'No existe una única implementación computacional universal de cuartiles.'},
{heading:'La mediana es tendencia central, no precio correcto',paragraphs:['En una distribución impar es el valor central; en una par, el promedio de los dos centrales.','Su papel jurídico depende de la norma aplicable.'],example:'2%, 3%, 5%, 8% → mediana 4%.',chair:'No ajustes a mediana por reflejo.',remember:'Estar por debajo de la mediana no implica automáticamente incumplimiento.'},
{heading:'Ubica la tested party frente al rango',paragraphs:['Una vez definido el rango, se compara el resultado de la parte analizada.','La conclusión económica básica debe separarse de cualquier consecuencia fiscal local.'],example:'IQR 3.2%–5.8%; tested party 4.6% → dentro del rango.',chair:'Describe posición antes de opinar sobre consecuencias.',remember:'Fuera del rango no significa automáticamente “ajuste a mediana”.'},
{heading:'La estadística no repara comparables débiles',paragraphs:['Una observación funcionalmente inadecuada no se vuelve comparable por quedar absorbida por un IQR.','La secuencia correcta es delimitar, seleccionar método, comparables, ajustes y sólo después estadística.'],example:'Una empresa con intangibles únicos no se neutraliza simplemente con cuartiles.',chair:'Una mala selección con buenos decimales sigue siendo una mala selección.',remember:'El rango no crea comparabilidad.'},
{heading:'Extremo no significa inválido',paragraphs:['Un margen extremo requiere investigación, no exclusión automática.','La razón de rechazo debe ser económica, funcional, financiera o de calidad de datos.'],example:'Si una empresa con 9.5% sigue cumpliendo criterios objetivos, no se elimina sólo porque amplía el rango.',chair:'Nunca inventes una razón de rechazo después de ver el resultado.',remember:'Eliminar por resultado es cherry-picking.'},
{heading:'Conclusión técnica: contexto, método y límites',paragraphs:['La conclusión debe identificar universo, PLI, periodo, metodología estadística, resultado de la tested party, posición frente al rango y límites.','Manufacturas del Bajío presenta 5.9% frente a Q1 4.95%, mediana 5.70% y Q3 6.25%.'],example:'5.9% está dentro del rango y por encima de mediana; ello no implica incumplimiento.',chair:'Una buena conclusión también dice qué no está concluyendo.',remember:'Separa siempre análisis económico de regla jurídica local.'}
];
export function C6LessonPage(){const unlocked=typeof window!=='undefined'&&localStorage.getItem('tp-c6-unlocked')==='true';const{lessonNumber}=useParams();const sequence=Number(lessonNumber);const lesson=c6Lessons.find(x=>x.sequence===sequence);useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('C6',lesson.sequence,c6Lessons.length)},[lesson,unlocked]);if(!unlocked)return <Navigate to="/path" replace/>;if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/c6" replace/>;const body=bodies[sequence-1];const a=c6Assessments.find(x=>x.lesson===sequence);const check=a?{id:`c6-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:a.prompt,correctOptionId:`option-${a.correctIndex}`,options:a.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===a.correctIndex?a.feedback:'Revisa el razonamiento de la lección y vuelve a intentarlo.'}))}:null;return <><div className="lesson-topbar"><div className="container"><Link to="/courses/c6">← C6 · El Rango de Plena Competencia</Link><span>Lección {sequence} de {c6Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Consultant · C6</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(i=><li key={i}>{i}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="concept-callout"><strong>Aplicación</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('C6',sequence,c6Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav">{sequence>1?<Link className="button secondary" to={`/courses/c6/lesson/${sequence-1}`}>← Lección anterior</Link>:<span/>}{sequence<c6Lessons.length?<Link className="button primary" to={`/courses/c6/lesson/${sequence+1}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/c6">Volver al curso</Link>}</nav></article></>}
