import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { FormativeCheck } from '../components/learning/FormativeCheck';
import { j5Lessons } from '../content/curriculum/v1/j5';
import { j5Assessments } from '../content/curriculum/v1/j5Assessments';
import { markCourseLessonCompleted, markCourseLessonVisited } from '../services/courseProgress';

const lessonBodies = [
  { heading: 'Comparable no significa simplemente parecido', paragraphs: ['Un comparable es una operación o entidad independiente que puede servir como referencia para evaluar una operación controlada. La palabra clave es “puede”: compartir industria, producto o mercado no basta por sí solo.', 'La pregunta correcta es si las diferencias entre la operación controlada y la referencia afectan materialmente el precio, margen o condición analizada y, de ser así, si pueden ajustarse de manera razonablemente confiable.'], example: 'Una empresa vende el mismo producto a una relacionada y a un tercero en el mismo mercado y periodo. La referencia parece fuerte, pero un volumen diez veces mayor con descuentos significativos exige análisis adicional.', chair: 'No preguntes primero si dos cosas se parecen. Pregunta qué diferencias podrían cambiar la condición que estás midiendo.', remember: 'Comparabilidad es una evaluación económica de diferencias materiales, no una coincidencia superficial.' },
  { heading: 'El comparable interno nace dentro de la experiencia de una de las partes', paragraphs: ['Existe cuando una de las partes de la operación controlada también realiza una operación similar con una parte independiente.', 'Puede ofrecer información más detallada y un contexto transaccional mejor conocido, pero no es automáticamente confiable: deben revisarse volumen, mercado, funciones, términos, fecha, nivel comercial y demás condiciones relevantes.'], example: 'Un fabricante vende el mismo producto a su distribuidora relacionada y a un distribuidor independiente. La venta independiente es una referencia potencialmente valiosa, sujeta al análisis de diferencias.', chair: '“Interno” puede significar mejor información, no una aprobación automática.', remember: 'La calidad del comparable interno depende de los hechos y de la comparabilidad real de las condiciones.' },
  { heading: 'El comparable externo exige mirar más allá del código de industria', paragraphs: ['Un comparable externo proviene de operaciones o empresas independientes que no participan directamente en la transacción controlada. Puede identificarse en información pública, bases de datos, mercados observables u otras fuentes.', 'El error típico es encontrar empresas bajo el mismo código de industria y asumir que realizan funciones equivalentes. La descripción de negocio, FAR y calidad de los datos siguen siendo decisivos.'], example: 'Para analizar un distribuidor relacionado se identifican distribuidores independientes. Antes de aceptarlos debe confirmarse qué hacen realmente, qué activos usan y qué riesgos asumen.', chair: 'Una base de datos te entrega candidatos; el análisis convierte algunos de ellos en comparables.', remember: 'Código de industria es un filtro inicial, no una conclusión de comparabilidad.' },
  { heading: 'Lo que se transfiere importa', paragraphs: ['Las características del bien, servicio o activo pueden afectar su valor. En bienes importan calidad, especificaciones, marca, volumen y etapa del producto; en servicios, naturaleza, complejidad, especialización y alcance; en intangibles, exclusividad, territorio, duración, protección y utilidad económica.', 'La similitud nominal no elimina diferencias económicamente relevantes.'], example: 'Dos préstamos por el mismo monto pueden tener valores distintos si uno está garantizado y el otro no, o si difieren en plazo y calidad crediticia.', chair: 'Describe aquello que se transfiere con suficiente precisión antes de buscar qué podría compararse con ello.', remember: 'Características económicas relevantes pueden romper una comparación aun cuando la etiqueta de la operación sea idéntica.' },
  { heading: 'FAR explica por qué dos negocios parecidos pueden ganar distinto', paragraphs: ['La comparabilidad no puede separarse del análisis funcional. Dos empresas que venden productos similares pueden tener perfiles económicos muy distintos.', 'Una distribuidora rutinaria y otra que desarrolla mercado, controla riesgos comerciales relevantes, mantiene inventario significativo o posee intangibles no deberían tratarse como equivalentes sólo porque venden productos semejantes.'], example: 'Dos distribuidores venden el mismo tipo de producto, pero uno posee una marca propia valiosa y ejecuta funciones estratégicas de marketing. La comparabilidad funcional requiere especial atención.', chair: 'Parecido comercial no equivale a comparabilidad económica.', remember: 'Funciones, activos y riesgos ayudan a explicar diferencias legítimas de remuneración.' },
  { heading: 'Los contratos cambian la economía de una operación', paragraphs: ['Plazos de pago, garantías, exclusividad, volúmenes mínimos, duración, territorio, penalizaciones y condiciones de entrega pueden afectar precio, margen y riesgo.', 'La existencia del mismo producto no neutraliza esas diferencias. Debe entenderse su efecto económico y contrastar los términos con la conducta cuando corresponda.'], example: 'Dos distribuidores adquieren el mismo producto, pero uno compra un volumen mínimo anual mucho mayor y no tiene derecho de devolución. Esas condiciones pueden modificar su exposición económica.', chair: 'Lee el contrato como economista: identifica qué obligación, derecho o riesgo puede cambiar el precio o la rentabilidad.', remember: 'Términos contractuales comparables son parte de una comparación confiable.' },
  { heading: 'El mercado forma parte de la comparación', paragraphs: ['Geografía, tamaño de mercado, competencia, poder adquisitivo, costos locales, regulación, oferta, demanda y etapa del ciclo económico pueden afectar las condiciones observadas.', 'Por ello, trasladar una referencia entre mercados sin analizar el contexto puede producir una comparación débil.'], example: 'Un precio observado en un mercado con intensa competencia puede no ser directamente comparable con el de una jurisdicción donde existen pocos proveedores.', chair: 'Una cifra no viaja sola: lleva consigo el mercado en el que fue generada.', remember: 'Las circunstancias económicas pueden afectar materialmente precio y rentabilidad.' },
  { heading: 'Las estrategias importan cuando tienen sustancia', paragraphs: ['Entrada a mercados, lanzamiento de producto, penetración, expansión, mantenimiento de participación e innovación pueden afectar temporalmente precios o resultados.', 'Pero mencionar una estrategia no basta. Debe ser coherente con los hechos, tener sustancia económica y poder documentarse.'], example: 'Una empresa reduce precios durante una campaña documentada de penetración en un mercado nuevo. Esa situación puede afectar la comparación con una empresa madura del mismo sector.', chair: 'Una estrategia empresarial es un hecho a demostrar, no una explicación de último minuto para justificar un resultado.', remember: 'La estrategia puede afectar comparabilidad sólo cuando existe realmente y es económicamente relevante.' },
  { heading: 'Ajustar puede mejorar una comparación, pero también empeorarla', paragraphs: ['Cuando existe una diferencia material, pueden considerarse ajustes si permiten mejorar razonablemente la confiabilidad. Ejemplos conceptuales incluyen capital de trabajo, volumen, condiciones de pago, diferencias contractuales o geografía.', 'No toda diferencia debe ajustarse y no todo ajuste es confiable. Un cálculo basado en supuestos débiles puede introducir más error que el que intenta corregir. La aplicación técnica de ajustes se desarrollará en nivel Consultant.'], example: 'Manufacturas del Bajío vende el mismo componente a una relacionada y a un tercero, pero el tercero compra 40% más volumen y paga a 30 días mientras la relacionada paga a 90. La referencia es útil, pero las diferencias deben analizarse antes de concluir.', chair: 'Una búsqueda de comparables no comienza preguntando cuántas empresas encontramos. Comienza preguntando qué necesitamos comparar.', remember: 'Más comparables no significa mejor análisis; la confiabilidad de cada referencia es lo que importa.' },
];

export function J5LessonPage() {
  const { lessonNumber } = useParams();
  const sequence = Number(lessonNumber);
  const lesson = j5Lessons.find((item) => item.sequence === sequence);
  useEffect(() => { if (lesson) markCourseLessonVisited('J5', lesson.sequence, j5Lessons.length); }, [lesson]);
  if (!lesson || !Number.isInteger(sequence)) return <Navigate to="/courses/j5" replace />;
  const body = lessonBodies[sequence - 1];
  const assessment = j5Assessments.find((item) => item.lesson === sequence);
  const previous = sequence > 1 ? sequence - 1 : null;
  const next = sequence < j5Lessons.length ? sequence + 1 : null;
  const check = assessment ? { id: `j5-check-${sequence}`, title: `Lección ${sequence} · Comprobación`, prompt: assessment.prompt, correctOptionId: `option-${assessment.correctIndex}`, options: assessment.options.map((label, index) => ({ id: `option-${index}`, label, feedback: index === assessment.correctIndex ? assessment.feedback : 'Revisa el razonamiento de la lección y vuelve a intentarlo.' })) } : null;
  return <><div className="lesson-topbar"><div className="container"><Link to="/courses/j5">← J5 · Fundamentos de Comparabilidad</Link><span>Lección {sequence} de {j5Lessons.length}</span></div></div><article className="lesson-content"><div className="eyebrow">Junior · J5</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map((item) => <li key={item}>{item}</li>)}</ul></section><h2>{body.heading}</h2>{body.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<div className="concept-callout"><strong>Ejemplo</strong><p>{body.example}</p></div><section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{body.chair}</p></section>{check && <FormativeCheck check={check} onCorrect={() => markCourseLessonCompleted('J5', sequence, j5Lessons.length)} />}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{body.remember}</p></section><nav className="lesson-nav" aria-label="Navegación entre lecciones">{previous ? <Link className="button secondary" to={`/courses/j5/lesson/${previous}`}>← Lección anterior</Link> : <span />}{next ? <Link className="button primary" to={`/courses/j5/lesson/${next}`}>Siguiente lección →</Link> : <Link className="button primary" to="/courses/j5">Volver al curso</Link>}</nav></article></>;
}
