import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CourseProgressCard } from '../components/learning/CourseProgressCard';
import { j1Course,j1Lessons } from '../content/curriculum/v1/j1';import { j2Course,j2Lessons } from '../content/curriculum/v1/j2';import { j3Course,j3Lessons } from '../content/curriculum/v1/j3';import { j4Course,j4Lessons } from '../content/curriculum/v1/j4';import { j5Course,j5Lessons } from '../content/curriculum/v1/j5';
import { c1Course,c1Lessons } from '../content/curriculum/v1/c1';import { c2Course,c2Lessons } from '../content/curriculum/v1/c2';import { c3Course,c3Lessons } from '../content/curriculum/v1/c3';import { c4Course,c4Lessons } from '../content/curriculum/v1/c4';import { c5Course,c5Lessons } from '../content/curriculum/v1/c5';import { c6Course,c6Lessons } from '../content/curriculum/v1/c6';import { c7Course,c7Lessons } from '../content/curriculum/v1/c7';
import { ss1Course,ss1Lessons } from '../content/curriculum/v1/ss1';import { ss2Course,ss2Lessons } from '../content/curriculum/v1/ss2';import { ss3Course,ss3Lessons } from '../content/curriculum/v1/ss3';import { ss4Course,ss4Lessons } from '../content/curriculum/v1/ss4';import { ss5Course,ss5Lessons } from '../content/curriculum/v1/ss5';
import { courseProgressEventName, getCourseProgress } from '../services/courseProgress';
import { getProgress, progressEventName } from '../services/progress';

const juniorGuideUrl='https://drive.google.com/file/d/1Ql2l3w-6GRXRe2MMH_zKuqqW5qpXMB0N/view';

type MyPathPageProps={showLocalNote?:boolean};

export function LocalProgressNote(){return <aside className="local-progress-note"><strong>Sobre este progreso</strong><p>Por ahora se guarda sólo en este navegador mediante almacenamiento local. No contiene correo ni otra identidad. El nombre sólo se solicita si decides emitir tu certificado.</p></aside>}

export function MyPathPage({showLocalNote=true}:MyPathPageProps){
 const[version,setVersion]=useState(0);
 useEffect(()=>{const sync=()=>setVersion(v=>v+1);window.addEventListener(progressEventName,sync);window.addEventListener(courseProgressEventName,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(progressEventName,sync);window.removeEventListener(courseProgressEventName,sync);window.removeEventListener('storage',sync)}},[]);
 void version;
 const unlocked=(key:string)=>typeof window!=='undefined'&&localStorage.getItem(key)==='true';
 const progress={J1:getProgress(),J2:getCourseProgress('J2',j2Lessons.length),J3:getCourseProgress('J3',j3Lessons.length),J4:getCourseProgress('J4',j4Lessons.length),J5:getCourseProgress('J5',j5Lessons.length),C1:getCourseProgress('C1',c1Lessons.length),C2:getCourseProgress('C2',c2Lessons.length),C3:getCourseProgress('C3',c3Lessons.length),C4:getCourseProgress('C4',c4Lessons.length),C5:getCourseProgress('C5',c5Lessons.length),C6:getCourseProgress('C6',c6Lessons.length),C7:getCourseProgress('C7',c7Lessons.length),SS1:getCourseProgress('SS1',ss1Lessons.length),SS2:getCourseProgress('SS2',ss2Lessons.length),SS3:getCourseProgress('SS3',ss3Lessons.length),SS4:getCourseProgress('SS4',ss4Lessons.length),SS5:getCourseProgress('SS5',ss5Lessons.length)};
 const juniorCourses=[['J1',j1Course,j1Lessons,progress.J1],['J2',j2Course,j2Lessons,progress.J2],['J3',j3Course,j3Lessons,progress.J3],['J4',j4Course,j4Lessons,progress.J4],['J5',j5Course,j5Lessons,progress.J5]] as const;
 const allJuniorComplete=juniorCourses.every(([, ,lessons,p])=>p.completedLessons.length===lessons.length);
 const certificateIssued=Boolean(typeof window!=='undefined'&&localStorage.getItem('tp-junior-foundations-certificate'));
 const consultantUnlocked=unlocked('tp-consultant-level-unlocked');const consultantComplete=unlocked('tp-consultant-foundations-complete');const objectivePassed=unlocked('tp-consultant-cumulative-objective-passed');const practitionerUnlocked=unlocked('tp-practitioner-unlocked');const practitionerCertificate=Boolean(typeof window!=='undefined'&&localStorage.getItem('tp-practitioner-certificate'));
 return <section className="section my-path-page"><div className="container narrow"><div className="eyebrow">Mi Ruta</div><h1>Tu progreso, claro y sin ruido.</h1><p className="lead small">Puedes estudiar sin cuenta. Mientras uses este dispositivo y navegador, la Academy recuerda dónde te quedaste y qué lecciones has demostrado comprender mediante sus comprobaciones formativas.</p>
 {juniorCourses.map(([code,course,lessons,p])=><CourseProgressCard key={code} level="Junior" code={code} course={course} lessons={lessons} progress={p}/>)}
 <section className={`progress-card junior-foundations-card ${consultantUnlocked?'completed-level':''}`}><div className="progress-card-top"><div><span className="progress-kicker">Cierre de nivel</span><h2>Transfer Pricing Junior Foundations</h2></div><strong className="progress-percent">{consultantUnlocked?'✓':allJuniorComplete?'Ready':'—'}</strong></div><p className="progress-summary">{consultantUnlocked?'Nivel Junior aprobado. Consultant desbloqueado.':allJuniorComplete?'J1–J5 completos. Ya puedes presentar la evaluación acumulativa.':'Completa J1–J5 para habilitar la evaluación acumulativa.'}</p><div className="progress-actions"><a className="button secondary" href={juniorGuideUrl} target="_blank" rel="noreferrer">Guía integral Junior</a>{consultantUnlocked?<><Link className="button secondary" to="/junior-foundations/certificate">{certificateIssued?'Ver certificado':'Emitir certificado'}</Link><Link className="button primary" to="/courses/c1">Comenzar C1</Link></>:<Link className={`button primary ${!allJuniorComplete?'disabled-button':''}`} aria-disabled={!allJuniorComplete} to={allJuniorComplete?'/junior-foundations/assessment':'/path'}>Presentar evaluación</Link>}</div></section>
 {consultantUnlocked&&<CourseProgressCard level="Consultant" code="C1" course={c1Course} lessons={c1Lessons} progress={progress.C1}/>} {unlocked('tp-c2-unlocked')&&<CourseProgressCard level="Consultant" code="C2" course={c2Course} lessons={c2Lessons} progress={progress.C2}/>} {unlocked('tp-c3-unlocked')&&<CourseProgressCard level="Consultant" code="C3" course={c3Course} lessons={c3Lessons} progress={progress.C3}/>} {unlocked('tp-c4-unlocked')&&<CourseProgressCard level="Consultant" code="C4" course={c4Course} lessons={c4Lessons} progress={progress.C4}/>} {unlocked('tp-c5-unlocked')&&<CourseProgressCard level="Consultant" code="C5" course={c5Course} lessons={c5Lessons} progress={progress.C5}/>} {unlocked('tp-c6-unlocked')&&<CourseProgressCard level="Consultant" code="C6" course={c6Course} lessons={c6Lessons} progress={progress.C6}/>} {unlocked('tp-c7-unlocked')&&<CourseProgressCard level="Consultant" code="C7" course={c7Course} lessons={c7Lessons} progress={progress.C7}/>} 
 {consultantComplete&&<section className={`progress-card ${practitionerUnlocked?'completed-level':''}`}><div className="progress-card-top"><div><span className="progress-kicker">Cierre de nivel</span><h2>Transfer Pricing Practitioner</h2></div><strong className="progress-percent">{practitionerUnlocked?'✓':objectivePassed?'Case':'Ready'}</strong></div><p className="progress-summary">{practitionerUnlocked?'Nivel Practitioner aprobado. Semi Senior desbloqueado.':objectivePassed?'Componente objetivo aprobado. Falta el caso integrador obligatorio.':'C1–C7 completados. Presenta la evaluación acumulativa: ≥80% global y ningún dominio crítico debajo de 60%.'}</p><div className="progress-actions">{practitionerUnlocked?<><Link className="button secondary" to="/practitioner/certificate">{practitionerCertificate?'Ver certificado':'Emitir certificado'}</Link><Link className="button primary" to="/courses/ss1">Comenzar SS1</Link></>:<Link className="button primary" to={objectivePassed?'/consultant/case':'/consultant/assessment'}>{objectivePassed?'Resolver caso integrador':'Presentar evaluación acumulativa'}</Link>}</div></section>}
 {practitionerUnlocked&&<CourseProgressCard level="Semi Senior" code="SS1" course={ss1Course} lessons={ss1Lessons} progress={progress.SS1}/>} {unlocked('tp-ss2-unlocked')&&<CourseProgressCard level="Semi Senior" code="SS2" course={ss2Course} lessons={ss2Lessons} progress={progress.SS2}/>} {unlocked('tp-ss3-unlocked')&&<CourseProgressCard level="Semi Senior" code="SS3" course={ss3Course} lessons={ss3Lessons} progress={progress.SS3}/>} {unlocked('tp-ss4-unlocked')&&<CourseProgressCard level="Semi Senior" code="SS4" course={ss4Course} lessons={ss4Lessons} progress={progress.SS4}/>} {unlocked('tp-ss5-unlocked')&&<CourseProgressCard level="Semi Senior" code="SS5" course={ss5Course} lessons={ss5Lessons} progress={progress.SS5}/>} 
 {showLocalNote&&<LocalProgressNote/>}</div></section>}
