import{FormEvent,useEffect,useMemo,useState}from'react';import{Link,Navigate}from'react-router-dom';
type Domain='SERVICES'|'DEMPE'|'FINANCE'|'RESTRUCTURING'|'CCA'|'CONTROVERSY';type Question={id:number;domain:Domain;prompt:string;options:string[]};type Result={eligibilityId:string;score:number;passed:boolean;passedGlobal:boolean;passedDomains:boolean;domains:Record<Domain,number>};
const ELIGIBILITY_KEY='tp-advanced-practitioner-eligibility-id';const labels:Record<Domain,string>={SERVICES:'Servicios intragrupo',DEMPE:'Intangibles y DEMPE',FINANCE:'Operaciones financieras',RESTRUCTURING:'Reestructuraciones',CCA:'Cost Contribution Arrangements',CONTROVERSY:'Controversias y documentación'};
export function SemiSeniorAssessmentPage(){const eligible=typeof window!=='undefined'&&localStorage.getItem('tp-semi-senior-foundations-complete')==='true';const[attemptId,setAttemptId]=useState('');const[questions,setQuestions]=useState<Question[]>([]);const[answers,setAnswers]=useState<Record<number,number>>({});const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const answered=Object.keys(answers).length;const counts=useMemo(()=>Object.fromEntries((Object.keys(labels)as Domain[]).map(d=>[d,questions.filter(q=>q.domain===d).length]))as Record<Domain,number>,[questions]);
  async function start(){setLoading(true);setError('');setAnswers({});setResult(null);try{const r=await fetch('/api/advanced-practitioner/attempt',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:'{}'});if(!r.ok)throw new Error('No fue posible iniciar la evaluación.');const data=await r.json() as{attemptId:string;questions:Question[]};setAttemptId(data.attemptId);setQuestions(data.questions);}catch(e){setError(e instanceof Error?e.message:'No fue posible iniciar la evaluación.');}finally{setLoading(false);}}
  useEffect(()=>{if(eligible)void start();else setLoading(false);},[eligible]);if(!eligible)return <Navigate to="/path" replace/>;
  async function grade(e:FormEvent){e.preventDefault();if(answered!==questions.length)return;setError('');const r=await fetch('/api/advanced-practitioner/grade',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({attemptId,answers})});if(!r.ok){setError('No fue posible calificar la evaluación.');return;}const next=await r.json() as Result;setResult(next);if(next.passed)localStorage.setItem(ELIGIBILITY_KEY,next.eligibilityId);window.scrollTo({top:0,behavior:'smooth'});}
  if(loading)return <section className="section"><div className="container narrow"><h1>Preparando evaluación…</h1><p className="lead small">Generando un intento authoritative en servidor.</p></div></section>;
  if(result){return <section className="section"><div className="container narrow assessment-result"><div className="eyebrow">Advanced Transfer Pricing Practitioner</div><h1>{result.passed?'Componente acumulativo aprobado':'Hay dominios que necesitan refuerzo'}</h1><div className="result-score"><strong>{result.score}%</strong><span>calificación global</span></div><div className="materials-grid">{(Object.keys(labels)as Domain[]).map(d=><article className="material-card" key={d}><span className="material-type">Dominio crítico</span><h3>{labels[d]}</h3><p><strong>{result.domains[d]}%</strong> · {counts[d]} reactivos</p><small>{result.domains[d]>=60?'Dominio acreditado':'Requiere ≥60%'}</small></article>)}</div>{result.passed?<><p>La Academy validó en servidor ≥80% global y ≥60% en cada dominio. Ahora debes aprobar ambos casos avanzados.</p><Link className="button primary" to={`/semi-senior/cases?eligibilityId=${encodeURIComponent(result.eligibilityId)}`}>Resolver casos avanzados</Link></>:<><p>Necesitas ≥80% global y ≥60% en cada dominio.</p><button className="button primary" onClick={()=>void start()}>Intentar de nuevo</button></>}{error&&<p role="alert">{error}</p>}</div></section>;}
  return <section className="section assessment-page"><div className="container narrow"><div className="eyebrow">Evaluación acumulativa · Semi Senior</div><h1>Advanced Transfer Pricing Practitioner</h1><p className="lead small">24 reactivos estratificados en seis dominios. La selección y corrección se realizan en servidor. Necesitas 80% global y al menos 60% en cada dominio.</p><div className="assessment-progress"><strong>{answered} / {questions.length}</strong><span>respondidas</span></div>{error&&<p role="alert">{error}</p>}<form onSubmit={grade}>{questions.map((q,i)=><fieldset className="assessment-question" key={q.id}><legend><span>{i+1}</span><small>{labels[q.domain]}</small>{q.prompt}</legend>{q.options.map((o,oi)=><label className="assessment-option" key={o}><input type="radio" name={`q-${q.id}`} checked={answers[q.id]===oi} onChange={()=>setAnswers(a=>({...a,[q.id]:oi}))}/><span>{o}</span></label>)}</fieldset>)}<button className="button primary assessment-submit" disabled={answered!==questions.length}>Calificar evaluación</button></form></div></section>}
