import { useEffect } from 'react';import { Link,Navigate,useParams } from 'react-router-dom';import { FormativeCheck } from '../components/learning/FormativeCheck';import { ss1Lessons } from '../content/curriculum/v1/ss1';import { ss1Assessments } from '../content/curriculum/v1/ss1Assessments';import { markCourseLessonCompleted,markCourseLessonVisited } from '../services/courseProgress';
const bodies=[
{h:'Primero demuestra que existe el servicio',p:['Antes de discutir precio o mark-up, debe analizarse si existe una actividad por la que un independiente pagaría o que realizaría internamente. Una factura, reporte o interacción no bastan por sí solos.'],chair:'No empieces por el porcentaje; empieza por la sustancia.',remember:'Actividad intragrupo no equivale automáticamente a servicio remunerable.'},
{h:'Beneficio esperado, no éxito ex post',p:['El benefit test pregunta si el receptor obtiene o razonablemente espera obtener valor económico o comercial. No exige que el servicio produzca utilidad financiera inmediata.'],chair:'Describe qué cambió o se mantuvo gracias al servicio y por qué el receptor lo necesitaba.',remember:'“Se recibió apoyo corporativo” es demasiado vago.'},
{h:'Accionista no es proveedor por definición',p:['Algunas actividades se realizan para proteger la inversión o cumplir obligaciones propias del accionista. La etiqueta corporativa no decide la clasificación; importan finalidad y beneficiario.'],chair:'Pregunta quién necesita la actividad y para qué.',remember:'No toda actividad de matriz es shareholder activity.'},
{h:'Compara el alcance real',p:['Dos funciones con nombres similares pueden tener alcances distintos. También puede existir beneficio incidental sin un servicio identificable dirigido al receptor.'],chair:'La similitud nominal no prueba duplicidad.',remember:'Duplicidad e incidental benefit se analizan en sustancia.'},
{h:'Cuando puedes seguir la huella del costo',p:['Direct charge es transparente cuando servicio, receptor y costos pueden identificarse de manera fiable, por ejemplo horas exclusivas respaldadas por time sheets.'],chair:'Trazabilidad primero; asignación sólo cuando la trazabilidad directa no sea práctica.',remember:'Direct charge reduce dependencia de allocation keys.'},
{h:'La clave debe representar el beneficio',p:['En servicios compartidos puede usarse indirect charge. Empleados, usuarios, dispositivos, facturas o transacciones pueden ser claves razonables según la actividad.'],chair:'Una métrica fácil de obtener no es necesariamente una buena allocation key.',remember:'No existe una clave universal para todos los servicios.'},
{h:'Cost base antes que mark-up',p:['Debe definirse qué costos corresponden al servicio y analizar pass-through costs. La naturaleza del servicio y la información disponible condicionan la remuneración.'],chair:'No apliques mark-up a una base que todavía no entiendes.',remember:'La Academy no prescribe un mark-up universal.'},
{h:'Simplificado no significa automático',p:['Los low-value-adding services son de apoyo, no core, sin intangibles únicos y valiosos y sin riesgos significativos, sujeto a los demás requisitos y a la legislación local.','En Manufacturas del Bajío, HR, ERP y cuentas por pagar pueden superar el benefit test; materiales de junta pueden ser shareholder activity; ingresos como única key requiere revisión.'],chair:'Primero clasifica cada actividad; luego diseña el pool y la asignación.',remember:'El precio viene después de existencia, beneficio, evidencia y asignación.'}
];
export function SS1LessonPage(){const unlocked=typeof window!=='undefined'&&localStorage.getItem('tp-practitioner-unlocked')==='true';const{lessonNumber}=useParams();const sequence=Number(lessonNumber);const lesson=ss1Lessons.find(x=>x.sequence===sequence);useEffect(()=>{if(lesson&&unlocked)markCourseLessonVisited('SS1',lesson.sequence,ss1Lessons.length)},[lesson,unlocked]);if(!unlocked)return <Navigate to="/path" replace/>;if(!lesson||!Number.isInteger(sequence))return <Navigate to="/courses/ss1" replace/>;const b=bodies[sequence-1];const a=ss1Assessments.find(x=>x.lesson===sequence);const check=a?{id:`ss1-check-${sequence}`,title:`Lección ${sequence} · Comprobación`,prompt:a.prompt,correctOptionId:`option-${a.correctIndex}`,options:a.options.map((label,index)=>({id:`option-${index}`,label,feedback:index===a.correctIndex?a.feedback:'Revisa la lección y vuelve a intentarlo.'}))}:null;return <><div className="lesson-topbar"><div className="container"><Link to="/courses/ss1">← SS1 · Servicios Intragrupo</Link><span>Lección {sequence} de 8</span></div></div><article className="lesson-content"><div className="eyebrow">Semi Senior · SS1</div><h1>{lesson.title}</h1><p className="lesson-meta">≈ {lesson.estimatedMinutes} min</p><section className="learning-outcomes"><h2>Al terminar esta lección podrás</h2><ul>{lesson.learningOutcomes.map(i=><li key={i}>{i}</li>)}</ul></section><h2>{b.h}</h2>{b.p.map(x=><p key={x}>{x}</p>)}<section className="consultant-card"><div className="eyebrow">La Silla del Consultor</div><h2>Criterio profesional</h2><p>{b.chair}</p></section>{check&&<FormativeCheck check={check} onCorrect={()=>markCourseLessonCompleted('SS1',sequence,ss1Lessons.length)}/>}<section className="remember-card"><strong>Lo que no debes olvidar</strong><p>{b.remember}</p></section><nav className="lesson-nav">{sequence>1?<Link className="button secondary" to={`/courses/ss1/lesson/${sequence-1}`}>← Lección anterior</Link>:<span/>}{sequence<8?<Link className="button primary" to={`/courses/ss1/lesson/${sequence+1}`}>Siguiente lección →</Link>:<Link className="button primary" to="/courses/ss1">Volver al curso</Link>}</nav></article></>}
